var sohupchome_automodels = {
    "count": "12",
    "modellist": [{
        "name": "本田CR-V",
        "url": "http://db.auto.sohu.com/dongfenghonda/1992?pvid=bf23bc17"
    },
    {
        "name": "丰田汉兰达",
        "url": "http://db.auto.sohu.com/guangqitoyota/1679?pvid=bf23bc17"
    },
    {
        "name": "本田思域",
        "url": "http://db.auto.sohu.com/dongfenghonda/1993?pvid=bf23bc17"
    },
    {
        "name": "奥迪A4L",
        "url": "http://db.auto.sohu.com/yiqiaudi/2374?pvid=bf23bc17"
    },
    {
        "name": "大众Tiguan",
        "url": "http://db.auto.sohu.com/jinkouvw/1626/?pvid=bf23bc17"
    },
    {
        "name": "日产轩逸",
        "url": "http://db.auto.sohu.com/dongfengnissan/1071?pvid=bf23bc17"
    },
    {
        "name": "荣威RX5",
        "url": "http://db.auto.sohu.com/roewe-2051/5045?pvid=bf23bc17"
    },
    {
        "name": "奔驰E级",
        "url": "http://db.auto.sohu.com/beijingbenz/2976?pvid=bf23bc17"
    },
    {
        "name": "大众蔚领",
        "url": "http://db.auto.sohu.com/yiqivw/5133?pvid=bf23bc17"
    },
    {
        "name": "本田冠道",
        "url": "http://db.auto.sohu.com/guangqihonda/5055?pvid=bf23bc17"
    },
    {
        "name": "大众捷达",
        "url": "http://db.auto.sohu.com/yiqivw/1001?pvid=bf23bc17"
    },
    {
        "name": "宝马5系",
        "url": "http://db.auto.sohu.com/huachenbmw/1233?pvid=bf23bc17"
    }]
}