(function(g){var window=this;var UY=function(a){a.g||(a.g=new g.kp,g.G(a,a.g));return a.g},VY=function(a){a.M("cardstatechange",a.qd()&&a.we()?1:0)},WY=function(a){var b=g.mi(a);
a=g.ti(a);return new g.Ph(b.x,b.y,a.width,a.height)},XY=function(a,b){var c=a.style;
"opacity"in c?c.opacity=b:"MozOpacity"in c?c.MozOpacity=b:"filter"in c&&(c.filter=""===b?"":"alpha(opacity="+100*Number(b)+")")},YY=function(a){return"none"!=a.style.display},lma=function(a){var b=g.gi(a,"fontSize");
var c=(c=b.match(hma))&&c[0]||null;if(b&&"px"==c)return parseInt(b,10);if(g.qe){if(String(c)in jma)return g.vi(a,b,"left","pixelLeft");if(a.parentNode&&1==a.parentNode.nodeType&&String(c)in kma)return a=a.parentNode,c=g.gi(a,"fontSize"),g.vi(a,b==c?"1em":b,"left","pixelLeft")}c=g.we("SPAN",{style:"visibility:hidden;position:absolute;line-height:0;padding:0;margin:0;border:0;height:1em;"});a.appendChild(c);b=c.offsetHeight;g.De(c);return b},mma=function(a){if(/-[a-z]/.test("pollChoiceIndex"))return null;
if(g.ll&&a.dataset){if(g.xc()&&!("pollChoiceIndex"in a.dataset))return null;a=a.dataset.pollChoiceIndex;return void 0===a?null:a}return a.getAttribute("data-"+g.Kc("pollChoiceIndex"))},aZ=function(a){a=g.Sa(a);
delete ZY[a];g.lc(ZY)&&$Y&&$Y.stop()},bZ=function(){$Y||($Y=new g.L(function(){nma()},20));
var a=$Y;a.isActive()||a.start()},nma=function(){var a=(0,g.B)();
g.Zb(ZY,function(b){cZ(b,a)});
g.lc(ZY)||bZ()},dZ=function(a,b){g.Vf.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.D;this.state=b.g},eZ=function(a,b,c,d){g.Jo.call(this);
if(!g.Ma(a)||!g.Ma(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.i=a;this.F=b;this.duration=c;this.C=d;this.coords=[];this.progress=this.D=0;this.A=null},cZ=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);1<a.progress&&(a.progress=1);a.D=1E3/(b-a.A);a.A=b;fZ(a,a.progress);1==a.progress?(a.g=0,aZ(a),a.Vc(),a.l()):1==a.g&&a.tr()},fZ=function(a,b){g.Oa(a.C)&&(b=a.C(b));
a.coords=Array(a.i.length);for(var c=0;c<a.i.length;c++)a.coords[c]=(a.F[c]-a.i[c])*b+a.i[c]},gZ=function(a,b,c,d,e){eZ.call(this,b,c,d,e);
this.element=a},hZ=function(a,b,c,d,e){if(2!=b.length||2!=c.length)throw Error("Start and end points must be 2D");
gZ.apply(this,arguments)},oma=function(a){return Math.pow(a,3)},pma=function(a){return 3*a*a-2*a*a*a},iZ=function(a){g.F.call(this);
this.i=a||window;this.g=[]},qma=function(a,b,c,d){c=(0,g.y)(c,d||a.i);
b=g.ns(b,"change",c,"iv-card-poll-choice-input");a.g.push(b)},jZ=function(a,b){(0,g.A)(b,function(b){g.at("visualElementShown",{csn:a,
ve:g.jt(b),eventType:4},g.ft,void 0,void 0)})},kZ=function(a,b){(0,g.A)(b,function(b){g.at("visualElementHidden",{csn:a,
ve:g.jt(b),eventType:8},g.ft,void 0,void 0)})},lZ=function(a,b,c){this.id=a;
this.timestamp=b.timestamp||0;this.type=b.card_type;this.teaserText=b.teaser_text;this.teaserDurationMs=b.teaser_duration_ms;this.startMs=b.start_ms;this.autoOpen=b.auto_open||!1;this.Wc=b.session_data||{};this.l=c;this.sponsored=b.sponsored||!1;a=b.tracking||{};this.i={VC:a.impression,click:a.click,close:a.close,yL:a.teaser_impression,ts:a.teaser_click};b=b.tracking_params||{};this.A=g.it(b.card);this.D=g.it(b.teaser);this.u=g.it(b.icon)},mZ=function(a,b){g.tg.call(this);
this.xj=a;this.yp=b;this[g.Xf]=!1},rZ=function(a,b,c,d){mZ.call(this,a,b);
a=this.yp;b=this.ia();c?(b.setAttribute("stroke",c.i),b.setAttribute("stroke-opacity",1),c=c.g,g.t(c)&&-1!=c.indexOf("px")?b.setAttribute("stroke-width",parseFloat(c)/rma(a)):b.setAttribute("stroke-width",c)):b.setAttribute("stroke","none");this.fill=d;c=this.yp;a=this.ia();if(d instanceof nZ)a.setAttribute("fill",d.F),a.setAttribute("fill-opacity",d.H);else if(d instanceof oZ){b="lg-"+d.u+"-"+d.C+"-"+d.A+"-"+d.D+"-"+d.g+"-"+d.i;var e=b in c.g?c.g[b]:null;if(!e){e=pZ(c,"linearGradient",{x1:d.u,y1:d.C,
x2:d.A,y2:d.D,gradientUnits:"userSpaceOnUse"});var f="stop-color:"+d.g;g.Ha(d.l)&&(f+=";stop-opacity:"+d.l);f=pZ(c,"stop",{offset:"0%",style:f});e.appendChild(f);f="stop-color:"+d.i;g.Ha(d.o)&&(f+=";stop-opacity:"+d.o);d=pZ(c,"stop",{offset:"100%",style:f});e.appendChild(d);e=qZ(c,b,e)}a.setAttribute("fill","url(#"+e+")")}else a.setAttribute("fill","none")},sZ=function(){},tZ=function(a,b){mZ.call(this,a,b)},uZ=function(){this.Va=[];
this.Ba=[];this.Kd=[]},vZ=function(a,b,c,d){var e=a.sd[0]-b*Math.cos(g.Yd(d))+b*Math.cos(g.Yd(d+90)),f=a.sd[1]-c*Math.sin(g.Yd(d))+c*Math.sin(g.Yd(d+90));
a.Va.push(3);a.Ba.push(1);a.Kd.push(b,c,d,90,e,f);a.uk=!1;a.sd=[e,f]},tma=function(a,b){for(var c=a.Kd,d=0,e=0,f=a.Va.length;e<f;e++){var k=a.Va[e],l=sma[k]*a.Ba[e];
b(k,c.slice(d,d+l));d+=l}},wZ=function(a,b,c,d){rZ.call(this,a,b,c,d)},xZ=function(a,b){this.g=a;
this.i=b},yZ=function(a,b,c,d,e){g.Uo.call(this,e);
this.width=a;this.height=b;this.l=c||null;this.N=d||null},rma=function(a){var b=a.nj();
return b?b.width/(a.l?new g.be(a.l,a.N):a.nj()).width:0},oZ=function(a,b,c,d,e,f,k,l){this.u=a;
this.C=b;this.A=c;this.D=d;this.g=e;this.i=f;this.l=g.Fa(k)?k:null;this.o=g.Fa(l)?l:null},nZ=function(a,b){this.F=a;
this.H=null==b?1:b},zZ=function(a,b){mZ.call(this,a,b)},AZ=function(a,b,c,d){rZ.call(this,a,b,c,d)},BZ=function(a,b,c,d,e){yZ.call(this,a,b,c,d,e);
this.g={};this.R=g.se&&!g.Vc(526);this.K=new g.Nn(this)},pZ=function(a,b,c){a=a.O.g.createElementNS("http://www.w3.org/2000/svg",b);
if(c)for(var d in c)a.setAttribute(d,c[d]);return a},CZ=function(a,b,c,d){b=pZ(a,"path",{d:uma(b)});
c=new AZ(b,a,c,d);a.o.ia().appendChild(c.ia())},uma=function(a){var b=[];
tma(a,function(a,d){switch(a){case 0:b.push("M");Array.prototype.push.apply(b,d);break;case 1:b.push("L");Array.prototype.push.apply(b,d);break;case 2:b.push("C");Array.prototype.push.apply(b,d);break;case 3:var c=d[3];b.push("A",d[0],d[1],0,180<Math.abs(c)?1:0,0<c?1:0,d[4],d[5]);break;case 4:b.push("Z")}});
return b.join(" ")},qZ=function(a,b,c){if(b in a.g)return a.g[b];
var d="_svgdef_"+vma++;c.setAttribute("id",d);a.g[b]=d;a.C.appendChild(c);return d},wma=function(){DZ||(DZ=new g.fh(400),DZ.start());
return DZ},EZ=function(a,b){function c(a){return a.baseUrl}
function d(a){if(a){var b=a.simpleText;if(b)return b;if(a.runs)return(0,g.D)(a.runs,function(a){return a.text}).join("")}}
function e(a){if(a){var b=[],c=a.videoId;c&&b.push("v="+c);(c=a.playlistId)&&b.push("list="+c);(a=a.startTimeSeconds)&&b.push("t="+a);return"/watch?"+b.join("&")}}
var f={};f.startMs=parseInt(a.startMs,10);f.impressionUrls=(0,g.D)(a.impressionUrls||[],c);f.skip=a.skipEndscreen;f.visualElement=g.it(a.trackingParams);var k=(0,g.D)(a.elements||[],function(a,f){var k=a.endscreenElementRenderer;if(!k)return null;var l={},m=k.style,x=k.endpoint||{};l.id="element-"+f;l.type=m;l.title=d(k.title);l.metadata=d(k.metadata);l.callToAction=d(k.callToAction);l.Ku=k.image;l.left=parseFloat(k.left);l.width=parseFloat(k.width);l.top=parseFloat(k.top);l.aspectRatio=parseFloat(k.aspectRatio);
l.startMs=parseInt(k.startMs,10);l.endMs=parseInt(k.endMs,10);l.clickUrls=(0,g.D)(x.loggingUrls||[],c);l.Ok=g.gc(k,"title","accessibility","accessibilityData","label");l.impressionUrls=(0,g.D)(k.impressionUrls||[],c);l.TC=(0,g.D)(k.hovercardShowUrls||[],c);l.Wc={itct:k.trackingParams};l.visualElement=g.it(k.trackingParams);if("VIDEO"==m)l.targetUrl=x.urlEndpoint?x.urlEndpoint.url:e(x.watchEndpoint),l.Ll=!1,l.yn=b,l.videoDuration=d(k.videoDuration);else if("PLAYLIST"==m)l.targetUrl=x.urlEndpoint?x.urlEndpoint.url:
e(x.watchEndpoint),l.Ll=!1,l.yn=b,l.playlistLength=d(k.playlistLength);else if("CHANNEL"==m){if(m=g.gc(x,"browseEndpoint","browseId"))l.channelId=m,l.targetUrl="/channel/"+m;l.Ll=!1;l.yn="new";l.isSubscribe=!!k.isSubscribe;if(l.isSubscribe){a:{if(m=k.hovercardButton)if(m=m.subscribeButtonRenderer){x=d(m.unsubscribedButtonText);var C=d(m.subscribedButtonText);if(m.subscribed){var E=d(m.subscriberCountWithUnsubscribeText);var H=d(m.subscriberCountText)}else E=d(m.subscriberCountText),H=d(m.subscriberCountWithSubscribeText);
var S=null;if(k.signinEndpoint&&(S=g.gc(k,"signinEndpoint","webNavigationEndpointData","url"),!S)){k=void 0;break a}if(x&&(C||S)){k={subscribed:m.subscribed,subscribeText:x,subscribeCount:E,unsubscribeText:C,unsubscribeCount:H,enabled:m.enabled,signinUrl:S,classic:k.useClassicSubscribeButton};break a}}k=void 0}l.subscribeButton=k}else l.subscribersText=d(k.subscribersText)}else"WEBSITE"==m&&(l.targetUrl=g.gc(x,"urlEndpoint","url"),l.Ll=!0,l.yn="new",l.iconUrl=k.icon.thumbnails[0].url);return l});
f.elements=(0,g.Ee)(k,function(a){return!!a});
return f},FZ=function(a){g.pK.call(this,a);
this.i=null;this.H=!1;this.o=null;this.g={};this.C={};this.A=this.l=null;this.N=[];a=g.V(a);this.K=g.az(a)||g.bz(a);this.Qz=!0;this.D=0;this.F=new g.zo;this.u=new g.rs(this);g.G(this,this.u);this.u.J(this.player,g.TD("creatorendscreen"),this.RD);this.u.J(this.player,"crx_creatorendscreen",this.SD);this.u.J(this.player,"resize",this.rb);this.u.J(window,"focus",this.EK);this.load();var b=g.ye("STYLE");(document.getElementsByTagName("HEAD")[0]||document.body).appendChild(b);g.Sf(this,function(){g.De(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},GZ=function(a){return a.player.getVideoData().ac?"current":a.K?"new":"current"},HZ=function(a){return"creator-endscreen-editor"===a},IZ=function(a,b){g.ZJ(a.player,"creatorendscreen");
a.l&&(a.l.dispose(),a.l=null,a.A.dispose(),a.A=null);for(var c in a.g)a.g[c].dispose();a.g={};a.C={};0<a.N.length&&(a.N.forEach(function(a){a.dispose()}),a.N.length=0);
a.D=0;if((a.i=b)&&b.elements){xma(a);c=[];var d=new g.QD(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);g.V(a.player).g||(a.l=new g.T({B:"div",G:"ytp-ce-shadow"}),g.cK(a.player,a.l.element,4),a.A=new g.BP(a.l,200));for(d=0;d<b.elements.length;++d){var e=b.elements[d],f=yma(a,e);a.g[e.id]=f;a.C[e.id]=e;g.cK(a.player,f.element,4);var k=new g.QD(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(k);zma(a,f,e)}g.WJ(a.player,
c);a.rb()}},xma=function(a){var b=g.Ct(),c=g.Dt();
c&&b&&g.kt(c,b,[a.i.visualElement])},yma=function(a,b){var c=null;
switch(b.type){case "VIDEO":c={B:"div",V:["ytp-ce-element","ytp-ce-video"],L:{tabindex:"0","aria-label":b.Ok||"","aria-hidden":"true"},I:[{B:"div",G:"ytp-ce-element-shadow"},{B:"div",G:"ytp-ce-covering-image",L:JZ(b)},{B:"div",G:"ytp-ce-covering-shadow-top"},{B:"a",G:"ytp-ce-covering-overlay",L:{href:b.targetUrl,tabindex:"-1"},I:[{B:"div",V:["ytp-ce-video-title","yt-ui-ellipsis","yt-ui-ellipsis-2"],L:{dir:g.Ao(a.F,b.title||"")},U:b.title},{B:"div",G:"ytp-ce-video-duration",U:b.videoDuration}]}]};
c=new g.T(c);break;case "PLAYLIST":c={B:"div",V:["ytp-ce-element","ytp-ce-playlist"],L:{tabindex:"0","aria-label":b.Ok||"","aria-hidden":"true"},I:[{B:"div",G:"ytp-ce-element-shadow"},{B:"div",G:"ytp-ce-covering-image",L:JZ(b)},{B:"div",G:"ytp-ce-covering-shadow-top"},{B:"a",G:"ytp-ce-covering-overlay",L:{href:b.targetUrl,tabindex:"-1"},I:[{B:"div",V:["ytp-ce-playlist-title","yt-ui-ellipsis","yt-ui-ellipsis-2"],L:{dir:g.Ao(a.F,b.title||"")},U:b.title},{B:"div",G:"ytp-ce-playlist-count",I:[{B:"div",
G:"ytp-ce-playlist-icon"},{B:"div",G:"ytp-ce-playlist-count-text",U:b.playlistLength}]}]}]};c=new g.T(c);break;case "CHANNEL":c={B:"div",V:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],L:{tabindex:"0","aria-label":b.Ok||"","aria-hidden":"true"},I:[{B:"div",G:"ytp-ce-element-shadow"},{B:"div",G:"ytp-ce-expanding-overlay",I:[{B:"div",G:"ytp-ce-expanding-overlay-hider"},{B:"div",G:"ytp-ce-expanding-overlay-background"},{B:"div",G:"ytp-ce-expanding-overlay-content",
I:[{B:"div",G:"ytp-ce-expanding-overlay-body",I:[{B:"div",G:"ytp-ce-expanding-overlay-body-padding",I:[{B:"a",V:["ytp-ce-channel-title","ytp-ce-link"],L:{href:b.targetUrl,target:"_blank",tabindex:"-1",dir:g.Ao(a.F,b.title||"")},U:b.title},b.subscribeButton?{B:"div",G:"ytp-ce-subscribe-container",I:[{B:"div",G:"ytp-ce-channel-subscribe"}]}:"",b.subscribersText?{B:"div",G:"ytp-ce-channel-subscribers-text",U:b.subscribersText}:"",b.metadata?{B:"div",V:["ytp-ce-channel-metadata","yt-ui-ellipsis","yt-ui-ellipsis-3"],
U:b.metadata}:""]}]}]}]},{B:"div",G:"ytp-ce-expanding-image",L:JZ(b)}]};c=new g.T(c);var d=g.ie(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton){g.J(d,"ytp-ce-subscribe-button");if(g.V(a.player).g){var e=null;var f=b.Wc.itct}else e="endscreen",f=null;e=new g.pV(b.subscribeButton.subscribeText,b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,b.subscribeButton.enabled,b.subscribeButton.classic,b.channelId,!!b.subscribeButton.subscribed,
e,f,b.subscribeButton.signinUrl,a.player);d.appendChild(e.element);a.N.push(e)}break;case "WEBSITE":c={B:"div",V:["ytp-ce-element","ytp-ce-website"],L:{tabindex:"0","aria-label":b.Ok||"","aria-hidden":"true"},I:[{B:"div",G:"ytp-ce-element-shadow"},{B:"div",G:"ytp-ce-expanding-overlay",I:[{B:"div",G:"ytp-ce-expanding-overlay-hider"},{B:"div",G:"ytp-ce-expanding-overlay-background"},{B:"div",G:"ytp-ce-expanding-overlay-content",I:[{B:"div",G:"ytp-ce-expanding-overlay-body",I:[{B:"div",G:"ytp-ce-expanding-overlay-body-padding",
I:[{B:"div",G:"ytp-ce-website-title",L:{dir:g.Ao(a.F,b.title||"")},U:b.title},{B:"div",G:"ytp-ce-website-metadata",U:b.metadata},{B:"a",V:["ytp-ce-website-goto","ytp-ce-link"],L:{href:b.targetUrl,target:"_blank",tabindex:"-1"},U:b.callToAction}]}]}]}]},{B:"div",G:"ytp-ce-expanding-image",L:JZ(b)},{B:"div",G:"ytp-ce-expanding-icon",L:KZ(b.iconUrl)}]},c=new g.T(c)}b.g&&g.J(c.element,"ytp-ce-placeholder");return c},JZ=function(a){if(a.Ku)var b=a.Ku.thumbnails;
return KZ(b?b[b.length-1].url:null)},KZ=function(a){return a?{style:"background-image: url("+a+")"}:{}},zma=function(a,b,c){function d(){k(1)}
function e(){k(-1)}
b.ca("mouseenter",(0,g.y)(a.Eq,a,b,c));b.ca("mouseleave",(0,g.y)(a.Ar,a,b,c));g.V(a.player).g||b.ca("click",(0,g.y)(function(a){g.J(a.element,"ytp-ce-element-hover")},a,b));
b.ca("click",(0,g.y)(a.by,a,c));b.ca("keypress",(0,g.y)(a.by,a,c));b.ca("focus",(0,g.y)(function(a,b){this.Eq(a,b)},a,b,c));
b.ca("blur",(0,g.y)(function(a,b){this.Ar(a,b)},a,b,c));
b.ca("touchstart",(0,g.y)(a.Eq,a,b,c));var f=g.ke("ytp-ce-expanding-overlay-hider",b.element);f&&b.J(f,"touchstart",function(a){g.js(a);g.Go(b.element,"ytp-ce-element-hover");g.Go(b.element,"ytp-ce-force-expand")});
b.ca("keydown",(0,g.y)(function(a,b){this.Qz=9==b.keyCode&&!b.shiftKey},a,b));
var k=(0,g.y)(function(a,b,c){this.D+=c;0<this.D?(g.J(a.element,"ytp-ce-force-expand"),LZ(this,b.id,!0)):(g.Go(a.element,"ytp-ce-force-expand"),g.Go(a.element,"ytp-ce-element-hover"),LZ(this,b.id,!1))},a,b,c);
a=(0,g.y)(function(a,b){b&&(a.ca("blur",function(){YY(b)&&this.Qz&&b.focus()}),a.J(b,"focus",d),a.J(b,"blur",e))},a,b);
a(g.ke("ytp-sb-subscribe",b.element));a(g.ke("ytp-sb-unsubscribe",b.element));b.ca("focus",d);b.ca("blur",e)},LZ=function(a,b,c){a.l&&(c?a.A.show():a.A.hide());
for(var d in a.g)d!=b&&g.K(a.g[d].element,"ytp-ce-element-shadow-show",c)},MZ=function(a,b,c){function d(){f||(e++,e==b.length&&(k.stop(),c&&c()))}
if(!b||HZ(g.V(a.player).playerStyle))c&&c();else{b=Ama(a,b);var e=0,f=!1,k=new g.L(function(){f=!0;c&&c()},1E3,a);
k.start();for(a=0;a<b.length;a++)g.Ar(b[a],d)}},NZ=function(a,b,c){MZ(a,b.clickUrls,c);
(a=g.Dt())&&b.Ll&&g.mt(a,b.visualElement)},Ama=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce,d=a.player.getCurrentTime().toFixed(2);
c={CPN:c,AD_CPN:c,MT:d};d=[];for(var e=0;e<b.length;e++)d.push(Bma(b[e],c));return d},Bma=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(a){var c=unescape(a);
c=c.substring(1,c.length-1);return b[c]?escape(b[c]):a})},OZ=function(a){return g.Ma(a)&&a.length?a[0]:a},PZ=function(a){var b=/.+/;
return g.t(a)&&null!=b&&null!=a&&a.match(b)?a:""},QZ=function(a,b){if(null==a)return b;
var c=parseInt(a,0);if(isNaN(c))return b;c=c.toString(16);return"#"+"000000".substring(0,6-c.length)+c},RZ=function(a){return g.t(a)?a:""},SZ=function(a,b,c){for(var d in b)if(b[d]==a)return a;
return c},TZ=function(a,b){return"true"==a||"false"==a?"true"==a:b},UZ=function(a,b){return g.t(a)?parseFloat(a):b},VZ=function(a,b,c,d,e){a=parseFloat(a);
if(null!=a&&!isNaN(a)){if(d)return g.Ud(a,b,c);if(a>=b&&a<=c)return a}return e},Cma=function(a){if(null==a)return 0;
if("never"==a)return-1;a=a.split(":");if(3<a.length)return 0;var b=0,c=1;(0,g.A)(a,function(a){a=parseFloat(a);0>a&&(c=-c);b=60*b+Math.abs(a)});
return c*b},WZ=function(a,b){if(null==a)return null;
if(g.Na(a)){var c=[];(0,g.A)(a,function(a){(a=b(a))&&c.push(a)});
return c}var d=b(a);return d?[d]:[]},Dma=function(a){function b(a){return null!=a&&!isNaN(a)}
return(a=a?new g.Mh(parseFloat(a.top),parseFloat(a.right),parseFloat(a.bottom),parseFloat(a.left)):null)&&b(a.top)&&b(a.right)&&b(a.bottom)&&b(a.left)?a:null},Ema=function(a){function b(a){return(0,g.Ee)(a.split(/ +/),function(a){return""!=a})}
return null==a?[]:b(a)},Fma=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.g=d},XZ=function(a){if(!a)return null;
var b=g.ud(RZ(a.value));b=g.rd(b);if(!b)return null;var c=SZ(a.target,Gma,"current");return null==c?null:new Fma(b,c,TZ(a.show_link_icon,!0),null!=a.pause_on_navigation?a.pause_on_navigation:!0)},YZ=function(a){return a.value?a.value:null},Hma=function(a,b,c){this.type=a;
this.trigger=b;this.url=c},Kma=function(a){if(!a)return null;
var b=SZ(a.type,Ima),c=SZ(a.trigger,Jma),d=OZ(a.url);d=XZ(d?d:null);OZ(a.subscribeData);return b?new Hma(b,c,d):null},ZZ=function(a,b,c){var d=(c="xx"==c||"xy"==c)?640:360;
return(d+((c?a.width:a.height)-d)*b)/d},$Z=function(a,b,c){var d=(c="xy"==c||"yy"==c)?360:640;
return(d+((c?a.height:a.width)-d)*b)/d},a_=function(a,b,c,d,e,f,k,l,m,n,p){this.x=a;
this.y=b;this.Bi=c;this.l=d;this.t=e;this.u=f;this.A=k;this.C=l;this.o=m;this.i=n;this.g=p},b_=function(a,b){if(!a)return null;
var c=UZ(a.x,0),d=UZ(a.y,0),e=UZ(a.w,0),f=UZ(a.h,0),k=Cma(a.t),l=UZ(a.d,0),m=UZ(a.px,0),n=UZ(a.py,0),p=UZ(a.scaleSlope,1),u=UZ(a.scaleSlopeX,p);p=UZ(a.scaleSlopeY,p);var x=SZ(a.scaleDimension,Lma,"xy");return b(c,d,e,f,k,l,m,n,u,p,x)},e_=function(a,b){var c=c_(b,d_(a,new g.Ph(a.x,a.y,a.Bi,a.l),b.g)),d=b.g,e=c.clone();
d&&!d.contains(c)&&(c.width<d.width?e.left=g.Ud(c.left,d.left,d.left+d.width-c.width):(e.left=d.left,e.width=d.width),c.height<d.height?e.top=g.Ud(c.top,d.top,d.top+d.height-c.height):(e.top=d.top,e.height=d.height));return e},d_=function(a,b,c){var d=a.A,e=a.C,f=a.g?a.g:"xy",k=ZZ(c,a.o,f);
a=$Z(c,a.i,f);f=640*b.width*k/100;var l=360*b.height*a/100;return new g.Ph(0==d?640*b.left*k/100:0<d?d:c.width+d-f,0==e?360*b.top*a/100:0<e?e:c.height+e-l,f,l)},f_=function(a){return a?b_(a,function(a,c,d,e,f,k,l,m,n,p,u){return new a_(a,c,d,e,f,k,l,m,n,p,u)}):null},g_=function(a,b){this.g=a;
this.i=b||null},c_=function(a,b){var c=a.i?e_(a.i,new g_(a.g)):a.g;
var d=b.clone(),e=c.left;c=c.top;e instanceof g.$d?(d.left+=e.x,d.top+=e.y):(d.left+=e,g.Ha(c)&&(d.top+=c));return d},h_=function(a,b,c,d,e,f,k,l,m,n,p,u,x){a_.call(this,a,b,c,d,e,l,m,n,p,u,x);
this.D=f;this.F=k},Mma=function(a){if(!a)return null;
var b=UZ(a.sx,0),c=UZ(a.sy,0);return b_(a,function(a,e,f,k,l,m,n,p,u,x,C){return new h_(a,e,f,k,l,b,c,m,n,p,u,x,C)})},Nma=function(a,b,c,d,e,f,k,l,m,n,p,u,x,C){this.i=a;
this.bgColor=b;this.borderColor=c;this.borderWidth=d;this.g=e;this.A=f;this.l=k;this.textAlign=l;this.textSize=m;this.o=n;this.padding=p;this.effects=u;this.cornerRadius=x;this.u=C},i_=function(a){if(!a)return null;
var b=QZ(a.fgColor,"#1A1A1A"),c=QZ(a.bgColor,"#FFF"),d=QZ(a.borderColor,"#000"),e=VZ(a.borderWidth,0,5,!1,0),f=VZ(a.bgAlpha,0,1,!1,.8),k=QZ(a.highlightFontColor,"#F2F2F2"),l=VZ(a.highlightWidth,0,5,!1,3),m=RZ(a.textAlign),n=VZ(a.textSize,3.3,30.1,!0,3.6107),p=RZ(a.fontWeight),u=Dma(a.padding),x=Ema(a.effects),C=VZ(a.cornerRadius,0,10,!0,0);a=OZ(a.gradient);if(a=a?a:null){var E=VZ(a.x1,0,100,!0,0),H=VZ(a.y1,0,100,!0,0),S=VZ(a.x2,0,100,!0,100),X=VZ(a.y2,0,100,!0,100),ra=QZ(a.color1,"#FFF"),wb=QZ(a.color2,
"#000");a=new Oma(E,H,S,X,ra,wb,VZ(a.opacity1,0,100,!0,100),VZ(a.opacity2,0,100,!0,0))}else a=null;return new Nma(b,c,d,e,f,k,l,m,n,p,u,x,C,a)},Oma=function(a,b,c,d,e,f,k,l){this.l=a;
this.u=b;this.o=c;this.A=d;this.g=e;this.i=f;this.C=k;this.D=l},Pma=function(a,b,c,d){this.type=a;
this.i=b;this.g=c;this.l=d},Rma=function(a){if(!a)return null;
var b=SZ(a.type,Qma,"rect"),c=WZ(a.rectRegion,f_),d=WZ(a.anchoredRegion,Mma);a=WZ(a.shapelessRegion,f_);return new Pma(b,c,d,a)},j_=function(a){return a.i&&a.i.length?a.i[0]:a.g&&a.g.length?a.g[0]:a.l&&a.l.length?a.l[0]:null},Sma=function(a,b){this.i=a;
this.g=b},Tma=function(a,b){this.state=a;
this.ref=b},k_=function(a){if(!a)return null;
var b=SZ(a.state,Uma);a=PZ(a.ref);return b?new Tma(b,a):null},Vma=function(a,b,c,d){this.g=a||[];
this.l=b||[];this.o=c;this.i=d;this.value=!1},Wma=function(a){if(!a)return null;
var b=WZ(a.condition,k_),c=WZ(a.notCondition,k_),d=TZ(a.show_delay,!1);a=TZ(a.hide_delay,!1);return b||c?new Vma(b,c,d,a):null},Xma=function(a,b,c){(0,g.A)(a.g,g.Va(b,!1),c);
(0,g.A)(a.l,g.Va(b,!0),c)},l_=function(a,b,c,d,e,f,k,l,m,n,p,u,x,C){this.id=a;
this.author=b;this.type=c;this.style=d;this.o=e;this.segment=f;this.l=k||[];this.C=l||[];this.i=m;this.A=n;this.u=p;this.data=u;this.g=x;this.itct=C},$ma=function(a){if(!a)return null;
var b=PZ(a.id),c=PZ(a.author),d=SZ(a.type,Yma),e=SZ(a.style,m_),f=RZ(OZ(a.TEXT)),k=RZ(a.data);k=0!=k.length?JSON.parse(k):{};var l=OZ(a.segment);var m=l?l:null;m?(PZ(m.timeRelative),l=PZ(m.spaceRelative),l=(m=WZ(m.movingRegion,Rma))?new Sma(l,m):null):l=null;m=WZ(a.action,Kma);var n=WZ(a.trigger,Wma),p=OZ(a.appearance);(p=i_(p?p:null))||(p=i_({}));var u=SZ(a.coordinate_system,Zma,"video_relative"),x=TZ(a.closeable,!0),C=RZ(a.log_data);a=RZ(a.itct);return b&&d?new l_(b,c,d,e,f,l,m,n,p,u,x,k,C,a):null},
o_=function(a){return n_(a,function(a){return"click"==a.trigger})},n_=function(a,b){return(0,g.gk)(a.l,b,void 0)},ana=function(a,b,c){(0,g.A)(a.l,b,c)},bna=function(a,b){return g.cb(a.l,b,void 0)},p_=function(a,b,c){(0,g.A)(a.C,b,c)},cna=function(a,b){(0,g.D)(a.C,b,void 0)},r_=function(a){return(a=q_(a))?j_(a):null},q_=function(a){a.segment?(a=a.segment,a=a.g.length?a.g[0]:null):a=null;
return a},s_=function(a,b){var c=r_(a);
return c&&b?$Z(b,c.i,c.g?c.g:"xy"):1},u_=function(a,b,c){this.g={};
this.l=!1;this.u="ivTrigger:"+a;this.i=c;Xma(b,function(a,b){var c=t_(b.state,b.ref);this.i.subscribe(c,(0,g.y)(this.o,this,c,a));this.g[c]=a},this)},t_=function(a,b){var c="ivTriggerCondition:"+a;
return b?c+":"+b:c},v_=function(){this.g=!1;
this.u=this.i=null},w_=function(a,b,c){a.i?(a.i.setSize(b,c),a.i.clear()):(b=new BZ(b,c,void 0,void 0,void 0),a.i=b,a.i.Dp(),a.u=g.we("DIV"),a.u.appendChild(a.i.ia()));
return a.i},x_=function(a,b,c){var d=document.createElementNS("http://www.w3.org/2000/svg",a);
b&&g.Zb(b,function(a,b){d.setAttribute(b,a)});
for(var e=2;e<arguments.length;e++)d.appendChild(arguments[e]);return d},y_=function(a,b){var c=g.To(g.So.getInstance());
b.setAttribute("result",c);a.appendChild(b);return c},dna=function(a,b){var c=y_(a,x_("feGaussianBlur",{"in":b,
stdDeviation:"1.8"}));c=y_(a,x_("feDiffuseLighting",{"in":c,surfaceScale:"4",diffuseConstant:"1"},x_("feDistantLight",{azimuth:"270",elevation:"15","lighting-color":"white"})));c=y_(a,x_("feComposite",{"in":c,in2:b,operator:"in"}));return y_(a,x_("feComposite",{in2:c,"in":b,operator:"arithmetic",k2:1,k3:.5,k4:0}))},ena=function(a,b){var c=y_(a,x_("feOffset",{"in":b,
dx:"-7",dy:"-7"}));c=y_(a,x_("feGaussianBlur",{"in":c,stdDeviation:"3"}));c=y_(a,x_("feColorMatrix",{"in":c,type:"matrix",values:"0 0 0 0 0  0 0 0 0 0  0 0 0 0 0  0 0 0 0.5 0"}));var d=y_(a,x_("feColorMatrix",{"in":b,type:"matrix",values:"0 0 0 0 0  0 0 0 0 0  0 0 0 0 0  0 0 0 100 0"}));d=y_(a,x_("feGaussianBlur",{"in":d,stdDeviation:"1"}));c=y_(a,x_("feComposite",{operator:"out","in":c,in2:d}));return y_(a,x_("feComposite",{operator:"over","in":b,in2:c}))},fna=function(a,b){return b},gna=function(a){var b=
x_("filter",{filterUnits:"userSpaceOnUse"}),c="SourceGraphic";
(0,g.A)(a,function(a){a:{switch(a){case "bevel":a=dna;break a;case "dropshadow":a=ena;break a}a=fna}c=a(b,c)});
return b},hna=function(a){a=(0,g.Ee)(a,function(a){return a in z_});
g.zb(a,function(a,c){return z_[a]-z_[c]});
return a},ina=function(a){return g.cb(a,function(a){return"dropshadow"==a})?new g.Mh(0,7,7,0):new g.Mh(0,0,0,0)},A_=function(a,b,c){var d=new uZ;
d.moveTo(a.left+b+c,a.top+c);d.Zb(a.left+a.width-b-c,a.top+c);vZ(d,b,b,-90);d.Zb(a.left+a.width-c,a.top+a.height-b-c);vZ(d,b,b,0);d.Zb(a.left+b+c,a.top+a.height-c);vZ(d,b,b,90);d.Zb(a.left+c,a.top+b+c);vZ(d,b,b,180);d.close();return d},B_=function(a,b,c,d){var e=a.u;
e?a=new oZ(e.l*b/100,e.u*c/100,e.o*b/100,e.A*c/100,e.g,e.i,e.C,e.D):(b=a.g,a=new nZ(a.bgColor,d?Math.max(b,.9):b));return a},C_=function(a,b){var c=g.Qh(a),d=ina(b);
g.Pa(d)?(c.top-=d.top,c.right+=d.right,c.bottom+=d.bottom,c.left-=d.left):(c.top-=d,c.right+=Number(void 0),c.bottom+=Number(void 0),c.left-=Number(void 0));return new g.Ph(c.left,c.top,c.right-c.left,c.bottom-c.top)},D_=function(a,b,c){if(c.length&&(b=g.ie(document,"g",void 0,b),b.length)){var d=hna(c);
if(d){c="effects:"+(d?d.join("|"):"");var e=c in a.g?a.g[c]:null;e?a=e:(d=gna(d),a=0<d.childNodes.length?qZ(a,c,d):null)}else a=null;a&&b[0].setAttribute("filter","url(#"+a+")")}},E_=function(){v_.call(this);
this.o=0},jna=function(a,b){var c=a.top-b.y,d=b.x-a.left-a.width,e=b.y-a.top-a.height,f=a.left-b.x,k=Math.max(c,d,e,f);
if(0>k)return"i";switch(k){case c:return"t";case d:return"r";case e:return"b";case f:return"l"}return"i"},F_=function(a){v_.apply(this,arguments)},G_=function(a){v_.apply(this,arguments)},H_=function(a){E_.apply(this,arguments)},I_=function(a,b,c,d,e){g.F.call(this);
this.g=a;this.P=b;this.A=c;this.ha=d;this.W=e;this.F=!1;this.aa=new iZ(this);g.G(this,this.aa);this.O=this.u=this.C=this.K=this.i=null;this.Z=!1;this.Y=this.H=this.N=null;this.Cm=new g.fm(this.tC,100,this);g.G(this,this.Cm);this.D=new g.L(this.Sv,500,this);g.G(this,this.D);this.R=this.l=this.o=null},kna=function(a,b){var c=(0,g.y)(function(a,c,f){c=f?J_(this,c,(0,g.y)(f,this)):J_(this,c);
this.aa.ca(b,a,c)},a);
c("mouseover","G",a.Pw);c("mouseout","F",a.kg);c("click","D");c("touchend","D")},lna=function(a){if(a.g.u){if(n_(a.g,function(a){return"close"==a.type}))var b=a.i;
else a.o=g.we("DIV","annotation-close-button"),g.ui(a.o,!1),g.nq(a.o,"annotation_id",a.g.id),a.i.appendChild(a.o),b=a.o;var c=function(a){a.stopPropagation()};
a.aa.ca(b,"click",J_(a,"E",c));a.aa.ca(b,"touchend",J_(a,"E",c))}},J_=function(a,b,c){return(0,g.y)(function(a){if(this.W)c&&c(a);
else if(a.event.target instanceof Element){var d=a.event.target;g.ui(d,!1);try{var f=document.elementFromPoint(a.event.clientX,a.event.clientY);if(g.Ne(f,null,"annotation",void 0)){var k=document.createEvent("MouseEvent");k.initMouseEvent(a.event.type,a.event.bubbles,a.event.cancelable,a.event.view,a.event.detail,a.event.screenX,a.event.screenY,a.event.clientX,a.event.clientY,a.event.ctrlKey,a.event.altKey,a.event.shiftKey,a.event.metaKey,a.event.button,a.event.relatedTarget);f.dispatchEvent(k)}}finally{g.ui(d,
!0)}}d=WY(a.target);a=new g.$d(a.clientX,a.clientY);"F"==b&&d.contains(a)||this.ha.M(b,this.g)},a)},M_=function(a){if(a.i||a.l){var b=r_(a.g);
if(b){var c=K_(a);if(a.i){b=e_(b,c);var d=g.NJ(a.A).getVideoContentRect();g.si(a.i,b.width,b.height);g.ii(a.i,b.left,b.top);a.K=new g.Ph(d.left+b.left,d.top+b.top,b.width,b.height);var e=(e=r_(a.g))&&d?ZZ(d,e.o,e.g?e.g:"xy"):1;var f=s_(a.g,d);d=a.g.i;d.padding?d=d.padding:(d="speech"==a.g.style?1.6:.8,d=new g.Mh(d,d,d,d));d=new g.Mh(360*d.top*f/100,640*d.right*e/100,360*d.bottom*f/100,640*d.left*e/100);a.u&&(d.right+=1.5*c.g.height/100);a.i.style.padding=d.top+"px "+d.right+"px "+d.bottom+"px "+d.left+
"px";"label"==a.g.style&&a.C&&(a.C.style.padding=a.i.style.padding);d=c.g;var k=!1,l=0,m=0;var n=g.NJ(a.A).getVideoContentRect();var p=g.UJ(a.A);g.Rh(n,p)?n=null:(p.top+=20,p.height-=40,"player_relative"!=a.g.A&&(p.left-=n.left,p.top-=n.top),n=p);n&&(l=n.top-(b.top+b.height),m=b.top-(n.top+n.height),k=0<l||0<m);if(k&&n){d=l;e=m;if(a.u){f=L_(a,23,b,d,e);if(a.o){var u=43-f.width;0<u&&(b.left+f.left-u>n.left&&(f.left-=u),f.width+=u)}u=f;g.si(a.u,f.width,f.height);g.ii(a.u,f.left,f.top)}a.o&&(u?b=new g.$d(u.left+
u.width-23-18,a.Z?u.top+2:u.top+u.height-18-2):(u=L_(a,18,b,d,e),b=new g.$d(u.left,u.top),g.si(a.o,u.width,u.height)),g.ii(a.o,b));a.O=new g.Ph(a.K.left+u.left,a.K.top+u.top,u.width,u.height);a.N=a.aa.ca(g.NJ(a.A),"mousemove",a.FE,a)}else a.u&&(u=e/f*d.height*4.2/100,u=new g.be(u,u),"highlight"==a.g.type||"label"==a.g.style?(e=1.5*d.height/100,u=new g.Ph(b.width-u.width-e,b.height-u.height-e,u.width,u.height)):u=new g.Ph(b.width-u.width-3*d.height/100,(b.height-u.height)/2,u.width,u.height),g.si(a.u,
u.width,u.height),g.ii(a.u,u.left,u.top)),a.o&&(u=9<=d.left+d.width-(b.left+b.width),e=9<=b.top-d.top,g.ii(a.o,u&&e?new g.$d(b.width-9,-9):u?new g.$d(b.width-9,45<b.height?9:b.height-9):e?new g.$d(45<b.width?b.width-9-18:-9,-9):b.width/d.width>b.height/d.height?new g.$d(45<b.width?b.width-9-18:-9,b.height-9):new g.$d(-9,45<b.height?9:b.height-9)))}a.l&&a.l.l(a.g,c);if(a.i){c=a.i;b=a.g.i;c.style.color="highlightText"==a.g.style?b.A:b.i;u=g.NJ(a.A).getVideoContentRect();c.style.fontSize=360*b.textSize*
s_(a.g,u)/100+"px";u=a.g.style;c.style.textAlign=b.textAlign?b.textAlign:"title"==u||"highlightText"==u?"center":"left";b.o&&(c.style.fontWeight=b.o);a=a.i;c=a.style.overflow;u=(b=g.ke("annotation-link-icon",a))?YY(b):!1;e=(d=g.ke("annotation-close-button",a))?YY(d):!1;u&&g.ui(b,!1);e&&g.ui(d,!1);m=f="";if(n=g.ke("inner-text",a))f=n.style.overflow,m=n.style.position,n.style.overflow="visible",n.style.position="static";a.style.overflow="scroll";if(a.scrollHeight>a.offsetHeight||a.scrollWidth>a.offsetWidth){l=
k=lma(a);p=5;for(var x=Math.floor(k/2);x;)a.scrollHeight<=a.offsetHeight&&a.scrollWidth<=a.offsetWidth?(p=l,l=Math.min(l+x,k)):l=Math.max(l-x,p),x=Math.floor(x/2),a.style.fontSize=l+"px";l!=p&&(a.scrollHeight>a.offsetHeight||a.scrollWidth>a.offsetWidth)&&(a.style.fontSize=p+"px")}a.style.overflow=c;n&&(n.style.overflow=f,n.style.position=m);e&&g.ui(d,!0);u&&g.ui(b,!0)}}}},L_=function(a,b,c,d,e){var f=0<e;
b=new g.Ph(0,c.height-b,Math.max(c.width,b),b);0<d&&(b.top=c.height,20<d&&(b.height+=d-20),g.J(a.i,"annotation-extend-down"));f&&(b.top=-b.height,20<e&&(c=e-20,b.top-=c,b.height+=c),g.J(a.i,"annotation-extend-up"),a.Z=!0);return b},N_=function(a){return"label"!=a.g.style||a.l.g},K_=function(a){var b=g.NJ(a.A).getVideoContentRect();
if("player_relative"==a.g.A){var c=g.NJ(a.A).getPlayerSize();b=new g.Ph(-b.left,-b.top,c.width,c.height)}else b=new g.Ph(0,0,b.width,b.height);return new g_(b,a.R?r_(a.R):null)},O_=function(a,b){return b?new g.Ph(a.x+b.left,a.y+b.top,b.width,b.height):null},P_=function(a,b,c){g.F.call(this);
this.i=a;this.annotation=b;this.view=c;this.g=null;this.l=this.isVisible=!1;mna(b,a)},mna=function(a,b){cna(a,function(c){return new u_(a.id,c,b)})},Q_=function(a){a.i.unsubscribe("resize",a.Ow,a);
a.i.unsubscribe("onVideoAreaChange",a.Fy,a)},R_=function(a){a.g&&(a.g.stop(),a.g=null)},S_=function(a,b,c){lZ.call(this,a,b,c);
this.channelId=b.channel_id;this.customMessage=b.custom_message;this.profileImageUrl=b.image_url;this.title=b.title;this.metaInfo=b.meta_info;this.url=XZ({pause_on_navigation:b.pause_on_navigation,target:b.target||"new",value:b.url})},T_=function(a,b,c){lZ.call(this,a,b,c);
this.imageUrl=b.image_url;this.displayDomain=b.display_domain;this.showLinkIcon=b.show_link_icon;this.o=b.button_icon_url;this.title=b.title;this.customMessage=b.custom_message;this.url=XZ({pause_on_navigation:b.pause_on_navigation,target:b.target||"new",value:b.url});this.g=null;if(a=b.signin_url)this.g=XZ({target:"current",value:a});this.N=b.signin_title||null;this.H=b.signin_message||null},U_=function(a,b,c){T_.call(this,a,b,c);
this.F=b.ypc_flow_type;this.C=b.innertube_request_params},V_=function(a,b,c){lZ.call(this,a,b,c);
this.o=b.image_url;this.playlistVideoCount=b.playlist_video_count;this.customMessage=b.custom_message;this.title=b.title;this.metaInfo=b.meta_info;this.url=XZ({pause_on_navigation:b.pause_on_navigation,target:b.target||"new",value:b.url})},W_=function(a,b,c){lZ.call(this,a,b,c);
this.C=this.id.replace(/[^a-z0-9-]/gi,"-");this.title=b.title;this.choices=b.choices;this.g=b.hasOwnProperty("old_vote")?b.old_vote:null;this.o=null;if(a=b.signin_url)this.o=XZ({target:"current",value:a});this.F=b.hasOwnProperty("xsrf_token")?b.xsrf_token:null},X_=function(a,b,c){T_.call(this,a,b,c);
this.offers=[];a=b.offers||[];for(b=0;b<a.length;b++)this.offers.push(new nna(a[b]))},nna=function(a){this.merchant=g.Fc(a.merchant);
this.price=g.Fc(a.price)},Y_=function(a,b,c){T_.call(this,a,b,c);
this.K=b.ypc_item_type;this.F=b.ypc_item_id;this.C=b.ypc_flow_type},Z_=function(a,b,c){lZ.call(this,a,b,c);
this.o=b.image_url;this.videoDuration=b.video_duration||null;this.customMessage=b.custom_message;this.title=b.title;this.metaInfo=b.meta_info;this.isLiveNow=!!b.is_live_now;this.url=XZ({pause_on_navigation:b.pause_on_navigation,target:b.target||"new",value:b.url})},$_=function(a,b,c){lZ.call(this,a,b,c);
this.F=b.image_url;this.o=b.badge_symbol||"";this.priceText=b.price_text||"";this.title=b.title;this.metaInfo=b.meta_info;this.C=!!b.is_paygated;this.H=!!b.user_has_entitlement;this.url=XZ({target:b.target||"new",value:b.url})},ona=function(a){this.g=a;
this.i={}},pna=function(a){var b={};
b=(b["iv-event"]=1,b);g.TJ(a.g,"iv",b,void 0)},d0=function(a,b,c,d){if(b){var e=a0(a,b);
a.i[b]=e["p-time"];e["iv-event"]=e.link||e["l-class"]||e["link-id"]?2:7;b=b0(a,"cta_annotation_shown",e,c);c0(a,e,qna(b,d))}},e0=function(a,b,c,d,e,f){if(b){var k=a0(a,b);
k["iv-event"]=3;k["i-time"]=a.i[b]||"";d&&g.tc(k,d);b=b0(a,"cta_annotation_clicked",k,e);c0(a,k,b,c,f)}},f0=function(a,b){if(b){var c=a0(a,b);
c["iv-event"]=4;c["i-time"]=a.i[b]||"";var d=b0(a,"cta_annotation_closed",c);c0(a,c,d)}},qna=function(a,b){return b?(0,g.D)(a,g.Va(function(a,b){return g.Qn(b,a)},b)):a},b0=function(a,b,c,d){d=d?g.pb(d):[];
var e=c["a-type"];if(30==e||31==e&&g.P(g.V(a.g).experiments,"enable_async_click_tracking")){a:{c=c["a-id"];a=a.g.getVideoData();if(a.Vt){if((b=a.Vt[b])&&g.wv(b)){a=g.yc("[ANNOTATION_ID]");0<=b.indexOf("[ANNOTATION_ID]")?b=b.replace("[ANNOTATION_ID]",c):0<=b.indexOf(a)&&(b=b.replace(a,c));break a}}else if(a.Sm){b=g.Vq(a.Sm,{label:b,value:"a_id="+c});break a}b=""}b&&d.push(b)}return d},c0=function(a,b,c,d,e){var f=1,k=-1;
if(d){var l=!1;var m=function(){f--;f||l||(clearTimeout(k),l=!0,d())};
k=setTimeout(function(){l=!0;d()},1E3)}(0,g.A)(c||[],function(a){f++;
g.Ar(a,m)});
e&&(f++,0!=e&&a.g.sendVideoStatsEngageEvent(e,m));g.TJ(a.g,"iv",b,m)},a0=function(a,b){var c={};
if(b){var d=new g.Fn(b);(0,g.A)(d.Bd(),function(a){c[a]=escape(d.get(a,""))})}c["p-time"]=a.g.getCurrentTime().toFixed(2);
c.ps=g.V(a.g).playerStyle;return c},g0=function(a,b,c,d,e){e=a0(a,e);
e["iv-event"]=c;b&&(e.ei=b);e["a-id"]||(e["a-id"]="card:drawer");e["a-type"]=51;c0(a,e,d)},h0=function(a,b,c,d){c&&(c=a0(a,c),c["iv-event"]=b,c0(a,c,d))},rna=function(a,b,c,d,e,f,k){this.g=a;
this.l=b;this.sb=c;this.videoData=d;this.logger=e;this.fa=f;this.i=k},i0=function(a,b,c){this.g=a;
this.o=b;this.u=c;this.i=new g.zo},sna=function(a,b){var c=[];
(0,g.A)(b.choices,function(a){c.push({B:"li",G:b.C+"-"+a.index.toString(),I:[{B:"label",I:[{B:"input",G:"iv-card-poll-choice-input",L:{type:"checkbox",role:"radio",name:b.C+a.index.toString(),value:a.index.toString(),"data-poll-choice-index":a.index.toString()}},{B:"span",G:"iv-card-poll-choice-text",I:[{B:"span",G:"iv-card-poll-choice-percent"},j0(this,"span",void 0,a.desc)]}]},{B:"div",G:"iv-card-poll-result",I:[{B:"div",G:"iv-card-poll-result-bar"}]}]})},a);
var d={B:"ul",L:{role:"radiogroup"},I:c},e={};b.o&&(e["aria-label"]=g.JN("$POLL_TITLE - Sign in to vote.",{POLL_TITLE:b.title}));var f=["iv-card","iv-card-poll"];d=[{B:"div",G:"iv-card-content",I:[j0(a,"h2",e,b.title),{B:"form",I:[{B:"fieldset",I:[d]}]}]}];b.o&&(f.push("iv-card-unavailable"),d.push({B:"div",V:["iv-card-sign-in"],I:[{B:"h2",U:"Want to vote?"},{B:"a",V:["iv-card-sign-in-button","iv-button"],L:{href:YZ(b.o)},I:[{B:"span",V:["iv-button-content"],U:"Sign in"}]}]}));f=new g.T({B:"div",
V:f,I:d});d=f.element;k0(b,d);qma(a.g.g,d,g.Va(a.C,b),a);(0,g.A)(g.je("iv-card-poll-choice-input",d),function(a){this.g.g.ca(a,"focus",g.Va(this.l,!0));this.g.g.ca(a,"blur",g.Va(this.l,!1))},a);
b.o&&(d=g.ke("iv-card-sign-in-button",d),a.o(d,b.o,b.id,b.Wc,b.l,b.i.click,5));return f},o0=function(a,b,c,d){var e=b.displayDomain?{B:"div",
G:"iv-card-image-text",U:b.displayDomain}:"",f=l0(a,b),k=["iv-card"];b.g&&k.push("iv-card-unavailable");e=[{B:"a",G:"iv-click-target",L:{href:YZ(b.url)},I:[m0(b.imageUrl,e),{B:"div",G:"iv-card-content",I:[j0(a,"h2",void 0,b.title),f]}]}];b.g&&e.push({B:"div",V:["iv-card-sign-in"],I:[j0(a,"h2",void 0,b.N||""),{B:"p",U:b.H},{B:"a",V:["iv-card-sign-in-button","iv-button"],L:{href:YZ(b.g)},I:[j0(a,"span","iv-button-content","Sign in")]}]});k=new g.T({B:"div",V:k,I:e});n0(a,k,b,c,d);return k},q0=function(a,
b,c){var d=["yt-badge",
"standalone-ypc-badge-renderer-icon",b.H?"standalone-ypc-badge-renderer-icon-purchased":"standalone-ypc-badge-renderer-icon-available"],e={};d=b.C&&b.o?{B:"span",V:d,L:e,U:b.o}:"";c={B:"div",V:["iv-card",c],I:[{B:"a",G:"iv-click-target",L:{href:YZ(b.url)},I:[m0(b.F,d?{B:"div",G:"iv-card-image-text",I:[d,b.priceText]}:""),{B:"div",G:"iv-card-content",I:[{B:"h2",G:"iv-card-primary-link",U:b.title},p0(a,b)]}]}]};c=new g.T(c);n0(a,c,b);return c},r0=function(a,b){return b.customMessage?j0(a,"div","iv-card-message",
b.customMessage):""},m0=function(a,b){var c="background-image: url("+a+");",d=[];
b&&d.push(b);return{B:"div",G:"iv-card-image",L:{style:c},I:d}},p0=function(a,b){if(!b.metaInfo||0==b.metaInfo.length)return"";
var c=[];(0,g.A)(b.metaInfo,function(a){c.push(j0(this,"li","",a))},a);
return{B:"ul",G:"iv-card-meta-info",I:c}},j0=function(a,b,c,d){c?g.t(c)?c={"class":c}:g.Ma(c)&&(c={"class":c.join(" ")}):c={};
c.dir=g.Ao(a.i,d);return{B:b,L:c,U:d}},l0=function(a,b){if(!b.customMessage)return"";
var c=["iv-card-action","iv-card-primary-link"],d={};b.o&&(c.push("iv-card-action-icon"),d.style="background-image: url("+b.o+");");d.dir=g.Ao(a.i,b.customMessage);var e=[{B:"span",U:b.customMessage}];b.showLinkIcon&&(e.push("\u00a0"),e.push({B:"span",G:"iv-card-link-icon"}));return{B:"div",V:c,L:d,I:e}},k0=function(a,b){var c=0;
(0,g.A)(a.choices,function(a){c+=a.count});
c=c||1;for(var d=0;d<a.choices.length;d++){var e=a.choices[d],f=g.ke(a.C+"-"+e.index.toString(),b);e=e.count/c;null==a.g&&(e=0);g.K(f.getElementsByTagName("label")[0],"iv-card-poll-choice-checked",a.g==d);f.getElementsByTagName("input")[0].checked=a.g==d;var k=Math.floor(100*e).toFixed(0),l=g.ke("iv-card-poll-choice-percent",f);g.Ie(l,g.JN("$PERCENT%",{PERCENT:k}));f=g.ke("iv-card-poll-result-bar",f);g.ai(f,"transform","scaleX("+e.toFixed(2)+")")}g.K(b,"iv-card-poll-voted",null!=a.g);g.K(b,"iv-card-poll-expanded",
null!=a.g&&1<a.choices.length)},s0=function(a,b,c,d){d?(c&&a.g.videoData.sa||a.g.fa.pauseVideo(),a.g.fa.isFullscreen()&&a.g.fa.toggleFullscreen(),e0(a.g.logger,b.l,d,void 0,b.i.click,5),(a=g.Dt())&&g.mt(a,b.A)):b.url&&a.u(b.url,b.id,b.Wc,b.l,b.i.click||[],5)},n0=function(a,b,c,d,e){c.g&&t0(a,g.je("iv-card-sign-in-button",b.element),c,c.g,e);
c.url&&t0(a,g.je("iv-click-target",b.element),c,c.url,d)},t0=function(a,b,c,d,e){(0,g.A)(b,function(a){if(e){var b=(0,g.y)(function(a){a.stopPropagation();
a.preventDefault();e();return!1},this);
this.g.g.ca(a,"click",b)}else d&&this.o(a,d,c.id,c.Wc,c.l,c.i.click,5)},a)},u0=function(a){var b=0;
-1!=a.indexOf("h")&&(a=a.split("h"),b=3600*a[0],a=a[1]);-1!=a.indexOf("m")&&(a=a.split("m"),b=60*a[0]+b,a=a[1]);-1!=a.indexOf("s")?(a=a.split("s"),b=1*a[0]+b):b=1*a+b;return b},w0=function(a){var b;
(b=a)&&!(b=1<a.length?"/"==a.charAt(0)&&"/"!=a.charAt(1):"/"==a)&&(b=v0(a),b="com"==b[0]&&"youtube"==b[1]||"be"==b[0]&&"youtu"==b[1]);return b?-1==a.indexOf("/redirect?"):!1},v0=function(a){a=a.replace(/^(https?:)?\/\//,"");
a=a.split("/",1);return!a||1>a.length||!a[0]?[]:a[0].toLowerCase().split(".").reverse()},tna=function(a){a=YZ(a);
if(!a)return null;a=a.replace(/https?:\/\//g,"");var b;(b=!w0(a))||(b=g.sh(g.rh(a)[5]||null)||"",b=b.split("/"),b="/"+(1<b.length?b[1]:""),b="/watch"!=b);if(b)return null;b=g.Tq(a);if(!b||!b.v)return null;if(b=b.t)return u0(b);a=a.split("#",2);return!a||2>a.length?null:(a=g.Rq(a[1]))&&a.t?u0(a.t):-1},x0=function(a){a=YZ(a);
a=a.replace(/https?:\/\//g,"");return w0(a)?(a=g.Tq(a))&&a.v?a.v:null:null},una=function(a,b,c){c=c.replace(/\/(u|b)\/[0-9]+/g,"");
var d=/^[0-9]+$/;a&&d.test(a)&&(c="/b/"+a+c);b&&d.test(b)&&(c="/u/"+b+c);return c},y0=function(a,b){return b?b:w0(a)?"current":"new"},z0=function(a,b){g.F.call(this);
this.Aa=a;this.context=b;this.Ls=!1;this.ha=0},vna=function(a){return(0,g.B)()-a.ha},wna=function(a,b,c,d,e,f){var k=YZ(b);
if(k){var l=y0(k,b.target),m=(0,g.y)(function(){b.g&&this.context.fa.pauseVideo();var a=this.context.videoData.ac||!1,d=g.Tq(k||"");a&&d&&(d.v||d.list)?g.vX(this.context.fa.app,d.v,c,d.list,!1,void 0,void 0):g.cM(k||"","current"==l?"_top":void 0,c)},a);
"new"==l&&(m(),m=null);var n={};n.interval=vna(a);e0(a.context.logger,d,m,n,e,f);w0(k)||(a=g.Dt(),d=c.itct,a&&d&&g.mt(a,g.it(d)))}},C0=function(a,b,c){z0.call(this,b,c);
var d=this;this.i=a;this.P=null;this.Z=this.xa=this.u=this.ua=!1;this.Y=null;this.O=new g.L(g.Ja,c.sb.Hc?4E3:3E3);g.G(this,this.O);this.ma=new g.L(g.Ja);g.G(this,this.ma);this.A=new i0(c,(0,g.y)(this.ni,this),(0,g.y)(this.Wl,this));this.F=new g.T({B:"div",G:"iv-drawer",L:{id:"iv-drawer"},I:[{B:"div",G:"iv-drawer-header",L:{"aria-role":"heading"},I:[{B:"span",G:"iv-drawer-header-text"},{B:"button",V:["iv-drawer-close-button","ytp-button"],L:{"aria-label":"Hide cards",tabindex:"0"}}]},{B:"div",G:"iv-drawer-content"}]});
g.G(this,this.F);this.C=this.F.element;this.ea=new g.BP(this.F,330);g.G(this,this.ea);this.ya=g.ke("iv-drawer-header-text",this.C);this.o=g.ke("iv-drawer-content",this.C);this.l=[];this.oa=this.R=this.D=this.W=this.g=null;this.N=[];this.addCueRange(0,1E3*c.videoData.lengthSeconds,"",function(){d.xa&&A0(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.xa=d.u)&&B0(d)});
this.K=this.H=this.ba=null},Ana=function(a,b){var c=b&&b.data&&b.data.card_type;
if(c&&D0[c]){c=new D0[c](b.id,b.data,b.g);if(!a.ua){g.Fo(a.ia(),["html5-stop-propagation","iv-drawer-manager"]);g.cK(a.i,a.C,5);xna(a);a.R=g.ke("ytp-cards-button",a.i.getRootNode());var d=g.ke("iv-drawer-close-button",a.C);a.oa=d;a.ua=!0}E0(a,c.id);var e=yna(a,c);if(e){d={Db:c,Ko:e.element,ow:!1};var f=zna(a,d);g.sb(a.l,f,0,d);e.X(a.o,f);a.Vk();c.autoOpen?a.addCueRange(c.startMs,0x8000000000000,c.id,g.Va(a.nL,d)):(e=1E3*a.context.fa.getCurrentTime(),5E3>e&&e>c.startMs&&a.zz(d),a.addCueRange(c.startMs,
c.startMs+1,c.id,g.Va(a.zz,d)),F0(a))}}},Bna=function(a,b){b.data.autoOpenMs&&a.addCueRange(b.data.autoOpenMs,0x8000000000000,"",function(){A0(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
b.data.autoCloseMs&&a.addCueRange(b.data.autoCloseMs,0x8000000000000,"",function(){B0(a)});
var c=b.data.headerText;g.Ie(a.ya,c);a.R&&a.R.setAttribute("title",c);b.data.eventId&&(a.P=b.data.eventId);a.ba=g.it(b.data.trackingParams);a.K=g.it(b.data.closeTrackingParams);a.H=g.it(b.data.iconTrackingParams)},E0=function(a,b){var c=Cna(a,b);
c&&(c==a.g&&(a.g=null),a.i.removeCueRange(c.Db.id),g.De(c.Ko),g.kb(a.l,c),a.Vk(),F0(a))},A0=function(a,b,c,d){if(!a.u){a.ea.show();
a.W=new g.L(function(){g.J(a.context.fa.getRootNode(),"ytp-iv-drawer-open")},0);
a.W.start();a.Y=g.ds(a.o,"mousewheel",(0,g.y)(a.hE,a));a.u=!0;a.ha=(0,g.B)();g0(a.context.logger,a.P,7,void 0,d&&d.Db?d.Db.l:void 0);var e=g.Dt();e&&a.ba&&a.K&&jZ(e,[a.ba,a.K]);var f={TRIGGER_TYPE:b};(0,g.A)(a.l,function(b){b.ow||(b.ow=!0,d0(a.context.logger,b.Db.l,b.Db.i.VC,f));e&&jZ(e,[b.Db.A])});
VY(a.i);c&&(a.D=new g.L(function(){a.la=a.R;a.oa.focus()},330),a.D.start())}},B0=function(a){a.u&&(a.ea.hide(),g.es(a.Y),a.Y=null,g.Go(a.context.fa.getRootNode(),"ytp-iv-drawer-open"),a.u=!1,VY(a.i),a.D&&a.D.stop(),a.D=new g.L(function(){a.la&&(a.la.focus(),a.la=null)},330),a.D.start())},xna=function(a){var b=g.ke("iv-drawer-close-button",a.C);
a.context.g.ca(b,"click",a.EB,a);a.context.g.ca(a.o,"touchend",function(){a.O.start()});
a.context.g.ca(a.o,"scroll",a.MB,a);a.context.i.subscribe("onHideControls",function(){a.Z=!0});
a.context.i.subscribe("onShowControls",function(){a.Z=!1});
a.context.i.subscribe("onVideoAreaChange",function(){a.Z=g.Eo(a.i.getRootNode(),"ytp-autohide")});
a.N.push(g.xq("iv-button-shown",a.pD,a));a.N.push(g.xq("iv-button-hidden",a.oD,a));a.N.push(g.xq("iv-teaser-shown",a.sD,a));a.N.push(g.xq("iv-teaser-hidden",a.rD,a));a.N.push(g.xq("iv-teaser-clicked",a.qD,a))},yna=function(a,b){switch(b.type){case "simple":return o0(a.A,b);
case "collaborator":var c=a.A,d={B:"div",V:["iv-card","iv-card-channel"],I:[{B:"a",V:["iv-click-target"],L:{href:YZ(b.url),"data-ytid":b.channelId},I:[m0(b.profileImageUrl),{B:"div",G:"iv-card-content",I:[r0(c,b),{B:"h2",G:"iv-card-primary-link",U:b.title},p0(c,b)]}]}]};d=new g.T(d);n0(c,d,b);return d;case "donation":return c=a.A,d=(0,g.y)(c.A,c,b),o0(c,b,d,d);case "episode":return q0(a.A,b,"iv-card-episode");case "movie":return q0(a.A,b,"iv-card-movie");case "playlist":return c=a.A,d={B:"div",V:["iv-card",
"iv-card-playlist"],I:[{B:"a",G:"iv-click-target",L:{href:YZ(b.url)},I:[m0(b.o,{B:"div",G:"iv-card-image-overlay",I:[{B:"span",G:"iv-card-playlist-video-count",U:b.playlistVideoCount.toString()}]}),{B:"div",G:"iv-card-content",I:[r0(c,b),j0(c,"h2","iv-card-primary-link",b.title),p0(c,b)]}]}]},d=new g.T(d),n0(c,d,b),d;case "poll":return sna(a.A,b);case "productListing":c=a.A;var e=0!=b.offers.length;d=["iv-card"];var f="",k=l0(c,b);e&&(d.push("iv-card-product-listing"),f="iv-card-primary-link",e=b.offers[0],
k=[],e.price&&k.push({B:"div",G:"iv-card-offer-price",U:e.price}),e.merchant&&k.push({B:"div",G:"iv-card-offer-merchant",U:e.merchant}),k={B:"div",I:k});d={B:"div",V:d,L:{tabindex:"0"},I:[{B:"a",V:["iv-card-image","iv-click-target"],L:{style:"background-image: url("+b.imageUrl+");",href:YZ(b.url),"aria-hidden":"true",tabindex:"-1"}},{B:"div",G:"iv-card-content",I:[b.sponsored?{B:"div",G:"iv-card-sponsored",I:["Sponsored",{B:"div",G:"iv-ad-info-container",I:[{B:"div",G:"iv-ad-info",U:"{{adInfo}}"},
{B:"div",G:"iv-ad-info-icon-container",I:[{B:"div",G:"iv-ad-info-icon"},{B:"div",G:"iv-ad-info-callout"}]}]}]}:"",{B:"a",G:"iv-click-target",L:{href:YZ(b.url)},I:[j0(c,"h2",f,b.title),k]}]}]};d=new g.T(d);f=g.ye("span");g.Ie(f,"You are seeing this product because we think it is relevant to the video. Google may be compensated by the merchant.");d.kb(f,"adInfo");n0(c,d,b);return d;case "tip":return c=a.A,d=(0,g.y)(c.D,c,b),o0(c,b,d,d);case "video":return c=a.A,d=b.isLiveNow?{B:"span",V:["yt-badge",
"yt-badge-live"],U:"LIVE NOW"}:"",d={B:"div",V:["iv-card","iv-card-video"],I:[{B:"a",G:"iv-click-target",L:{href:YZ(b.url)},I:[m0(b.o,b.videoDuration?{B:"span",G:"iv-card-video-duration",U:b.videoDuration}:""),{B:"div",G:"iv-card-content",I:[r0(c,b),j0(c,"h2","iv-card-primary-link",b.title),p0(c,b),d]}]}]},d=new g.T(d),n0(c,d,b),d}return null},zna=function(a,b){if(0==a.l.length)return 0;
var c=g.db(a.l,function(a){return b.Db.startMs>a.Db.startMs||b.Db.startMs==a.Db.startMs&&b.Db.timestamp>=a.Db.timestamp?!0:!1});
return-1==c?0:c+1},Dna=function(a){return a.g?"productListing"==a.g.Db.type:(0,g.qj)(a.l,function(a){return"productListing"==a.Db.type})},F0=function(a){g.K(a.i.getRootNode(),"ytp-cards-shopping-active",Dna(a))},G0=function(a,b){if(a.F.Ga()){var c=new eZ([0,
a.o.scrollTop],[0,b.Ko.offsetTop],600,pma);a.context.l.ca(c,"animate",function(b){a.o.scrollTop=b.y});
a.context.l.ca(c,"finish",function(b){a.o.scrollTop=b.y});
c.play()}else g.lC(a.F,!0),a.o.scrollTop=b.Ko.offsetTop,g.lC(a.F,!1)},H0=function(a){return a.g&&a.g.Db?a.g.Db:a.l[0]&&a.l[0].Db?a.l[0].Db:null},Cna=function(a,b){return g.cb(a.l,function(a){return a.Db.id==b})},I0=function(a,b,c){z0.call(this,a,b);
this.annotation=c;this.isActive=!1},Ena=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&a.addCueRange(a.annotation.data.start_ms,a.annotation.data.end_ms,a.annotation.id,function(){a.show()},function(){a.hide()})},J0=function(a,b,c){I0.call(this,a,b,c);
this.i=null;this.D=!1;this.l=null;this.o=!1;this.u=0;this.g=this.C=this.A=null},K0=function(a,b,c){I0.call(this,a,b,c);
this.F=this.u=this.H=!1;this.C=5E3;this.o=null;this.D=g.we("DIV","iv-promo-contents");this.i=this.l=this.g=null;this.A=new g.L(function(){this.g.setAttribute("aria-hidden",!0);g.ui(this.l,!1);g.ui(this.i,!0)},700,this);
g.G(this,this.A)},Fna=function(a){var b=a.annotation.data;
if("cta"==a.annotation.style)var c=6;else if("video"==a.annotation.style||"playlist"==a.annotation.style)c=7;a.C=b.collapse_delay_ms||a.C;var d=["iv-promo","iv-promo-inactive"];a.ia().setAttribute("aria-hidden",!0);a.ia().setAttribute("aria-label","Promotion");a.ia().tabIndex=0;var e=a.annotation.Kb(),f=b.image_url;if(f){var k=g.we("DIV",["iv-promo-img","iv-click-target"]);f=g.we("IMG",{src:f,"aria-hidden":"true"});k.appendChild(f);b.video_duration&&!b.is_live?(f=g.we("SPAN","iv-promo-video-duration",
b.video_duration),k.appendChild(f)):b.playlist_length&&(f=g.we("SPAN","iv-promo-playlist-length",b.playlist_length.toString()),k.appendChild(f));e&&a.ni(k,e,a.annotation.id,b.session_data,a.annotation.g,void 0,c)}e?(f=g.we("A","iv-promo-txt"),g.Pd(f,YZ(e)),a.g=f):a.g=g.we("DIV","iv-promo-txt");switch(a.annotation.style){case "cta":case "website":var l=g.we("P",null,g.we("STRONG",null,b.text_line_1));var m=g.we("P",null,g.we("SPAN","iv-promo-link",b.text_line_2));if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");
g.P(a.context.sb.experiments,"web_action_cta_larger_ui")&&d.push("iv-promo-website-card-cta-larger-ui");var n=g.we("BUTTON",["iv-promo-round-expand-icon","ytp-button"]);f=g.we("BUTTON",["iv-button","iv-promo-button"],g.we("SPAN","iv-button-content",f));var p=g.we("DIV","iv-promo-button-container");p.appendChild(f);e&&a.ni(a.ia(),e,a.annotation.id,b.session_data,a.annotation.g,void 0,c)}g.J(a.g,"iv-click-target");e&&a.ni(a.g,e,a.annotation.id,b.session_data,a.annotation.g,void 0,c);break;case "playlist":case "video":l=
g.we("P",null,g.we("SPAN",null,b.text_line_1)),m=g.we("P",null,g.we("STRONG",null,b.text_line_2)),b.is_live&&(l=m,m=g.we("SPAN",["yt-badge","iv-promo-badge-live"],"LIVE NOW")),g.J(a.g,"iv-click-target"),e&&a.ni(a.g,e,a.annotation.id,b.session_data,a.annotation.g,void 0,c),d.push("iv-promo-video")}l&&a.g.appendChild(l);m&&a.g.appendChild(m);a.D.appendChild(a.g);p&&a.D.appendChild(p);c=g.we("DIV","iv-promo-actions");a.i=g.we("BUTTON",["iv-promo-expand","ytp-button"]);a.i.title="Expand";a.context.g.ca(a.i,
"click",g.Va(a.Gp,5E3),a);c.appendChild(a.i);g.ui(a.i,!1);a.context.g.ca(a.ia(),"mouseover",a.vC,a);a.context.g.ca(a.ia(),"mouseout",a.uC,a);a.context.g.ca(a.ia(),"touchend",g.Va(a.Gp,5E3),a);a.l=g.we("BUTTON",["iv-promo-close","ytp-button"]);a.l.title="Close";a.context.g.ca(a.l,"click","cta"==a.annotation.style&&b.text_line_3?a.nC:a.mC,a);c.appendChild(a.l);g.Fo(a.ia(),d);k&&(a.ia().appendChild(k),n&&k.appendChild(n));a.ia().appendChild(a.D);a.ia().appendChild(c)},L0=function(a){a.u||a.F||a.o||(g.J(a.ia(),
"iv-promo-collapsed"),a.u=!0,a.A.start())},M0=function(a){a.A.stop();
a.u&&(g.Ho(a.ia(),["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.u=!1,a.g&&a.g.removeAttribute("aria-hidden"),g.ui(a.i,!1),g.ui(a.l,!0))},O0=function(a,b){a.o||(a.o=g.gh(function(){N0(this);
L0(this)},b,a))},N0=function(a){a.o&&(g.v.clearTimeout(a.o),a.o=null)},P0=function(a){g.pK.call(this,a);
this.N=!1;this.H=0;this.i={};this.K={};this.D=new ona(a);this.A=new g.rs(this);g.G(this,this.A);this.C=this.l=null;this.A.J(this.player,"onVideoAreaChange",(0,g.y)(this.M,this,"onVideoAreaChange"));this.A.J(this.player,"onHideControls",(0,g.y)(this.M,this,"onHideControls"));this.A.J(this.player,"onShowControls",(0,g.y)(this.M,this,"onShowControls"));this.A.J(this.player,"resize",(0,g.y)(this.M,this,"resize"));this.A.J(this.player,"presentingplayerstatechange",(0,g.y)(this.M,this,"presentingplayerstatechange"));
this.subscribe("onHideControls",this.TH,this);this.subscribe("onShowControls",this.UJ,this);this.subscribe("presentingplayerstatechange",this.cJ,this);this.subscribe("resize",this.Br,this);this.subscribe("G",this.PD,this);this.subscribe("F",this.kg,this);this.subscribe("D",this.PG,this);this.subscribe("E",this.sH,this);g.V(this.player).K.subscribe("vast_info_card_add",this.Ey,this);this.P=new g.rs(this);g.G(this,this.P);this.P.J(this.player,g.TD("annotations_module"),this.ND);this.P.J(this.player,
"crx_annotations_module",this.OD);this.R=g.we("DIV",["video-legacy-annotations","html5-stop-propagation"]);this.Z=g.we("DIV","video-custom-annotations");this.u=new g.T({B:"div",V:["ytp-player-content","ytp-iv-player-content"]});g.G(this,this.u);g.cK(this.player,this.u.element,4);this.u.hide();this.o=new g.T({B:"div",V:["ytp-iv-video-content"]});g.G(this,this.o);g.Ae(this.o.element,g.we("DIV","video-annotations",this.R,this.Z));this.F=this.g=null;this.O=[];Gna(this)&&this.load();var b=g.ye("STYLE");
(document.getElementsByTagName("HEAD")[0]||document.body).appendChild(b);g.Sf(this,function(){g.De(b)});
if(a=b.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},Q0=function(a){switch(a){case "annotation-editor":case "live-dashboard":return!0}return!1},Gna=function(a){var b=g.V(a.player);
a=a.player.getVideoData();return 1==(b.Hf||a.Hf)&&!a.vA||null!==b.K.get(a.videoId)},R0=function(a,b,c){a.N=!0;
a.C=g.er(b,c)},S0=function(a,b){for(var c={},d=0;d<b.attributes.length;d++){var e=b.attributes[d];
c[e.name]=e.nodeValue}for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],e.tagName){if(c[e.tagName])var f=c[e.tagName];else if("data"==e.tagName){0<e.childNodes.length&&(f=e.childNodes[0].nodeValue,c[e.tagName]="string"==typeof f?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&"TEXT"==e.tagName?1==e.childNodes.length&&3==e.childNodes[0].nodeType?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push(S0(a,e))}return c},T0=function(a,b,c){return!(a.loaded&&a.H==b&&a.player.getVideoData().videoId==
c)},Ina=function(a,b){var c=Hna(a,b);
if(!c&&"marker"!=b.type)return null;p_(b,function(a){a=(0,g.y)(this.pK,this,b.id,a);this.subscribe("ivTrigger:"+b.id,a)},a);
var d=new P_(a.ea,b,c);g.G(d,c);return d},Jna=function(a,b){var c=g.we("DIV",["annotation",
"annotation-type-custom"]);g.ui(c,!1);var d=null;switch(b.type){case "branding":if(g.V(a.player).Gc)break;a.u.element.appendChild(c);d=new J0(c,U0(a),b);break;case "promotion":g.cK(a.player,c,4),d=new K0(c,U0(a),b)}d&&d.qn();return d},Kna=function(a){var b=a.player.getVideoData();
if(b.zd){var c=g.V(a.player),d=c.K.get(b.videoId);if(d){var e={format:"XML",Bc:{},method:"POST",withCredentials:!0};"gaming"==c.playerStyle&&(e.Bc.gaming="1");e.Vc=(0,g.y)(function(a,b,c){T0(this,a,b)||(a=g.Oq(c)&&c.responseXML?c.responseXML:null)&&V0(this,a)},a,a.H,b.videoId);
g.Ts()&&(e.Vc=W0(a,e.Vc));e.tb={ic_only:"1"};X0(e,d);a.N=!0;g.er(b.zd,e)}}},X0=function(a,b){a.method="POST";
a.tb=a.tb||{};b.al&&(a.tb.ic_coll=b.al);b.bl&&(a.tb.ic_xml=b.bl);b.zs&&(a.tb.ic_track=b.zs)},Lna=function(a){var b=new g.T({B:"div"});
g.ui(b.element,!1);var c=new C0(a.player,b.element,U0(a));g.G(c,b);b.X(a.u.element);c.qn();return c},U0=function(a){if(!a.F){var b=new iZ(a);
g.G(a,b);var c=new g.Nn(a);g.G(a,c);a.F=new rna(b,c,g.V(a.player),a.player.getVideoData(),a.D,a.player,a.ea)}return a.F},V0=function(a,b){var c=!1;
Mna(b);for(var d=b.getElementsByTagName("annotation"),e=0;e<d.length;e++){var f=S0(a,d[e]),k=null;try{k=$ma(f)}catch(l){}if(k){a:{switch(k.type){case "branding":case "promotion":f=!0;break a}f=!1}if(f){if(f=Jna(a,k))g.G(a,f),a.K[k.id]=f}else if("card"==k.type||"drawer"==k.type)a.g||(a.g=Lna(a),g.G(a,a.g)),"card"==k.type?Ana(a.g,k):Bna(a.g,k),c=!0;else if(f=Ina(a,k))g.G(a,f),a.i[k.id]=f}}c&&(VY(a.player),a.Br());g.Zb(a.i,function(a){if(a.view){var b=a.annotation;(a=a.view)&&b.segment&&b.segment.i&&
(b=this.i[b.segment.i])&&(a.R=b.annotation)}},a)},Mna=function(a){if((a=a.getElementsByTagName("annotations"))&&!(1>a.length)&&(a=a[0].getAttribute("itct"))){var b=g.Dt();
if(b){var c=g.Ct();c&&g.kt(b,c,[g.it(a)])}}},Nna=function(a,b,c,d){d?Y0(a,b,c):Z0(a,b,c)},Z0=function(a,b,c){if(b=a.i[b])R_(b),c&&c.i?(a=(0,g.y)(a.Rv,a,b),b.g=new g.L(a,2E3),b.g.start()):a.Rv(b)},Y0=function(a,b,c){if(b=a.i[b])R_(b),c&&c.o?(a=(0,g.y)(a.Iz,a,b),b.g=new g.L(a,2E3),b.g.start()):a.Iz(b)},$0=function(a,b){var c=a.player.getVideoData();
if(!c.Qk)return!1;var d=YZ(b);if(!d)return!1;d=d.replace(/https?:\/\//g,"");if(!w0(d))return!1;d=g.Tq(d);return d.list||d.p?!1:(d=x0(b))?c.videoId==d?!0:"new"!=b.target&&g.V(a.player).i?!0:!1:!1},Hna=function(a,b){if(Ona(b)){var c=b.u||n_(b,function(a){return"click"==a||"rollOut"==a||"rollOut"==a});
return new I_(b,(0,g.y)(a.R.appendChild,a.R),a.player,a.ea,c)}return null},Ona=function(a){if("highlight"==a.type||"widget"==a.type)return!0;
if("text"==a.type)for(var b in m_)if(a.style==m_[b])return!0;return!1},a1=function(a,b,c,d){a.M(t_(b,d),c,d)},W0=function(a,b){return(0,g.y)(function(){if(!this.da()){var a=Array.prototype.slice.call(arguments,0);
a.unshift(b);b=g.Va.apply(window,a);this.O.push(g.Rs(b))}},a)};
g.HJ.prototype.mi=g.ca(14,function(a,b){var c=g.IJ(this).l;c&&c.mi(a,b)});
g.Uo.prototype.Dp=g.ca(0,function(){this.i=this.O.createElement("DIV")});
var hma=/[^\d]+$/,jma={cm:1,"in":1,mm:1,pc:1,pt:1},kma={em:1,ex:1},ZY={},$Y=null;g.z(dZ,g.Vf);g.z(eZ,g.Jo);g.h=eZ.prototype;g.h.getDuration=function(){return this.duration};
g.h.play=function(a){if(a||0==this.g)this.progress=0,this.coords=this.i;else if(1==this.g)return!1;aZ(this);this.startTime=a=(0,g.B)();-1==this.g&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.A=this.startTime;this.progress||this.o();this.Od("play");-1==this.g&&this.Od("resume");this.g=1;var b=g.Sa(this);b in ZY||(ZY[b]=this);bZ();cZ(this,a);return!0};
g.h.stop=function(a){aZ(this);this.g=0;a&&(this.progress=1);fZ(this,this.progress);this.Od("stop");this.l()};
g.h.pause=function(){1==this.g&&(aZ(this),this.g=-1,this.Od("pause"))};
g.h.T=function(){0==this.g||this.stop(!1);this.Od("destroy");eZ.Ha.T.call(this)};
g.h.destroy=function(){this.dispose()};
g.h.tr=function(){this.Od("animate")};
g.h.Od=function(a){this.dispatchEvent(new dZ(a,this))};
g.z(gZ,eZ);gZ.prototype.u=g.Ja;gZ.prototype.tr=function(){this.u();gZ.Ha.tr.call(this)};
gZ.prototype.l=function(){this.u();gZ.Ha.l.call(this)};
gZ.prototype.o=function(){this.u();gZ.Ha.o.call(this)};
g.z(hZ,gZ);hZ.prototype.u=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};
g.r(iZ,g.F);iZ.prototype.ca=function(a,b,c,d){c=(0,g.y)(c,d||this.i);a=g.ds(a,b,c);this.g.push(a);return a};
iZ.prototype.Xl=function(a,b,c,d){c=(0,g.y)(c,d||this.i);a=g.os(a,b,c);this.g.push(a);return a};
iZ.prototype.Na=function(a){g.es(a);g.kb(this.g,a)};
iZ.prototype.T=function(){g.es(this.g);this.g.length=0;g.F.prototype.T.call(this)};g.z(mZ,g.tg);g.h=mZ.prototype;g.h.yp=null;g.h.xj=null;g.h.ia=function(){return this.xj};
g.h.addEventListener=function(a,b,c,d){g.fg(this.xj,a,b,c,d)};
g.h.removeEventListener=function(a,b,c,d){g.ng(this.xj,a,b,c,d)};
g.h.T=function(){mZ.Ha.T.call(this);var a=this.xj;if(a)if(g.Zf(a))a.fe&&g.cg(a.fe);else if(a=g.ig(a)){var b=0,c;for(c in a.listeners)for(var d=a.listeners[c].concat(),e=0;e<d.length;++e)g.og(d[e])&&++b}};g.z(rZ,mZ);rZ.prototype.fill=null;g.z(tZ,mZ);uZ.prototype.ze=null;uZ.prototype.sd=null;uZ.prototype.uk=!0;var sma=[2,2,6,6,0];g.h=uZ.prototype;g.h.clear=function(){this.Va.length=0;this.Ba.length=0;this.Kd.length=0;delete this.ze;delete this.sd;delete this.uk;return this};
g.h.moveTo=function(a,b){0==g.Za(this.Va)?this.Kd.length-=2:(this.Va.push(0),this.Ba.push(1));this.Kd.push(a,b);this.sd=this.ze=[a,b];return this};
g.h.Zb=function(a){var b=g.Za(this.Va);if(null==b)throw Error("Path cannot start with lineTo");1!=b&&(this.Va.push(1),this.Ba.push(0));for(b=0;b<arguments.length;b+=2){var c=arguments[b],d=arguments[b+1];this.Kd.push(c,d)}this.Ba[this.Ba.length-1]+=b/2;this.sd=[c,d]};
g.h.close=function(){var a=g.Za(this.Va);if(null==a)throw Error("Path cannot start with close");4!=a&&(this.Va.push(4),this.Ba.push(1),this.sd=this.ze);return this};
g.h.clone=function(){var a=new this.constructor;a.Va=this.Va.concat();a.Ba=this.Ba.concat();a.Kd=this.Kd.concat();a.ze=this.ze&&this.ze.concat();a.sd=this.sd&&this.sd.concat();a.uk=this.uk;return a};
g.h.transform=function(a){if(!this.uk)throw Error("Non-simple path");a.transform(this.Kd,0,this.Kd,0,this.Kd.length/2);this.ze&&a.transform(this.ze,0,this.ze,0,1);this.sd&&this.ze!=this.sd&&a.transform(this.sd,0,this.sd,0,1);return this};
g.h.isEmpty=function(){return 0==this.Va.length};g.z(wZ,rZ);g.z(yZ,g.Uo);yZ.prototype.o=null;yZ.prototype.nj=function(){return this.Jg?g.ti(this.ia()):g.Ha(this.width)&&g.Ha(this.height)?new g.be(this.width,this.height):null};
yZ.prototype.resume=function(){};g.z(oZ,sZ);g.z(nZ,sZ);g.z(zZ,tZ);zZ.prototype.clear=function(){g.Be(this.ia())};
zZ.prototype.setSize=function(a,b){var c=this.ia(),d={width:a,height:b},e;for(e in d)c.setAttribute(e,d[e])};
g.z(AZ,wZ);var DZ;g.z(BZ,yZ);var vma=0;g.h=BZ.prototype;g.h.Dp=function(){var a=pZ(this,"svg",{width:this.width,height:this.height,overflow:"hidden"}),b=pZ(this,"g");this.C=pZ(this,"defs");this.o=new zZ(b,this);a.appendChild(this.C);a.appendChild(b);this.i=a;this.l&&(this.ia().setAttribute("preserveAspectRatio","none"),this.R?this.kA():this.ia().setAttribute("viewBox","0 0 "+(this.l?this.l+" "+this.N:"")))};
g.h.kA=function(){if(this.Jg){var a=this.nj();0==a.width?this.ia().style.visibility="hidden":(this.ia().style.visibility="",this.o.ia().setAttribute("transform","scale("+a.width/this.l+" "+a.height/this.N+") translate(0 0)"))}};
g.h.setSize=function(a,b){g.si(this.ia(),a,b)};
g.h.nj=function(){if(!g.ci)return this.Jg?g.ti(this.ia()):BZ.Ha.nj.call(this);var a=this.width,b=this.height,c=g.t(a)&&-1!=a.indexOf("%"),d=g.t(b)&&-1!=b.indexOf("%");if(!this.Jg&&(c||d))return null;if(c){var e=this.ia().parentNode;var f=g.ti(e);a=parseFloat(a)*f.width/100}d&&(e=e||this.ia().parentNode,f=f||g.ti(e),b=parseFloat(b)*f.height/100);return new g.be(a,b)};
g.h.clear=function(){this.o.clear();g.Be(this.C);this.g={}};
g.h.dj=function(){BZ.Ha.dj.call(this);this.R&&this.K.Na(wma(),"tick",this.kA)};
g.h.T=function(){delete this.g;delete this.C;delete this.o;this.K.dispose();delete this.K;BZ.Ha.T.call(this)};g.r(FZ,g.pK);g.h=FZ.prototype;
g.h.load=function(){g.pK.prototype.load.call(this);if(!HZ(g.V(this.player).playerStyle)){var a=g.TB(this.player.getVideoData());if(a)a=EZ(a,GZ(this)),IZ(this,a);else{var b=this.player.getVideoData();a=b.videoId;this.o&&this.o.abort();a={method:"POST",Vc:(0,g.y)(this.KH,this,a),Bc:{v:a},withCredentials:!0};"gaming"==g.V(this.player).playerStyle&&(a.Bc.gaming="1");this.K&&(a.Bc.ptype="embedded");var c=this.player.getVideoData().Ou;c&&(a.tb={ad_tracking:c});if(b=g.SB(b))if(b=g.ud(b),b=g.rd(b))this.o=
g.er(b,a)}}};
g.h.unload=function(){IZ(this,null);this.o&&(this.o.abort(),this.o=null);g.pK.prototype.unload.call(this)};
g.h.Yb=function(a,b){if(!HZ(g.V(this.player).playerStyle))return null;if("loadCustomEndscreenRenderer"==a){var c=EZ(b,"new");IZ(this,c);return!0}return null};
g.h.getOptions=function(){return HZ(g.V(this.player).playerStyle)?["loadCustomEndscreenRenderer"]:[]};
g.h.KH=function(a,b){var c=this.o=null;if(200==b.status){var d=b.responseText;")]}"==d.substring(0,3)&&(d=d.substring(3),c=JSON.parse(d),c=EZ(c,GZ(this)))}IZ(this,c)};
g.h.rb=function(){if(this.i&&this.i.elements){var a=this.player.getVideoContentRect();if(a&&0!=a.width&&0!=a.height){var b=this.player.getPlayerSize();if(b&&0!=b.width&&0!=b.height){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<b1.length;f++){var k=Math.abs(b.width-b1[f]);if(-1==e||d>=k)e=f,d=k}d=c1[e];this.l&&g.ai(this.l.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.i.elements.length;++b)if(f=this.i.elements[b].id,e=this.g[f],k=this.C[f],e&&k){var l=k.width*c/k.aspectRatio;
f=Math.round(l*a.height);var m=a.left+Math.round(k.left*a.width),n=a.top+Math.round(k.top*a.height);g.si(e.element,Math.round(k.width*a.width),f);g.ii(e.element,m,n);g.Ho(e.element,Pna);m=k.left+k.width/2;k=k.top+l/2;g.J(e.element,.5>=m&&.5>=k?"ytp-ce-top-left-quad":.5<m&&.5>=k?"ytp-ce-top-right-quad":.5>=m&&.5<k?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.Ho(e.element,c1);g.J(e.element,d);(e=g.ie(document,"div","ytp-ce-expanding-overlay-body",e.element)[0])&&g.ai(e,"height",f+"px")}}}}};
g.h.RD=function(a){if(this.i)if("ytp-ce-in-endscreen"==a.getId())this.H=!1,this.i.skip&&1==this.player.getPlayerState()?(g.QJ(this.player,!0),this.player.seekTo(Infinity),this.H=!0):(MZ(this,this.i.impressionUrls),(a=g.Dt())&&g.lt(a,this.i.visualElement));else if(!this.H){a=a.getId().substring(15);var b=this.g[a],c=this.C[a];g.J(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");b=this.player.getRootNode();g.J(b,"ytp-ce-shown");MZ(this,c.impressionUrls);(b=g.Dt())&&g.lt(b,c.visualElement);
g.V(this.player).ub&&this.player.na("endscreenelementshown",a)}};
g.h.SD=function(a){if("ytp-ce-in-endscreen"!=a.getId()&&!this.H){a=a.getId().substring(15);var b=this.g[a];g.Go(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden",!0);b=this.player.getRootNode();g.Go(b,"ytp-ce-shown");g.V(this.player).ub&&this.player.na("endscreenelementhidden",a)}};
g.h.EK=function(a){var b=this;a.target===window&&(new g.L(function(){for(var a in b.g)g.Ho(b.g[a].element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
g.h.by=function(a,b){if(a.targetUrl&&(!b||"keypress"!=b.type||13==b.keyCode)){for(var c=b.target;c&&!g.Eo(c,"ytp-ce-element");){g.Eo(c,"subscribe-label")&&NZ(this,a);if(g.Eo(c,"ytp-ce-channel-subscribe"))return;c=g.Ge(c)}if(!c||g.Eo(c,"ytp-ce-element-hover")){b.preventDefault();b.stopPropagation();if(c=this.g[a.id])this.Ar(c,a),c.element.blur();b.ctrlKey||b.metaKey||"new"==a.yn?(NZ(this,a),this.sz(),this.player.pauseVideo(),c=g.ud(a.targetUrl),c=g.rd(c),g.cM(c,void 0,a.Wc)):(c=this.player.getVideoData().ac,
c=(0,g.y)(this.tL,this,c,a.targetUrl,a.Wc),c=(0,g.y)(this.sz,this,c),NZ(this,a,c))}}};
g.h.tL=function(a,b,c){var d=g.Tq(b);a&&d&&(d.v||d.list)?g.vX(this.player.app,d.v,c,d.list,!1,void 0,void 0):g.bM(b,c)};
g.h.Eq=function(a,b){g.Eo(a.element,"ytp-ce-element-hover")||("VIDEO"==b.type||"PLAYLIST"==b.type?g.J(a.element,"ytp-ce-element-hover"):g.V(this.player).g?(new g.L(function(){g.J(a.element,"ytp-ce-element-hover")},200)).start():g.J(a.element,"ytp-ce-element-hover"),MZ(this,b.TC),LZ(this,b.id,!0))};
g.h.Ar=function(a,b){g.Go(a.element,"ytp-ce-element-hover");g.Go(a.element,"ytp-ce-force-expand");LZ(this,b.id,!1)};
g.h.sz=function(a){this.player.sendVideoStatsEngageEvent(17,a)};
var b1=[346,426,470,506,570,640,853,1280,1920],c1="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),Pna=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"];var Gma={UM:"current",aO:"new"};var Ima={CLOSE:"close",dO:"openUrl",kB:"subscribe"},Jma={OM:"click",CLOSE:"close",wN:"hidden",CO:"rollOut",gB:"rollOver",hB:"shown"};var Lma={gP:"xx",hP:"xy",iP:"yx",jP:"yy"};g.r(h_,a_);var Qma={HA:"anchored",yO:"rect",FO:"shapeless"};var Uma={CLOSED:"closed",mO:"playerControlShow",gB:"rollOver",hB:"shown"};l_.prototype.Kb=function(){var a=bna(this,function(a){return"openUrl"==a.type&&null!=a.url});
return a?a.url:null};
l_.prototype.showLinkIcon=function(){return n_(this,function(a){return null!=a.url&&a.url.showLinkIcon})};
var m_={HA:"anchored",KA:"branding",CHANNEL:"channel",TM:"cta",yN:"highlightText",MN:"label",PLAYLIST:"playlist",pO:"popup",JO:"speech",kB:"subscribe",SO:"title",VIDEO:"video",cP:"website"},Yma={KA:"branding",EM:"card",aN:"drawer",xN:"highlight",UN:"marker",uO:"promotion",TEXT:"text",eP:"widget"},Zma={aP:"video_relative",nO:"player_relative"};u_.prototype.o=function(a,b,c,d){this.g[a]=b?!c:c;a=g.cc(this.g,function(a){return a});
this.l!=a&&(this.l=a,this.i.M(this.u,a,d))};v_.prototype.ia=function(){return this.u};
v_.prototype.l=function(){};var z_={bevel:1,dropshadow:2};g.r(E_,v_);
E_.prototype.l=function(a,b){var c=r_(a);if(c){var d=e_(c,b);if(!(0>=d.width||0>=d.height)){var e;if(e=(c=(c=q_(a))&&c.g?c.g:null)&&c.length?c[0]:null){var f=g.Sh(c_(b,d_(e,new g.Ph(e.D,e.F,e.Bi,e.l),b.g))),k=d.clone();c=new g.Ph(f.x,f.y,1,1);var l=Math.max(k.left+k.width,c.left+c.width),m=Math.max(k.top+k.height,c.top+c.height);k.left=Math.min(k.left,c.left);k.top=Math.min(k.top,c.top);k.width=l-k.left;k.height=m-k.top;c=a.i;k=C_(k,c.effects);l=w_(this,k.width,k.height);m=B_(c,k.width,k.height,this.g);
d=new g.Ph(d.left-k.left,d.top-k.top,d.width,d.height);var n=new g.$d(f.x-k.left,f.y-k.top);this.o=17*$Z(b.g,e.i,e.g?e.g:"xy");e=c.cornerRadius;f=a.i;var p=this.g&&o_(a),u=p?f.borderWidth+1:f.borderWidth;p=(f=u?new xZ(u,p?f.i:f.borderColor):null)?f.g/2:0;u=jna(d,n);var x=this.A(d,e,n,u),C=n.x;n=n.y;var E=d.width,H=d.height,S=d.left;d=d.top;var X=new uZ;X.moveTo(S+e+p,d+p);"t"==u&&(X.Zb(x.start,d+p),X.Zb(C,n),X.Zb(x.end,d+p));X.Zb(S+E-e-p,d+p);vZ(X,e,e,-90);"r"==u&&(X.Zb(S+E-p,x.start),X.Zb(C,n),X.Zb(S+
E-p,x.end));X.Zb(S+E-p,d+H-e-p);vZ(X,e,e,0);"b"==u&&(X.Zb(x.end,d+H-p),X.Zb(C,n),X.Zb(x.start,d+H-p));X.Zb(S+e+p,d+H-p);vZ(X,e,e,90);"l"==u&&(X.Zb(S+p,x.end),X.Zb(C,n),X.Zb(S+p,x.start));X.Zb(S+p,d+e+p);vZ(X,e,e,180);X.close();CZ(l,X,f,m);if(m=this.ia())g.J(m,"annotation-shape"),g.J(m,"annotation-speech-shape"),g.ii(m,k.left,k.top),g.si(m,k.width,k.height),D_(l,m,c.effects)}}}};
E_.prototype.A=function(a,b,c,d){function e(a,c,d,e){a=Math.min(Math.max(e-2*b,0),a);c=g.Ud(c-a/2,d+b,d+e-a-b);return new g.yj(c,c+a)}
return"t"==d||"b"==d?e(this.o,c.x,a.left,a.width):"l"==d||"r"==d?e(this.o,c.y,a.top,a.height):new g.yj(0,0)};g.r(F_,v_);F_.prototype.l=function(a,b){var c=r_(a);if(c){var d=e_(c,b);if(!(0>=d.width||0>=d.height)){var e=a.i;c=C_(d,e.effects);var f=w_(this,c.width,c.height),k=new xZ(!e.l&&this.g?1:e.l,e.bgColor),l=new nZ("#000",0);d=A_(new g.Ph(0,0,d.width,d.height),e.cornerRadius,k?k.g/2+1:0);CZ(f,d,k,l);f=this.ia();g.J(f,"annotation-shape");e=e.g;XY(f,this.g?Math.max(e,.9):e);g.ii(f,c.left,c.top);g.si(f,c.width,c.height)}}};g.r(G_,v_);
G_.prototype.l=function(a,b){var c=r_(a);if(c){var d=e_(c,b);if(!(0>=d.width||0>=d.height)){c=a.i;var e=C_(d,c.effects),f=w_(this,e.width,e.height),k=new g.Ph(0,0,d.width,d.height);d=B_(c,d.width,d.height,this.g);var l=c.cornerRadius;var m=a.i;var n=this.g&&o_(a),p=n?m.borderWidth+1:m.borderWidth;m=p?new xZ(p,n?m.i:m.borderColor):null;k=A_(k,l,m?m.g/2+1:0);CZ(f,k,m,d);if(k=this.ia())g.J(k,"annotation-shape"),g.J(k,"annotation-popup-shape"),g.ii(k,e.left,e.top),g.si(k,e.width,e.height),D_(f,k,c.effects)}}};g.r(H_,E_);H_.prototype.A=function(a,b,c,d){function e(a,c,d,e){a=Math.min(Math.max(e-2*b,0),a);c=c<=d+e/2?Math.max(d+e/4-a/2,d+b):Math.min(d+3*e/4-a/2,d+e-a-b);return new g.yj(c,c+a)}
return"t"==d||"b"==d?e(this.o,c.x,a.left,a.width):"l"==d||"r"==d?e(this.o,c.y,a.top,a.height):new g.yj(0,0)};g.r(I_,g.F);g.h=I_.prototype;g.h.Pw=function(){this.F||(this.o&&g.ui(this.o,!0),this.u&&g.ui(this.u,!0),this.l&&(this.l.g=!0,XY(this.i,N_(this)?1:0),this.l.l(this.g,K_(this))),this.D.isActive()&&this.D.stop(),this.F=!0,this.H=this.aa.Xl(g.NJ(this.A),"mouseleave",function(a){this.Cm.stop();this.kg(a)}))};
g.h.kg=function(){this.F&&(this.O?this.D.start():this.Sv(),this.l&&(this.l.g=!1,XY(this.i,N_(this)?1:0),this.l.l(this.g,K_(this))),this.F=!1,this.H&&(this.aa.Na(this.H),this.H=null))};
g.h.Sv=function(){this.o&&g.ui(this.o,!1);this.u&&g.ui(this.u,!1)};
g.h.FE=function(a){this.Y=a;this.Cm.vj()};
g.h.tC=function(){var a=this.Y,b=new g.$d(a.clientX,a.clientY),c=g.mi(this.A.getRootNode()),d=O_(c,this.K);c=(this.u&&YY(this.u)||this.o&&YY(this.o))&&O_(c,this.O);d&&d.contains(b)||c&&c.contains(b)?this.Pw(a):this.kg(a)};
g.h.show=function(){var a=this.g.i;a=(a&&0==a.g||"title"==this.g.style||"highlightText"==this.g.style?!1:!0)&&!this.l;var b=!this.i;if(a){var c=K_(this),d=null;"highlight"==this.g.type||"label"==this.g.style?d=new F_:"popup"==this.g.style?d=new G_:"anchored"==this.g.style?d=new E_:"speech"==this.g.style&&(d=new H_);d&&(d.l(this.g,c),this.l=d,c=d.ia())&&(g.ui(c,!1),g.J(c,"annotation-type-"+this.g.type.toLowerCase()),this.P(c))}if(b){c=["annotation"];"highlightText"!=this.g.style||c.push("annotation-no-mouse");
c.push("annotation-type-"+this.g.type.toLowerCase());this.i=g.we("DIV",c);g.ui(this.i,!1);this.g.o&&(this.C=g.we("DIV","inner-text"),"label"==this.g.style&&(g.J(this.C,"player-label-text"),this.C.style.backgroundColor=this.g.i.bgColor),g.Ie(this.C,this.g.o),this.i.appendChild(this.C));g.nq(this.i,"annotation_id",this.g.id);this.P(this.i);kna(this,this.i);if(o_(this.g)&&this.g.showLinkIcon()){if(d=this.g.Kb())c=this.i,d=new g.zn(YZ(d)),c.title=d.g+d.i;this.u=g.we("SPAN","annotation-link-icon");g.ui(this.u,
!1);this.i.appendChild(this.u)}lna(this);o_(this.g)||(this.i.style.cursor="default")}if(a||b){a:{a=this.g.segment.g;if(a.length&&(a=j_(a[0]))){a=a.u;break a}a=0}this.i&&(this.i.style.zIndex=a);this.l&&this.l.ia()&&(this.l.ia().style.zIndex=a)}g.ui(this.i,!0);XY(this.i,N_(this)?1:0);M_(this);this.l&&this.l.ia()&&g.ui(this.l.ia(),!0)};
g.h.hide=function(){this.i&&g.ui(this.i,!1);this.l&&this.l.ia()&&g.ui(this.l.ia(),!1);this.N&&(this.aa.Na(this.N),this.N=null)};g.r(P_,g.F);g.h=P_.prototype;g.h.hide=function(){this.isVisible=!1;this.view&&(Q_(this),this.view.hide())};
g.h.show=function(){this.isVisible=!0;this.view&&(this.view.show(),this.i.subscribe("resize",this.Ow,this),this.i.subscribe("onVideoAreaChange",this.Fy,this))};
g.h.destroy=function(){if(this.view){Q_(this);var a=this.view,b=a.aa;g.es(b.g);b.g.length=0;a.Cm.dispose();a.D.dispose();a.i&&g.De(a.i);a.l&&a.l.ia()&&g.De(a.l.ia())}R_(this)};
g.h.Fy=function(){M_(this.view)};
g.h.Ow=function(){M_(this.view)};g.r(S_,lZ);g.r(T_,lZ);g.r(U_,T_);g.r(V_,lZ);g.r(W_,lZ);g.r(X_,T_);g.r(Y_,T_);g.r(Z_,lZ);g.r($_,lZ);i0.prototype.l=function(a,b){var c=g.Ne(b.target,"label");c&&g.K(c,"iv-card-poll-choice-focused",a)};
i0.prototype.C=function(a,b){var c=g.Ne(b.target,null,"iv-card-poll",void 0);if(c)if(a.o)g.ke("iv-card-sign-in-button",c).click();else{var d=parseInt(mma(b.target),10);if(null==a.g)a.choices[d].count++,a.g=d;else if(a.g!=d){var e=a.choices[a.g];e.count=Math.max(e.count-1,0);a.choices[d].count++;a.g=d}else e=a.choices[a.g],e.count=Math.max(e.count-1,0),a.g=null;k0(a,c);g.ir(this.g.videoData.zd,{Bc:{action_poll_vote:1},tb:{poll_id:a.id,index:d,session_token:a.F}});e0(this.g.logger,a.l,void 0,{"link-id":d},
a.i.click,5);(c=g.Dt())&&g.mt(c,a.A)}};
i0.prototype.A=function(a){var b=g.w("yt.www.ypc.bootstrap.api.loadOffersForInnertubeRequestParams"),c;b&&(c=function(){b(a.F,a.C)});
s0(this,a,!0,c)};
i0.prototype.D=function(a){var b=g.w("yt.www.ypc.bootstrap.api.loadOffers");b&&(b=g.Va(b,a.K,a.F,a.C));s0(this,a,!1,b)};g.r(z0,g.F);g.h=z0.prototype;g.h.addCueRange=function(a,b,c,d,e){a=new g.QD(a,b,{id:c});g.G(this,a);a.namespace="annotations_module";d&&UY(a).subscribe("onEnter",d,this);e&&UY(a).subscribe("onExit",e,this);g.WJ(this.context.fa,[a])};
g.h.qn=function(){this.context.i.subscribe("resize",this.Vk,this)};
g.h.ia=function(){return this.Aa};
g.h.ni=function(a,b,c,d,e,f,k){this.context.g.ca(a,"click",g.Va(this.Wl,b,c,d,e,f||[],k||0),this);this.context.g.ca(a,"touchstart",g.Va(function(){this.Ls=!1}),this);
this.context.g.ca(a,"touchmove",g.Va(function(){this.Ls=!0}),this)};
g.h.Wl=function(a,b,c,d,e,f,k){if(this.Ls)return!1;k&&(k.stopPropagation(),k.preventDefault());wna(this,a,c,d,e,f);return!1};
g.h.show=function(){this.ha=(0,g.B)()};
g.h.hide=function(){};
g.h.destroy=function(){g.De(this.ia())};
g.h.Vk=function(){};g.r(C0,z0);g.h=C0.prototype;g.h.isAvailable=function(){var a;if(a=!!this.l.length)(a=this.i.getRootNode())?(a=g.ti(a),a=173<a.width&&173<a.height):a=!1;return a};
g.h.Vk=function(){var a=this.isAvailable();g.ui(this.ia(),a);g.K(this.context.fa.getRootNode(),"ytp-iv-drawer-enabled",a);VY(this.i)};
g.h.destroy=function(){this.i.mi(!1);this.i.getRootNode().removeChild(this.C);g.yq(this.N);g.es(this.Y);this.W&&this.W.dispose();this.D&&this.D.dispose();z0.prototype.destroy.call(this)};
g.h.hE=function(a){this.O.start();a.preventDefault();a=a||window.event;var b=0;"MozMousePixelScroll"==a.type?b=0==(a.axis==a.HORIZONTAL_AXIS)?a.detail:0:window.opera?b=a.detail:b=0==a.wheelDelta%120?"WebkitTransform"in document.documentElement.style?window.chrome&&0==navigator.platform.indexOf("Mac")?a.wheelDeltaY/-30:a.wheelDeltaY/-1.2:a.wheelDelta/-1.6:a.wheelDeltaY/-3;if(a=b)this.o.scrollTop+=a};
g.h.zz=function(a){if(!g.Eo(this.i.getRootNode(),"ytp-cards-teaser-shown")){if(this.g!=a){var b=g.Dt(),c=this.g?this.g.Db.u:this.H;b&&c&&kZ(b,[c]);this.g=a;F0(this)}YY(this.ia())&&(2==this.context.fa.getPresentingPlayerType()?b=1==(isNaN(void 0)?this.context.fa.getAdState():void 0):(b=isNaN(void 0)?this.context.fa.getPlayerState():void 0,b=1==b||0==b&&0===this.context.fa.getCurrentTime()),b&&a.Db.teaserDurationMs&&this.i.mi(!0,{teaserText:a.Db.teaserText,durationMs:a.Db.teaserDurationMs}));this.ma.isActive()||
((!this.u||!this.O.isActive()&&this.Z)&&G0(this,a),this.ma.start(910+a.Db.teaserDurationMs))}};
g.h.nL=function(a){this.u||(this.g=a,F0(this),G0(this,a),A0(this,"YOUTUBE_DRAWER_AUTO_OPEN",!1,a))};
g.h.EB=function(){if(this.u){g0(this.context.logger,this.P,4,H0(this).i.close);var a=g.Dt();a&&this.K&&g.mt(a,this.K);B0(this)}};
g.h.MB=function(){g.K(this.C,"iv-drawer-scrolled",0<this.o.scrollTop)};
g.h.pD=function(){var a=g.Dt(),b=H0(this);b=b?b.u:this.H;a&&b&&jZ(a,[b])};
g.h.oD=function(){var a=g.Dt(),b=H0(this);b=b?b.u:this.H;a&&b&&kZ(a,[b])};
g.h.sD=function(){var a=H0(this);h0(this.context.logger,8,a.l,a.i.yL);var b=g.Dt();b&&a&&jZ(b,[a.D,a.u])};
g.h.rD=function(){var a=g.Dt(),b=H0(this);a&&b&&kZ(a,[b.D])};
g.h.qD=function(a){var b=H0(this),c=g.Dt();this.g?a?(a=this.context.logger,h0(a,9,b.l,b.i.ts),a.g.sendVideoStatsEngageEvent(4,void 0),c&&g.mt(c,b.D)):(a=this.context.logger,h0(a,12,b.l,b.i.ts),a.g.sendVideoStatsEngageEvent(4,void 0),c&&g.mt(c,b.u)):(a=this.context.logger,g0(a,this.P,12,b.i.ts),a.g.sendVideoStatsEngageEvent(4,void 0),c&&this.H&&g.mt(c,this.H))};
var D0={collaborator:S_,donation:U_,episode:$_,movie:$_,playlist:V_,poll:W_,productListing:X_,simple:T_,tip:Y_,video:Z_};g.r(I0,z0);I0.prototype.qn=function(){z0.prototype.qn.call(this);Ena(this)};
I0.prototype.show=function(){z0.prototype.show.call(this);var a=g.Dt(),b=this.annotation.data;a&&b&&(b=b.session_data)&&jZ(a,[g.it(b.itct)])};
I0.prototype.hide=function(){z0.prototype.hide.call(this);var a=g.Dt(),b=this.annotation.data;a&&b&&(b=b.session_data)&&kZ(a,[g.it(b.itct)])};g.r(J0,I0);g.h=J0.prototype;g.h.uL=function(a,b,c,d){this.l.stop();if(!this.o){var e=g.ti(a);this.g||(g.ri(a,e.width),g.ri(b,e.width));g.ai(c,"top",e.height-Math.max(Math.min(e.height,d)/2+10,20)+"px");g.ai(c,"right","1px");this.o=!0;g.ui(a,!0);this.A=new g.L(function(){g.J(this.ia(),"iv-branding-active")},0,this);
this.A.start()}};
g.h.SC=function(a,b){g.Go(this.ia(),"iv-branding-active");this.C=new g.L((0,g.y)(function(){g.ui(a,!1);this.g||g.ri(b,0)},this),250);
this.C.start();this.o=!1};
g.h.show=function(){if(!this.isActive){I0.prototype.show.call(this);if(!this.D){g.J(this.ia(),"iv-branding");var a=this.annotation.data;this.u=a.image_width;this.i=g.we("IMG",{src:a.image_url,"class":"branding-img iv-click-target",width:a.image_width,height:a.image_height});g.ui(this.i,!1);var b=g.we("DIV","branding-img-container",this.i);this.ia().appendChild(b);var c=g.we("DIV","iv-branding-context-name");g.Ie(c,a.channel_name);var d=g.we("DIV","iv-branding-context-subscribe");if(b=a.standalone_subscribe_button_data)this.g=
new g.pV(b.subscribeText,b.subscribeCount,b.unsubscribeText,b.unsubscribeCount,!!b.enabled,!!b.classic,a.channel_id,!!b.subscribed,b.feature,a.session_data.itct,b.signinUrl,this.context.fa),this.g.X(d);b=g.we("DIV","iv-branding-context-subscribe-caret");c=g.we("DIV","branding-context-container-inner",b,c,d);g.ui(c,!1);d=g.we("DIV","branding-context-container-outer",c);g.ai(d,"right",this.u+"px");this.ia().appendChild(d);var e=this.annotation.Kb();e&&this.ni(this.i,e,this.annotation.id,a.session_data,
this.annotation.g);this.l=new g.L(g.Va(this.SC,c,d),500,this);g.G(this,this.l);this.context.g.ca(this.ia(),"mouseover",(0,g.y)(this.uL,this,c,d,b,a.image_height));this.context.g.ca(this.ia(),"mouseout",(0,g.y)(this.l.start,this.l,void 0));this.D=!0}d0(this.context.logger,this.annotation.g);g.ui(this.ia(),!0);this.isActive=!0;if(this.i){a=this.i;var f=void 0===f?0:f;b=WY(a).width;c=g.Ha(void 0)?void 0:b;g.ii(a,c);f=new hZ(a,[c,a.offsetTop],[c-b-f,a.offsetTop],200,oma);g.G(this,f);this.context.l.ca(f,
"begin",g.Va(g.ui,a,!0));f.play()}}};
g.h.hide=function(){this.isActive&&(I0.prototype.hide.call(this),g.ui(this.ia(),!1),this.isActive=!1)};
g.h.destroy=function(){this.g&&(this.g.dispose(),this.g=null);I0.prototype.destroy.call(this)};g.r(K0,I0);g.h=K0.prototype;g.h.show=function(){this.isActive||(I0.prototype.show.call(this),this.H||(Fna(this),this.H=!0),g.ui(this.ia(),!0),this.annotation&&this.annotation.g&&d0(this.context.logger,this.annotation.g),g.gh(function(){g.Go(this.ia(),"iv-promo-inactive")},100,this),this.ia().removeAttribute("aria-hidden"),this.isActive=!0,N0(this),M0(this),O0(this,this.C))};
g.h.hide=function(){this.isActive&&(g.J(this.ia(),"iv-promo-inactive"),this.isActive=!1,this.ia().setAttribute("aria-hidden",!0))};
g.h.Wl=function(a,b,c,d,e,f,k){return this.u?!1:I0.prototype.Wl.call(this,a,b,c,d,e,f,k)};
g.h.Gp=function(a,b){b.stopPropagation();M0(this);O0(this,a);this.g.focus()};
g.h.vC=function(a){this.F=!0;this.Gp(500,a)};
g.h.uC=function(){this.F=!1;L0(this)};
g.h.mC=function(a){a.stopPropagation();this.hide();f0(this.context.logger,this.annotation.g)};
g.h.nC=function(a){a.stopPropagation();N0(this);this.u=!0;g.J(this.ia(),"iv-promo-collapsed-no-delay");this.A.start();f0(this.context.logger,this.annotation.g)};
g.h.destroy=function(){this.A.dispose();I0.prototype.destroy.call(this)};g.r(P0,g.pK);g.h=P0.prototype;g.h.Yb=function(a,b){if(!Q0(g.V(this.player).playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":var c=g.Io(b);c&&V0(this,c);return!0;case "removeCustomAnnotationById":return b&&this.g&&(E0(this.g,b),VY(this.player)),!0}return null};
g.h.getOptions=function(){return Q0(g.V(this.player).playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.h.Br=function(){if(this.o){var a=g.NJ(this.player).getVideoContentRect(!0);g.si(this.o.element,a.width,a.height);g.ii(this.o.element,a.left,a.top)}if(this.g){var b=g.UJ(this.player);a=this.g;b=b.width;g.K(a.C,"iv-drawer-small",426>=b);g.K(a.C,"iv-drawer-big",1280<=b)}};
g.h.cJ=function(a){this.gc(a.state);g.U(a.state,2)&&(this.qd()&&this.we()&&2!=this.player.getPresentingPlayerType()&&this.setCardsVisible(!1),this.mi(!1))};
g.h.load=function(){g.pK.prototype.load.call(this);this.gc(g.MJ(this.player));this.H++;var a=this.player.getVideoData(),b=a.videoId,c=(0,g.y)(this.LH,this,b,this.H),d=(0,g.y)(function(){this.C=null},this);
g.Ts()&&(c=W0(this,c));c={format:"XML",Vc:c,onError:d,Bc:{}};a.isPharma&&(c.Bc.pharma="1");c.method="POST";c.withCredentials=!0;d=g.V(this.player);"gaming"==d.playerStyle&&(c.Bc.gaming="1");(b=d.K.get(b))&&X0(c,b);b=b&&(b.bl||b.al);if(!a.Pk||b)a.zd?R0(this,a.zd,c):(this.l=(0,g.y)(this.QD,this,c),this.player.addEventListener("videodatachange",this.l));g.cK(this.player,this.o.element,4);this.Br()};
g.h.gc=function(a){a=!a.isCued()&&!g.U(a,1024);g.lC(this.u,a);g.lC(this.o,a)};
g.h.QD=function(a){var b=this.player.getVideoData();b.zd&&(this.l&&(this.player.removeEventListener("videodatachange",this.l),this.l=null),R0(this,b.zd,a))};
g.h.unload=function(){pna(this.D);g.ZJ(this.player,"annotations_module");g.Zb(this.i,function(a){a.destroy()});
g.Zb(this.K,function(a){a.destroy()});
this.F=null;this.g&&(this.g.destroy(),this.g=null,VY(this.player));this.N=!1;this.C&&(this.C.abort(),this.C=null);this.i={};this.K={};this.u.hide();g.pK.prototype.unload.call(this);g.kC(this.o);this.l&&(this.player.removeEventListener("videodatachange",this.l),this.l=null)};
g.h.LH=function(a,b,c){this.C=null;if(!T0(this,b,a)&&(a=g.Oq(c)&&c.responseXML?c.responseXML:null)){V0(this,a);g.J(this.player.getRootNode(),"iv-module-loaded");a=[];for(var d in this.i){b=this.i[d].annotation;if(b.segment)if(c=b.segment,c.g.length)if(c=c.g[0].i||c.g[0].g||c.g[0].l,!c||2>c.length)c=null;else{var e=c.length-1;c=0>=c[0].t&&0>=c[e].t?null:{start:c[0].t,end:c[e].t}}else c=null;else c=null;if(e=c)if(c=1E3*e.start,e=1E3*e.end,0==c&&(c++,e++),!(e<c)){var f={id:d,namespace:"annotations_module"};
"marker"==b.type&&(f.style="ytp-chapter-marker",f.tooltip=b.o,f.visible=!0);b=new g.QD(c,e,f);a.push(b)}}g.WJ(this.player,a)}};
g.h.Ey=function(a){a==this.player.getVideoData().videoId&&(this.loaded?Kna(this):this.load())};
g.h.ND=function(a){a=a.getId();var b=this.i[a];b&&!b.l&&(b=b.annotation,Y0(this,a),d0(this.D,b.g))};
g.h.OD=function(a){Z0(this,a.getId())};
g.h.Rv=function(a){a&&(a.hide(),a1(this,"shown",!1,a.annotation.id),this.ol(a.annotation,"hidden"))};
g.h.Iz=function(a){a&&(a.show(),a1(this,"shown",!0,a.annotation.id),this.ol(a.annotation,"shown"))};
g.h.pK=function(a,b,c){var d=this.i[a];if(d&&b.value!=c){b.value=c;var e=!1;p_(d.annotation,function(a){e=e||a.value});
Nna(this,a,b,e)}};
g.h.PG=function(a){if(a&&a.id){var b=a.Kb();if(b){var c=YZ(b);if(c){var d=(0,g.y)(this.ol,this,a,"click");if("new"==y0(c,b.target)||$0(this,b))d(),d=null;e0(this.D,a.g,d)}}}};
g.h.ol=function(a,b){ana(a,function(c){if(c.trigger==b&&"openUrl"==c.type&&c.url){var d=this.player.getVideoData(),e;if(!(e=!$0(this,c.url))){e=x0(c.url);var f=tna(c.url);e?(d.videoId==e?this.player.seekTo(f||0):(d=U0(this).fa,g.vX(d.app,e,void 0,void 0,void 0,void 0,void 0),f&&U0(this).fa.ec()&&U0(this).fa.seekTo(f)),d=!0):d=!1;e=!d}e&&(e=g.V(this.player),(d=YZ(c.url))?(f=v0(d),e&&"com"==f[0]&&"google"==f[1]&&"plus"==f[2]&&(e=g.Va(una,e.pageId,e.qc),d=new g.zn(d),e=e(d.i),d.i=e,d=d.toString())):
d=null,d&&(this.player.pauseVideo(),c=y0(d,c.url.target),e=a.itct,"ei"in g.Tq(d)&&(d=g.Jh(d,"ei")),g.cM(d,"current"==c?"_top":void 0,{itct:e})))}},this)};
g.h.TH=function(){a1(this,"playerControlShow",!1)};
g.h.UJ=function(){a1(this,"playerControlShow",!0)};
g.h.PD=function(a){a1(this,"rollOver",!0,a.id)};
g.h.kg=function(a){a1(this,"rollOver",!1,a.id)};
g.h.sH=function(a){a&&a.id&&(this.i[a.id].l=!0,Z0(this,a.id),f0(this.D,a.g),this.ol(a,"close"),a1(this,"closed",!0,a.id))};
g.h.qd=function(){return!!this.g&&this.g.isAvailable()};
g.h.we=function(){this.qd();return!!this.g&&this.g.u};
g.h.setCardsVisible=function(a,b,c){b=void 0===b?!1:b;this.qd();this.g&&(a?c?A0(this.g,c,b):A0(this.g,"YOUTUBE_DRAWER_AUTO_OPEN",b):B0(this.g))};
g.h.mi=function(a,b){this.player.M(a?"cardsteasershow":"cardsteaserhide",b)};
g.h.T=function(){g.V(this.player).K.unsubscribe("vast_info_card_add",this.Ey,this);g.Go(this.player.getRootNode(),"ytp-iv-drawer-open");for(var a=this.O,b=0,c=a.length;b<c;b++)g.Us(a[b]);this.O.length=0;g.pK.prototype.T.call(this)};g.vU.annotations_module=P0;g.vU.creatorendscreen=FZ;})(_yt_player);
