(function(g){var window=this;var RY=function(a){a.g||(a.g=new g.zo,g.I(a,a.g));return a.g},SY=function(a){a.N("cardstatechange",a.sd()&&a.xe()?1:0)},TY=function(a){var b=g.Gh(a);
a=g.Nh(a);return new g.ih(b.x,b.y,a.width,a.height)},UY=function(a,b){var c=a.style;
"opacity"in c?c.opacity=b:"MozOpacity"in c?c.MozOpacity=b:"filter"in c&&(c.filter=""===b?"":"alpha(opacity="+100*Number(b)+")")},VY=function(a){return"none"!=a.style.display},WY=function(a,b){if(/^\d+px?$/.test(b))return parseInt(b,10);
var c=a.style.left,d=a.runtimeStyle.left;a.runtimeStyle.left=a.currentStyle.left;a.style.left=b;var e=a.style.pixelLeft;a.style.left=c;a.runtimeStyle.left=d;return+e},bna=function(a){var b=g.Ah(a,"fontSize");
var c=(c=b.match(Zma))&&c[0]||null;if(b&&"px"==c)return parseInt(b,10);if(g.Ld){if(String(c)in $ma)return WY(a,b);if(a.parentNode&&1==a.parentNode.nodeType&&String(c)in ana)return a=a.parentNode,c=g.Ah(a,"fontSize"),WY(a,b==c?"1em":b)}c=g.Qd("SPAN",{style:"visibility:hidden;position:absolute;line-height:0;padding:0;margin:0;border:0;height:1em;"});a.appendChild(c);b=c.offsetHeight;g.Wd(c);return b},cna=function(a){if(/-[a-z]/.test("pollChoiceIndex"))return null;
if(g.zk&&a.dataset){if(g.ic()&&!("pollChoiceIndex"in a.dataset))return null;a=a.dataset.pollChoiceIndex;return void 0===a?null:a}return a.getAttribute("data-"+g.uc("pollChoiceIndex"))},ZY=function(a){a=g.Pa(a);
delete XY[a];g.Wb(XY)&&YY&&YY.stop()},$Y=function(){YY||(YY=new g.N(function(){dna()},20));
var a=YY;a.isActive()||a.start()},dna=function(){var a=(0,g.C)();
g.Jb(XY,function(b){aZ(b,a)});
g.Wb(XY)||$Y()},bZ=function(a,b){g.rf.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.D;this.state=b.g},cZ=function(a,b,c,d){g.Yn.call(this);
if(!g.Ja(a)||!g.Ja(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.i=a;this.F=b;this.duration=c;this.B=d;this.coords=[];this.progress=this.D=0;this.A=null},aZ=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);1<a.progress&&(a.progress=1);a.D=1E3/(b-a.A);a.A=b;dZ(a,a.progress);1==a.progress?(a.g=0,ZY(a),a.Vc(),a.l()):1==a.g&&a.Ar()},dZ=function(a,b){g.Ma(a.B)&&(b=a.B(b));
a.coords=Array(a.i.length);for(var c=0;c<a.i.length;c++)a.coords[c]=(a.F[c]-a.i[c])*b+a.i[c]},eZ=function(a,b,c,d,e){cZ.call(this,b,c,d,e);
this.element=a},fZ=function(a,b,c,d,e){if(2!=b.length||2!=c.length)throw Error("Start and end points must be 2D");
eZ.call(this,a,b,c,d,e)},ena=function(a){return Math.pow(a,3)},fna=function(a){return 3*a*a-2*a*a*a},gZ=function(a){g.H.call(this);
this.i=a||window;this.g=[]},gna=function(a,b,c,d){c=(0,g.z)(c,d||a.i);
b=g.Er(b,"change",c,"iv-card-poll-choice-input");a.g.push(b)},hZ=function(a,b){(0,g.B)(b,function(c){g.vs("visualElementShown",{csn:a,
ve:g.Es(c),eventType:4},g.As,void 0,void 0)})},iZ=function(a,b){(0,g.B)(b,function(c){g.vs("visualElementHidden",{csn:a,
ve:g.Es(c),eventType:8},g.As,void 0,void 0)})},jZ=function(a,b,c){this.id=a;
this.timestamp=b.timestamp||0;this.type=b.card_type;this.teaserText=b.teaser_text;this.teaserDurationMs=b.teaser_duration_ms;this.startMs=b.start_ms;this.autoOpen=b.auto_open||!1;this.Wc=b.session_data||{};this.l=c;this.sponsored=b.sponsored||!1;a=b.tracking||{};this.i={yD:a.impression,click:a.click,close:a.close,VL:a.teaser_impression,Cs:a.teaser_click};b=b.tracking_params||{};this.A=g.Ds(b.card);this.D=g.Ds(b.teaser);this.u=g.Ds(b.icon)},kZ=function(a,b){g.Pf.call(this);
this.Aj=a;this.Jp=b;this[g.tf]=!1},pZ=function(a,b,c,d){kZ.call(this,a,b);
a=this.Jp;b=this.ka();c?(b.setAttribute("stroke",c.i),b.setAttribute("stroke-opacity",1),c=c.g,g.v(c)&&-1!=c.indexOf("px")?b.setAttribute("stroke-width",parseFloat(c)/hna(a)):b.setAttribute("stroke-width",c)):b.setAttribute("stroke","none");this.fill=d;c=this.Jp;a=this.ka();if(d instanceof lZ)a.setAttribute("fill",d.F),a.setAttribute("fill-opacity",d.H);else if(d instanceof mZ){b="lg-"+d.u+"-"+d.B+"-"+d.A+"-"+d.D+"-"+d.g+"-"+d.i;var e=b in c.g?c.g[b]:null;if(!e){e=nZ(c,"linearGradient",{x1:d.u,y1:d.B,
x2:d.A,y2:d.D,gradientUnits:"userSpaceOnUse"});var f="stop-color:"+d.g;g.Ea(d.l)&&(f+=";stop-opacity:"+d.l);f=nZ(c,"stop",{offset:"0%",style:f});e.appendChild(f);f="stop-color:"+d.i;g.Ea(d.o)&&(f+=";stop-opacity:"+d.o);d=nZ(c,"stop",{offset:"100%",style:f});e.appendChild(d);e=oZ(c,b,e)}a.setAttribute("fill","url(#"+e+")")}else a.setAttribute("fill","none")},qZ=function(){},rZ=function(a,b){kZ.call(this,a,b)},sZ=function(){this.Ta=[];
this.Ba=[];this.Md=[]},tZ=function(a,b,c,d){var e=a.ud[0]-b*Math.cos(g.sd(d))+b*Math.cos(g.sd(d+90)),f=a.ud[1]-c*Math.sin(g.sd(d))+c*Math.sin(g.sd(d+90));
a.Ta.push(3);a.Ba.push(1);a.Md.push(b,c,d,90,e,f);a.Fk=!1;a.ud=[e,f]},jna=function(a,b){for(var c=a.Md,d=0,e=0,f=a.Ta.length;e<f;e++){var k=a.Ta[e],l=ina[k]*a.Ba[e];
b(k,c.slice(d,d+l));d+=l}},uZ=function(a,b,c,d){pZ.call(this,a,b,c,d)},vZ=function(a,b){this.g=a;
this.i=b},wZ=function(a,b,c,d,e){g.jo.call(this,e);
this.width=a;this.height=b;this.l=c||null;this.I=d||null},hna=function(a){var b=a.qj();
return b?b.width/(a.l?new g.vd(a.l,a.I):a.qj()).width:0},mZ=function(a,b,c,d,e,f,k,l){this.u=a;
this.B=b;this.A=c;this.D=d;this.g=e;this.i=f;this.l=g.Ca(k)?k:null;this.o=g.Ca(l)?l:null},lZ=function(a,b){this.F=a;
this.H=null==b?1:b},xZ=function(a,b){kZ.call(this,a,b)},yZ=function(a,b,c,d){pZ.call(this,a,b,c,d)},zZ=function(a,b,c,d,e){wZ.call(this,a,b,c,d,e);
this.g={};this.O=g.Nd&&!g.Bc(526);this.P=new g.an(this)},nZ=function(a,b,c){a=a.M.g.createElementNS("http://www.w3.org/2000/svg",b);
if(c)for(var d in c)a.setAttribute(d,c[d]);return a},AZ=function(a,b,c,d){b=nZ(a,"path",{d:kna(b)});
c=new yZ(b,a,c,d);a.o.ka().appendChild(c.ka())},kna=function(a){var b=[];
jna(a,function(c,d){switch(c){case 0:b.push("M");Array.prototype.push.apply(b,d);break;case 1:b.push("L");Array.prototype.push.apply(b,d);break;case 2:b.push("C");Array.prototype.push.apply(b,d);break;case 3:var e=d[3];b.push("A",d[0],d[1],0,180<Math.abs(e)?1:0,0<e?1:0,d[4],d[5]);break;case 4:b.push("Z")}});
return b.join(" ")},oZ=function(a,b,c){if(b in a.g)return a.g[b];
var d="_svgdef_"+lna++;c.setAttribute("id",d);a.g[b]=d;a.B.appendChild(c);return d},mna=function(){BZ||(BZ=new g.Bg(400),BZ.start());
return BZ},CZ=function(a,b){function c(l){return l.baseUrl}
function d(l){if(l){var m=l.simpleText;if(m)return m;if(l.runs)return(0,g.G)(l.runs,function(n){return n.text}).join("")}}
function e(l){if(l){var m=[],n=l.videoId;n&&m.push("v="+n);(n=l.playlistId)&&m.push("list="+n);(l=l.startTimeSeconds)&&m.push("t="+l);return"/watch?"+m.join("&")}}
var f={};f.startMs=parseInt(a.startMs,10);f.impressionUrls=(0,g.G)(a.impressionUrls||[],c);f.skip=a.skipEndscreen;a.trackingParams&&(f.visualElement=g.Ds(a.trackingParams));var k=(0,g.G)(a.elements||[],function(l,m){var n=l.endscreenElementRenderer;if(!n)return null;var p={},r=n.style,u=n.endpoint||{};p.id="element-"+m;p.type=r;p.title=d(n.title);p.metadata=d(n.metadata);p.callToAction=d(n.callToAction);p.Xu=n.image;p.left=parseFloat(n.left);p.width=parseFloat(n.width);p.top=parseFloat(n.top);p.aspectRatio=
parseFloat(n.aspectRatio);p.startMs=parseInt(n.startMs,10);p.endMs=parseInt(n.endMs,10);p.clickUrls=(0,g.G)(u.loggingUrls||[],c);p.jl=g.Rb(n,"title","accessibility","accessibilityData","label");p.impressionUrls=(0,g.G)(n.impressionUrls||[],c);p.wD=(0,g.G)(n.hovercardShowUrls||[],c);p.Wc={itct:n.trackingParams};p.visualElement=g.Ds(n.trackingParams);if("VIDEO"==r)p.targetUrl=u.urlEndpoint?u.urlEndpoint.url:e(u.watchEndpoint),p.fm=!1,p.Nn=b,p.videoDuration=d(n.videoDuration);else if("PLAYLIST"==r)p.targetUrl=
u.urlEndpoint?u.urlEndpoint.url:e(u.watchEndpoint),p.fm=!1,p.Nn=b,p.playlistLength=d(n.playlistLength);else if("CHANNEL"==r){if(r=g.Rb(u,"browseEndpoint","browseId"))p.channelId=r,p.targetUrl="/channel/"+r;p.fm=!1;p.Nn="new";p.isSubscribe=!!n.isSubscribe;if(p.isSubscribe){a:{if(r=n.hovercardButton)if(r=r.subscribeButtonRenderer){u=d(r.unsubscribedButtonText);var y=d(r.subscribedButtonText);if(r.subscribed){var D=d(r.subscriberCountWithUnsubscribeText);var F=d(r.subscriberCountText)}else D=d(r.subscriberCountText),
F=d(r.subscriberCountWithSubscribeText);var E=null;if(n.signinEndpoint&&(E=g.Rb(n,"signinEndpoint","webNavigationEndpointData","url"),!E)){n=void 0;break a}if(u&&(y||E)){n={subscribed:r.subscribed,subscribeText:u,subscribeCount:D,unsubscribeText:y,unsubscribeCount:F,enabled:r.enabled,signinUrl:E,classic:n.useClassicSubscribeButton};break a}}n=void 0}p.subscribeButton=n}else p.subscribersText=d(n.subscribersText)}else"WEBSITE"==r&&(p.targetUrl=g.Rb(u,"urlEndpoint","url"),p.fm=!0,p.Nn="new",p.iconUrl=
n.icon.thumbnails[0].url);return p});
f.elements=(0,g.Xd)(k,function(l){return!!l});
return f},DZ=function(a){g.TJ.call(this,a);
this.i=null;this.H=!1;this.o=null;this.g={};this.B={};this.A=this.l=null;this.I=[];a=g.W(a);this.P=g.yy(a)||g.Ay(a);this.jA=!0;this.D=0;this.F=new g.On;this.u=new g.Ir(this);g.I(this,this.u);this.u.K(this.player,g.pD("creatorendscreen"),this.sE);this.u.K(this.player,"crx_creatorendscreen",this.tE);this.u.K(this.player,"resize",this.ib);this.u.K(window,"focus",this.dL);this.load();var b=g.Rd("STYLE");(document.getElementsByTagName("HEAD")[0]||document.body).appendChild(b);g.of(this,function(){g.Wd(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},EZ=function(a){return a.player.getVideoData().ac?"current":a.P?"new":"current"},FZ=function(a){return"creator-endscreen-editor"===a},GZ=function(a,b){g.BJ(a.player,"creatorendscreen");
a.l&&(a.l.dispose(),a.l=null,a.A.dispose(),a.A=null);for(var c in a.g)a.g[c].dispose();a.g={};a.B={};0<a.I.length&&(a.I.forEach(function(l){l.dispose()}),a.I.length=0);
a.D=0;if((a.i=b)&&b.elements){nna(a);c=[];var d=new g.mD(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);g.W(a.player).g||(a.l=new g.U({C:"div",G:"ytp-ce-shadow"}),g.FJ(a.player,a.l.element,4),a.A=new g.qP(a.l,200));for(d=0;d<b.elements.length;++d){var e=b.elements[d],f=ona(a,e);a.g[e.id]=f;a.B[e.id]=e;g.FJ(a.player,f.element,4);var k=new g.mD(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(k);pna(a,f,e)}g.yJ(a.player,
c);a.ib()}},nna=function(a){var b=g.Ts(),c=g.Us();
c&&b&&a.i.visualElement&&g.Fs(c,b,[a.i.visualElement],void 0)},ona=function(a,b){var c=null;
switch(b.type){case "VIDEO":c={C:"div",W:["ytp-ce-element","ytp-ce-video"],L:{tabindex:"0","aria-label":b.jl||"","aria-hidden":"true"},J:[{C:"div",G:"ytp-ce-element-shadow"},{C:"div",G:"ytp-ce-covering-image",L:HZ(b)},{C:"div",G:"ytp-ce-covering-shadow-top"},{C:"a",G:"ytp-ce-covering-overlay",L:{href:b.targetUrl,tabindex:"-1"},J:[{C:"div",W:["ytp-ce-video-title","yt-ui-ellipsis","yt-ui-ellipsis-2"],L:{dir:g.Pn(a.F,b.title||"")},U:b.title},{C:"div",G:"ytp-ce-video-duration",U:b.videoDuration}]}]};
c=new g.U(c);break;case "PLAYLIST":c={C:"div",W:["ytp-ce-element","ytp-ce-playlist"],L:{tabindex:"0","aria-label":b.jl||"","aria-hidden":"true"},J:[{C:"div",G:"ytp-ce-element-shadow"},{C:"div",G:"ytp-ce-covering-image",L:HZ(b)},{C:"div",G:"ytp-ce-covering-shadow-top"},{C:"a",G:"ytp-ce-covering-overlay",L:{href:b.targetUrl,tabindex:"-1"},J:[{C:"div",W:["ytp-ce-playlist-title","yt-ui-ellipsis","yt-ui-ellipsis-2"],L:{dir:g.Pn(a.F,b.title||"")},U:b.title},{C:"div",G:"ytp-ce-playlist-count",J:[{C:"div",
G:"ytp-ce-playlist-icon"},{C:"div",G:"ytp-ce-playlist-count-text",U:b.playlistLength}]}]}]};c=new g.U(c);break;case "CHANNEL":c={C:"div",W:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],L:{tabindex:"0","aria-label":b.jl||"","aria-hidden":"true"},J:[{C:"div",G:"ytp-ce-element-shadow"},{C:"div",G:"ytp-ce-expanding-overlay",J:[{C:"div",G:"ytp-ce-expanding-overlay-hider"},{C:"div",G:"ytp-ce-expanding-overlay-background"},{C:"div",G:"ytp-ce-expanding-overlay-content",
J:[{C:"div",G:"ytp-ce-expanding-overlay-body",J:[{C:"div",G:"ytp-ce-expanding-overlay-body-padding",J:[{C:"a",W:["ytp-ce-channel-title","ytp-ce-link"],L:{href:b.targetUrl,target:"_blank",tabindex:"-1",dir:g.Pn(a.F,b.title||"")},U:b.title},b.subscribeButton?{C:"div",G:"ytp-ce-subscribe-container",J:[{C:"div",G:"ytp-ce-channel-subscribe"}]}:"",b.subscribersText?{C:"div",G:"ytp-ce-channel-subscribers-text",U:b.subscribersText}:"",b.metadata?{C:"div",W:["ytp-ce-channel-metadata","yt-ui-ellipsis","yt-ui-ellipsis-3"],
U:b.metadata}:""]}]}]}]},{C:"div",G:"ytp-ce-expanding-image",L:HZ(b)}]};c=new g.U(c);var d=g.Ed(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton){g.K(d,"ytp-ce-subscribe-button");if(g.W(a.player).g){var e=null;var f=b.Wc.itct}else e="endscreen",f=null;e=new g.iV(b.subscribeButton.subscribeText,b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,b.subscribeButton.enabled,b.subscribeButton.classic,b.channelId,!!b.subscribeButton.subscribed,
e,f,b.subscribeButton.signinUrl,a.player);d.appendChild(e.element);a.I.push(e)}break;case "WEBSITE":c={C:"div",W:["ytp-ce-element","ytp-ce-website"],L:{tabindex:"0","aria-label":b.jl||"","aria-hidden":"true"},J:[{C:"div",G:"ytp-ce-element-shadow"},{C:"div",G:"ytp-ce-expanding-overlay",J:[{C:"div",G:"ytp-ce-expanding-overlay-hider"},{C:"div",G:"ytp-ce-expanding-overlay-background"},{C:"div",G:"ytp-ce-expanding-overlay-content",J:[{C:"div",G:"ytp-ce-expanding-overlay-body",J:[{C:"div",G:"ytp-ce-expanding-overlay-body-padding",
J:[{C:"div",G:"ytp-ce-website-title",L:{dir:g.Pn(a.F,b.title||"")},U:b.title},{C:"div",G:"ytp-ce-website-metadata",U:b.metadata},{C:"a",W:["ytp-ce-website-goto","ytp-ce-link"],L:{href:b.targetUrl,target:"_blank",tabindex:"-1"},U:b.callToAction}]}]}]}]},{C:"div",G:"ytp-ce-expanding-image",L:HZ(b)},{C:"div",G:"ytp-ce-expanding-icon",L:IZ(b.iconUrl)}]},c=new g.U(c)}b.g&&g.K(c.element,"ytp-ce-placeholder");return c},HZ=function(a){if(a.Xu)var b=a.Xu.thumbnails;
return IZ(b?b[b.length-1].url:null)},IZ=function(a){return a?{style:"background-image: url("+a+")"}:{}},pna=function(a,b,c){function d(){k(1)}
function e(){k(-1)}
b.da("mouseenter",(0,g.z)(a.Nq,a,b,c));b.da("mouseleave",(0,g.z)(a.Hr,a,b,c));g.W(a.player).g||b.da("click",(0,g.z)(function(l){g.K(l.element,"ytp-ce-element-hover")},a,b));
b.da("click",(0,g.z)(a.ty,a,c));b.da("keypress",(0,g.z)(a.ty,a,c));b.da("focus",(0,g.z)(function(l,m){this.Nq(l,m)},a,b,c));
b.da("blur",(0,g.z)(function(l,m){this.Hr(l,m)},a,b,c));
b.da("touchstart",(0,g.z)(a.Nq,a,b,c));var f=g.Gd("ytp-ce-expanding-overlay-hider",b.element);f&&b.K(f,"touchstart",function(l){l=l||window.event;l.cancelBubble=!0;l.stopPropagation&&l.stopPropagation();g.Vn(b.element,"ytp-ce-element-hover");g.Vn(b.element,"ytp-ce-force-expand")});
b.da("keydown",(0,g.z)(function(l,m){this.jA=9==m.keyCode&&!m.shiftKey},a,b));
var k=(0,g.z)(function(l,m,n){this.D+=n;0<this.D?(g.K(l.element,"ytp-ce-force-expand"),JZ(this,m.id,!0)):(g.Vn(l.element,"ytp-ce-force-expand"),g.Vn(l.element,"ytp-ce-element-hover"),JZ(this,m.id,!1))},a,b,c);
a=(0,g.z)(function(l,m){m&&(l.da("blur",function(){VY(m)&&this.jA&&m.focus()}),l.K(m,"focus",d),l.K(m,"blur",e))},a,b);
a(g.Gd("ytp-sb-subscribe",b.element));a(g.Gd("ytp-sb-unsubscribe",b.element));b.da("focus",d);b.da("blur",e)},JZ=function(a,b,c){a.l&&(c?a.A.show():a.A.hide());
for(var d in a.g)d!=b&&g.M(a.g[d].element,"ytp-ce-element-shadow-show",c)},KZ=function(a,b,c){function d(){f||(e++,e==b.length&&(k.stop(),c&&c()))}
if(!b||FZ(g.W(a.player).playerStyle))c&&c();else{b=qna(a,b);var e=0,f=!1,k=new g.N(function(){f=!0;c&&c()},1E3,a);
k.start();for(a=0;a<b.length;a++)g.Rq(b[a],d)}},LZ=function(a,b,c){KZ(a,b.clickUrls,c);
(a=g.Us())&&b.fm&&g.Hs(a,b.visualElement)},qna=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce,d=a.player.getCurrentTime().toFixed(2);
c={CPN:c,AD_CPN:c,MT:d};d=[];for(var e=0;e<b.length;e++)d.push(rna(b[e],c));return d},rna=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(c){var d=unescape(c);
d=d.substring(1,d.length-1);return b[d]?escape(b[d]):c})},MZ=function(a){return g.Ja(a)&&a.length?a[0]:a},NZ=function(a){var b=/.+/;
return g.v(a)&&null!=b&&null!=a&&a.match(b)?a:""},OZ=function(a,b){if(null==a)return b;
var c=parseInt(a,0);if(isNaN(c))return b;c=c.toString(16);return"#"+"000000".substring(0,6-c.length)+c},PZ=function(a){return g.v(a)?a:""},QZ=function(a,b,c){for(var d in b)if(b[d]==a)return a;
return c},RZ=function(a,b){return"true"==a||"false"==a?"true"==a:b},SZ=function(a,b){return g.v(a)?parseFloat(a):b},TZ=function(a,b,c,d,e){a=parseFloat(a);
if(null!=a&&!isNaN(a)){if(d)return g.pd(a,b,c);if(a>=b&&a<=c)return a}return e},sna=function(a){if(null==a)return 0;
if("never"==a)return-1;a=a.split(":");if(3<a.length)return 0;var b=0,c=1;(0,g.B)(a,function(d){d=parseFloat(d);0>d&&(c=-c);b=60*b+Math.abs(d)});
return c*b},UZ=function(a,b){if(null==a)return null;
if(g.La(a)){var c=[];(0,g.B)(a,function(e){(e=b(e))&&c.push(e)});
return c}var d=b(a);return d?[d]:[]},tna=function(a){function b(c){return null!=c&&!isNaN(c)}
return(a=a?new g.fh(parseFloat(a.top),parseFloat(a.right),parseFloat(a.bottom),parseFloat(a.left)):null)&&b(a.top)&&b(a.right)&&b(a.bottom)&&b(a.left)?a:null},una=function(a){function b(c){return(0,g.Xd)(c.split(/ +/),function(d){return""!=d})}
return null==a?[]:b(a)},vna=function(a){this.externalId=a},wna=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.g=d},VZ=function(a){if(!a)return null;
var b=g.Vc(PZ(a.value));b=g.Sc(b);if(!b)return null;var c=QZ(a.target,xna,"current");return null==c?null:new wna(b,c,RZ(a.show_link_icon,!0),null!=a.pause_on_navigation?a.pause_on_navigation:!0)},WZ=function(a){return a.value?a.value:null},yna=function(a,b,c,d){this.type=a;
this.trigger=b;this.url=c;this.subscribeData=d},Bna=function(a){if(!a)return null;
var b=QZ(a.type,zna),c=QZ(a.trigger,Ana),d=MZ(a.url);d=VZ(d?d:null);a=MZ(a.subscribeData);var e=a?a:null;e?(a=PZ(e.external_user_id),e=PZ(e.subscription_token),a=a&&e?new vna(a):null):a=null;return b?new yna(b,c,d,a):null},XZ=function(a,b,c){var d=(c="xx"==c||"xy"==c)?640:360;
return(d+((c?a.width:a.height)-d)*b)/d},YZ=function(a,b,c){var d=(c="xy"==c||"yy"==c)?360:640;
return(d+((c?a.height:a.width)-d)*b)/d},ZZ=function(a,b,c,d,e,f,k,l,m,n,p){this.x=a;
this.y=b;this.Hi=c;this.l=d;this.t=e;this.u=f;this.A=k;this.B=l;this.o=m;this.i=n;this.g=p},$Z=function(a,b){if(!a)return null;
var c=SZ(a.x,0),d=SZ(a.y,0),e=SZ(a.w,0),f=SZ(a.h,0),k=sna(a.t),l=SZ(a.d,0),m=SZ(a.px,0),n=SZ(a.py,0),p=SZ(a.scaleSlope,1),r=SZ(a.scaleSlopeX,p);p=SZ(a.scaleSlopeY,p);var u=QZ(a.scaleDimension,Cna,"xy");return b(c,d,e,f,k,l,m,n,r,p,u)},c_=function(a,b){var c=a_(b,b_(a,new g.ih(a.x,a.y,a.Hi,a.l),b.g)),d=b.g,e=c.clone();
d&&!d.contains(c)&&(c.width<d.width?e.left=g.pd(c.left,d.left,d.left+d.width-c.width):(e.left=d.left,e.width=d.width),c.height<d.height?e.top=g.pd(c.top,d.top,d.top+d.height-c.height):(e.top=d.top,e.height=d.height));return e},b_=function(a,b,c){var d=a.A,e=a.B,f=a.g?a.g:"xy",k=XZ(c,a.o,f);
a=YZ(c,a.i,f);f=640*b.width*k/100;var l=360*b.height*a/100;return new g.ih(0==d?640*b.left*k/100:0<d?d:c.width+d-f,0==e?360*b.top*a/100:0<e?e:c.height+e-l,f,l)},d_=function(a){return a?$Z(a,function(b,c,d,e,f,k,l,m,n,p,r){return new ZZ(b,c,d,e,f,k,l,m,n,p,r)}):null},e_=function(a,b){this.g=a;
this.i=b||null},a_=function(a,b){var c=a.i?c_(a.i,new e_(a.g)):a.g;
var d=b.clone(),e=c.left;c=c.top;e instanceof g.td?(d.left+=e.x,d.top+=e.y):(d.left+=e,g.Ea(c)&&(d.top+=c));return d},f_=function(a,b,c,d,e,f,k,l,m,n,p,r,u){ZZ.call(this,a,b,c,d,e,l,m,n,p,r,u);
this.D=f;this.F=k},Dna=function(a){if(!a)return null;
var b=SZ(a.sx,0),c=SZ(a.sy,0);return $Z(a,function(d,e,f,k,l,m,n,p,r,u,y){return new f_(d,e,f,k,l,b,c,m,n,p,r,u,y)})},Ena=function(a,b,c,d,e,f,k,l,m,n,p,r,u,y){this.i=a;
this.bgColor=b;this.borderColor=c;this.borderWidth=d;this.g=e;this.A=f;this.l=k;this.textAlign=l;this.textSize=m;this.o=n;this.padding=p;this.effects=r;this.cornerRadius=u;this.u=y},g_=function(a){if(!a)return null;
var b=OZ(a.fgColor,"#1A1A1A"),c=OZ(a.bgColor,"#FFF"),d=OZ(a.borderColor,"#000"),e=TZ(a.borderWidth,0,5,!1,0),f=TZ(a.bgAlpha,0,1,!1,.8),k=OZ(a.highlightFontColor,"#F2F2F2"),l=TZ(a.highlightWidth,0,5,!1,3),m=PZ(a.textAlign),n=TZ(a.textSize,3.3,30.1,!0,3.6107),p=PZ(a.fontWeight),r=tna(a.padding),u=una(a.effects),y=TZ(a.cornerRadius,0,10,!0,0);a=MZ(a.gradient);if(a=a?a:null){var D=TZ(a.x1,0,100,!0,0),F=TZ(a.y1,0,100,!0,0),E=TZ(a.x2,0,100,!0,100),L=TZ(a.y2,0,100,!0,100),O=OZ(a.color1,"#FFF"),pa=OZ(a.color2,
"#000");a=new Fna(D,F,E,L,O,pa,TZ(a.opacity1,0,100,!0,100),TZ(a.opacity2,0,100,!0,0))}else a=null;return new Ena(b,c,d,e,f,k,l,m,n,p,r,u,y,a)},Fna=function(a,b,c,d,e,f,k,l){this.l=a;
this.u=b;this.o=c;this.A=d;this.g=e;this.i=f;this.B=k;this.D=l},Gna=function(a,b,c,d){this.type=a;
this.i=b;this.g=c;this.l=d},Ina=function(a){if(!a)return null;
var b=QZ(a.type,Hna,"rect"),c=UZ(a.rectRegion,d_),d=UZ(a.anchoredRegion,Dna);a=UZ(a.shapelessRegion,d_);return new Gna(b,c,d,a)},h_=function(a){return a.i&&a.i.length?a.i[0]:a.g&&a.g.length?a.g[0]:a.l&&a.l.length?a.l[0]:null},Jna=function(a,b){this.i=a;
this.g=b},Kna=function(a,b){this.state=a;
this.ref=b},i_=function(a){if(!a)return null;
var b=QZ(a.state,Lna);a=NZ(a.ref);return b?new Kna(b,a):null},Mna=function(a,b,c,d){this.g=a||[];
this.l=b||[];this.o=c;this.i=d;this.value=!1},Nna=function(a){if(!a)return null;
var b=UZ(a.condition,i_),c=UZ(a.notCondition,i_),d=RZ(a.show_delay,!1);a=RZ(a.hide_delay,!1);return b||c?new Mna(b,c,d,a):null},Ona=function(a,b,c){(0,g.B)(a.g,g.Qa(b,!1),c);
(0,g.B)(a.l,g.Qa(b,!0),c)},j_=function(a,b,c,d,e,f,k,l,m,n,p,r,u,y){this.id=a;
this.author=b;this.type=c;this.style=d;this.o=e;this.segment=f;this.l=k||[];this.B=l||[];this.i=m;this.A=n;this.u=p;this.data=r;this.g=u;this.itct=y},Rna=function(a){if(!a)return null;
var b=NZ(a.id),c=NZ(a.author),d=QZ(a.type,Pna),e=QZ(a.style,k_),f=PZ(MZ(a.TEXT)),k=PZ(a.data);k=0!=k.length?JSON.parse(k):{};var l=MZ(a.segment);var m=l?l:null;m?(NZ(m.timeRelative),l=NZ(m.spaceRelative),l=(m=UZ(m.movingRegion,Ina))?new Jna(l,m):null):l=null;m=UZ(a.action,Bna);var n=UZ(a.trigger,Nna),p=MZ(a.appearance);(p=g_(p?p:null))||(p=g_({}));var r=QZ(a.coordinate_system,Qna,"video_relative"),u=RZ(a.closeable,!0),y=PZ(a.log_data);a=PZ(a.itct);return b&&d?new j_(b,c,d,e,f,l,m,n,p,r,u,k,y,a):null},
m_=function(a){return l_(a,function(b){return"click"==b.trigger})},l_=function(a,b){return(0,g.Mj)(a.l,b,void 0)},Sna=function(a,b,c){(0,g.B)(a.l,b,c)},Tna=function(a,b){return g.Wa(a.l,b,void 0)},n_=function(a,b,c){(0,g.B)(a.B,b,c)},Una=function(a,b){(0,g.G)(a.B,b,void 0)},p_=function(a){return(a=o_(a))?h_(a):null},o_=function(a){a.segment?(a=a.segment,a=a.g.length?a.g[0]:null):a=null;
return a},q_=function(a,b){var c=p_(a);
return c&&b?YZ(b,c.i,c.g?c.g:"xy"):1},s_=function(a,b,c){this.g={};
this.l=!1;this.u="ivTrigger:"+a;this.i=c;Ona(b,function(d,e){var f=r_(e.state,e.ref);this.i.subscribe(f,(0,g.z)(this.o,this,f,d));this.g[f]=d},this)},r_=function(a,b){var c="ivTriggerCondition:"+a;
return b?c+":"+b:c},t_=function(){this.g=!1;
this.u=this.i=null},u_=function(a,b,c){a.i?(a.i.setSize(b,c),a.i.clear()):(b=new zZ(b,c,void 0,void 0,void 0),a.i=b,a.i.Op(),a.u=g.Qd("DIV"),a.u.appendChild(a.i.ka()));
return a.i},v_=function(a,b,c){var d=document.createElementNS("http://www.w3.org/2000/svg",a);
b&&g.Jb(b,function(f,k){d.setAttribute(k,f)});
for(var e=2;e<arguments.length;e++)d.appendChild(arguments[e]);return d},w_=function(a,b){var c=g.io(g.ho.getInstance());
b.setAttribute("result",c);a.appendChild(b);return c},Vna=function(a,b){var c=w_(a,v_("feGaussianBlur",{"in":b,
stdDeviation:"1.8"}));c=w_(a,v_("feDiffuseLighting",{"in":c,surfaceScale:"4",diffuseConstant:"1"},v_("feDistantLight",{azimuth:"270",elevation:"15","lighting-color":"white"})));c=w_(a,v_("feComposite",{"in":c,in2:b,operator:"in"}));return w_(a,v_("feComposite",{in2:c,"in":b,operator:"arithmetic",k2:1,k3:.5,k4:0}))},Wna=function(a,b){var c=w_(a,v_("feOffset",{"in":b,
dx:"-7",dy:"-7"}));c=w_(a,v_("feGaussianBlur",{"in":c,stdDeviation:"3"}));c=w_(a,v_("feColorMatrix",{"in":c,type:"matrix",values:"0 0 0 0 0  0 0 0 0 0  0 0 0 0 0  0 0 0 0.5 0"}));var d=w_(a,v_("feColorMatrix",{"in":b,type:"matrix",values:"0 0 0 0 0  0 0 0 0 0  0 0 0 0 0  0 0 0 100 0"}));d=w_(a,v_("feGaussianBlur",{"in":d,stdDeviation:"1"}));c=w_(a,v_("feComposite",{operator:"out","in":c,in2:d}));return w_(a,v_("feComposite",{operator:"over","in":b,in2:c}))},Xna=function(a,b){return b},Yna=function(a){var b=
v_("filter",{filterUnits:"userSpaceOnUse"}),c="SourceGraphic";
(0,g.B)(a,function(d){a:{switch(d){case "bevel":d=Vna;break a;case "dropshadow":d=Wna;break a}d=Xna}c=d(b,c)});
return b},Zna=function(a){a=(0,g.Xd)(a,function(b){return b in x_});
g.pb(a,function(b,c){return x_[b]-x_[c]});
return a},$na=function(a){return g.Wa(a,function(b){return"dropshadow"==b})?new g.fh(0,7,7,0):new g.fh(0,0,0,0)},y_=function(a,b,c){var d=new sZ;
d.moveTo(a.left+b+c,a.top+c);d.Zb(a.left+a.width-b-c,a.top+c);tZ(d,b,b,-90);d.Zb(a.left+a.width-c,a.top+a.height-b-c);tZ(d,b,b,0);d.Zb(a.left+b+c,a.top+a.height-c);tZ(d,b,b,90);d.Zb(a.left+c,a.top+b+c);tZ(d,b,b,180);d.close();return d},z_=function(a,b,c,d){var e=a.u;
e?a=new mZ(e.l*b/100,e.u*c/100,e.o*b/100,e.A*c/100,e.g,e.i,e.B,e.D):(b=a.g,a=new lZ(a.bgColor,d?Math.max(b,.9):b));return a},A_=function(a,b){var c=g.jh(a),d=$na(b);
g.Na(d)?(c.top-=d.top,c.right+=d.right,c.bottom+=d.bottom,c.left-=d.left):(c.top-=d,c.right+=Number(void 0),c.bottom+=Number(void 0),c.left-=Number(void 0));return new g.ih(c.left,c.top,c.right-c.left,c.bottom-c.top)},B_=function(a,b,c){if(c.length&&(b=g.Ed(document,"g",void 0,b),b.length)){var d=Zna(c);
if(d){c="effects:"+(d?d.join("|"):"");var e=c in a.g?a.g[c]:null;e?a=e:(d=Yna(d),a=0<d.childNodes.length?oZ(a,c,d):null)}else a=null;a&&b[0].setAttribute("filter","url(#"+a+")")}},C_=function(){t_.call(this);
this.o=0},aoa=function(a,b){var c=a.top-b.y,d=b.x-a.left-a.width,e=b.y-a.top-a.height,f=a.left-b.x,k=Math.max(c,d,e,f);
if(0>k)return"i";switch(k){case c:return"t";case d:return"r";case e:return"b";case f:return"l"}return"i"},D_=function(a){t_.apply(this,arguments)},E_=function(a){t_.apply(this,arguments)},F_=function(a){C_.apply(this,arguments)},G_=function(a,b,c,d,e){g.H.call(this);
this.g=a;this.R=b;this.A=c;this.X=d;this.Y=e;this.F=!1;this.ca=new gZ(this);g.I(this,this.ca);this.M=this.u=this.B=this.P=this.i=null;this.V=!1;this.aa=this.H=this.I=null;this.Tm=new g.wl(this.WC,100,this);g.I(this,this.Tm);this.D=new g.N(this.gw,500,this);g.I(this,this.D);this.O=this.l=this.o=null},boa=function(a,b){var c=(0,g.z)(function(d,e,f){e=f?H_(this,e,(0,g.z)(f,this)):H_(this,e);
this.ca.da(b,d,e)},a);
c("mouseover","G",a.gx);c("mouseout","F",a.qg);c("click","D");c("touchend","D")},coa=function(a){if(a.g.u){if(l_(a.g,function(d){return"close"==d.type}))var b=a.i;
else a.o=g.Qd("DIV","annotation-close-button"),g.Oh(a.o,!1),g.Dp(a.o,"annotation_id",a.g.id),a.i.appendChild(a.o),b=a.o;var c=function(d){d.stopPropagation()};
a.ca.da(b,"click",H_(a,"E",c));a.ca.da(b,"touchend",H_(a,"E",c))}},H_=function(a,b,c){return(0,g.z)(function(d){if(this.Y)c&&c(d);
else if(d.event.target instanceof Element){var e=d.event.target;g.Oh(e,!1);try{var f=document.elementFromPoint(d.event.clientX,d.event.clientY);if(g.ge(f,null,"annotation",void 0)){var k=document.createEvent("MouseEvent");k.initMouseEvent(d.event.type,d.event.bubbles,d.event.cancelable,d.event.view,d.event.detail,d.event.screenX,d.event.screenY,d.event.clientX,d.event.clientY,d.event.ctrlKey,d.event.altKey,d.event.shiftKey,d.event.metaKey,d.event.button,d.event.relatedTarget);f.dispatchEvent(k)}}finally{g.Oh(e,
!0)}}e=TY(d.target);d=new g.td(d.clientX,d.clientY);"F"==b&&e.contains(d)||this.X.N(b,this.g)},a)},K_=function(a){if(a.i||a.l){var b=p_(a.g);
if(b){var c=I_(a);if(a.i){b=c_(b,c);var d=g.pJ(a.A).getVideoContentRect();g.Mh(a.i,b.width,b.height);g.Ch(a.i,b.left,b.top);a.P=new g.ih(d.left+b.left,d.top+b.top,b.width,b.height);var e=(e=p_(a.g))&&d?XZ(d,e.o,e.g?e.g:"xy"):1;var f=q_(a.g,d);d=a.g.i;d.padding?d=d.padding:(d="speech"==a.g.style?1.6:.8,d=new g.fh(d,d,d,d));d=new g.fh(360*d.top*f/100,640*d.right*e/100,360*d.bottom*f/100,640*d.left*e/100);a.u&&(d.right+=1.5*c.g.height/100);a.i.style.padding=d.top+"px "+d.right+"px "+d.bottom+"px "+d.left+
"px";"label"==a.g.style&&a.B&&(a.B.style.padding=a.i.style.padding);d=c.g;var k=!1,l=0,m=0;var n=g.pJ(a.A).getVideoContentRect();var p=g.wJ(a.A);g.kh(n,p)?n=null:(p.top+=20,p.height-=40,"player_relative"!=a.g.A&&(p.left-=n.left,p.top-=n.top),n=p);n&&(l=n.top-(b.top+b.height),m=b.top-(n.top+n.height),k=0<l||0<m);if(k&&n){d=l;e=m;if(a.u){f=J_(a,23,b,d,e);if(a.o){var r=43-f.width;0<r&&(b.left+f.left-r>n.left&&(f.left-=r),f.width+=r)}r=f;g.Mh(a.u,f.width,f.height);g.Ch(a.u,f.left,f.top)}a.o&&(r?b=new g.td(r.left+
r.width-23-18,a.V?r.top+2:r.top+r.height-18-2):(r=J_(a,18,b,d,e),b=new g.td(r.left,r.top),g.Mh(a.o,r.width,r.height)),g.Ch(a.o,b));a.M=new g.ih(a.P.left+r.left,a.P.top+r.top,r.width,r.height);a.I=a.ca.da(g.pJ(a.A),"mousemove",a.gF,a)}else a.u&&(r=e/f*d.height*4.2/100,r=new g.vd(r,r),"highlight"==a.g.type||"label"==a.g.style?(e=1.5*d.height/100,r=new g.ih(b.width-r.width-e,b.height-r.height-e,r.width,r.height)):r=new g.ih(b.width-r.width-3*d.height/100,(b.height-r.height)/2,r.width,r.height),g.Mh(a.u,
r.width,r.height),g.Ch(a.u,r.left,r.top)),a.o&&(r=9<=d.left+d.width-(b.left+b.width),e=9<=b.top-d.top,g.Ch(a.o,r&&e?new g.td(b.width-9,-9):r?new g.td(b.width-9,45<b.height?9:b.height-9):e?new g.td(45<b.width?b.width-9-18:-9,-9):b.width/d.width>b.height/d.height?new g.td(45<b.width?b.width-9-18:-9,b.height-9):new g.td(-9,45<b.height?9:b.height-9)))}a.l&&a.l.l(a.g,c);if(a.i){c=a.i;b=a.g.i;c.style.color="highlightText"==a.g.style?b.A:b.i;r=g.pJ(a.A).getVideoContentRect();c.style.fontSize=360*b.textSize*
q_(a.g,r)/100+"px";r=a.g.style;c.style.textAlign=b.textAlign?b.textAlign:"title"==r||"highlightText"==r?"center":"left";b.o&&(c.style.fontWeight=b.o);a=a.i;c=a.style.overflow;r=(b=g.Gd("annotation-link-icon",a))?VY(b):!1;e=(d=g.Gd("annotation-close-button",a))?VY(d):!1;r&&g.Oh(b,!1);e&&g.Oh(d,!1);m=f="";if(n=g.Gd("inner-text",a))f=n.style.overflow,m=n.style.position,n.style.overflow="visible",n.style.position="static";a.style.overflow="scroll";if(a.scrollHeight>a.offsetHeight||a.scrollWidth>a.offsetWidth){l=
k=bna(a);p=5;for(var u=Math.floor(k/2);u;)a.scrollHeight<=a.offsetHeight&&a.scrollWidth<=a.offsetWidth?(p=l,l=Math.min(l+u,k)):l=Math.max(l-u,p),u=Math.floor(u/2),a.style.fontSize=l+"px";l!=p&&(a.scrollHeight>a.offsetHeight||a.scrollWidth>a.offsetWidth)&&(a.style.fontSize=p+"px")}a.style.overflow=c;n&&(n.style.overflow=f,n.style.position=m);e&&g.Oh(d,!0);r&&g.Oh(b,!0)}}}},J_=function(a,b,c,d,e){var f=0<e;
b=new g.ih(0,c.height-b,Math.max(c.width,b),b);0<d&&(b.top=c.height,20<d&&(b.height+=d-20),g.K(a.i,"annotation-extend-down"));f&&(b.top=-b.height,20<e&&(c=e-20,b.top-=c,b.height+=c),g.K(a.i,"annotation-extend-up"),a.V=!0);return b},L_=function(a){return"label"!=a.g.style||a.l.g},I_=function(a){var b=g.pJ(a.A).getVideoContentRect();
if("player_relative"==a.g.A){var c=g.pJ(a.A).getPlayerSize();b=new g.ih(-b.left,-b.top,c.width,c.height)}else b=new g.ih(0,0,b.width,b.height);return new e_(b,a.O?p_(a.O):null)},M_=function(a,b){return b?new g.ih(a.x+b.left,a.y+b.top,b.width,b.height):null},N_=function(a,b,c){g.H.call(this);
this.i=a;this.annotation=b;this.view=c;this.g=null;this.l=this.isVisible=!1;doa(b,a)},doa=function(a,b){Una(a,function(c){return new s_(a.id,c,b)})},O_=function(a){a.i.unsubscribe("resize",a.fx,a);
a.i.unsubscribe("onVideoAreaChange",a.Ty,a)},P_=function(a){a.g&&(a.g.stop(),a.g=null)},Q_=function(a,b,c){jZ.call(this,a,b,c);
this.channelId=b.channel_id;this.customMessage=b.custom_message;this.profileImageUrl=b.image_url;this.title=b.title;this.metaInfo=b.meta_info;this.url=VZ({pause_on_navigation:b.pause_on_navigation,target:b.target||"new",value:b.url})},R_=function(a,b,c){jZ.call(this,a,b,c);
this.imageUrl=b.image_url;this.displayDomain=b.display_domain;this.showLinkIcon=b.show_link_icon;this.o=b.button_icon_url;this.title=b.title;this.customMessage=b.custom_message;this.url=VZ({pause_on_navigation:b.pause_on_navigation,target:b.target||"new",value:b.url});this.g=null;if(a=b.signin_url)this.g=VZ({target:"current",value:a});this.I=b.signin_title||null;this.H=b.signin_message||null},S_=function(a,b,c){R_.call(this,a,b,c);
this.F=b.ypc_flow_type;this.B=b.innertube_request_params},T_=function(a,b,c){jZ.call(this,a,b,c);
this.o=b.image_url;this.playlistVideoCount=b.playlist_video_count;this.customMessage=b.custom_message;this.title=b.title;this.metaInfo=b.meta_info;this.url=VZ({pause_on_navigation:b.pause_on_navigation,target:b.target||"new",value:b.url})},U_=function(a,b,c){jZ.call(this,a,b,c);
this.B=this.id.replace(/[^a-z0-9-]/gi,"-");this.title=b.title;this.choices=b.choices;this.g=b.hasOwnProperty("old_vote")?b.old_vote:null;this.o=null;if(a=b.signin_url)this.o=VZ({target:"current",value:a});this.F=b.hasOwnProperty("xsrf_token")?b.xsrf_token:null},V_=function(a,b,c){R_.call(this,a,b,c);
this.offers=[];a=b.offers||[];for(b=0;b<a.length;b++)this.offers.push(new eoa(a[b]))},eoa=function(a){this.merchant=g.pc(a.merchant);
this.price=g.pc(a.price)},W_=function(a,b,c){R_.call(this,a,b,c);
this.P=b.ypc_item_type;this.F=b.ypc_item_id;this.B=b.ypc_flow_type},X_=function(a,b,c){jZ.call(this,a,b,c);
this.o=b.image_url;this.videoDuration=b.video_duration||null;this.customMessage=b.custom_message;this.title=b.title;this.metaInfo=b.meta_info;this.isLiveNow=!!b.is_live_now;this.url=VZ({pause_on_navigation:b.pause_on_navigation,target:b.target||"new",value:b.url})},Y_=function(a,b,c){jZ.call(this,a,b,c);
this.F=b.image_url;this.o=b.badge_symbol||"";this.priceText=b.price_text||"";this.title=b.title;this.metaInfo=b.meta_info;this.B=!!b.is_paygated;this.H=!!b.user_has_entitlement;this.url=VZ({target:b.target||"new",value:b.url})},foa=function(a){this.g=a;
this.i={}},goa=function(a){var b={};
b=(b["iv-event"]=1,b);g.vJ(a.g,"iv",b,void 0)},b0=function(a,b,c,d){if(b){var e=Z_(a,b);
a.i[b]=e["p-time"];e["iv-event"]=e.link||e["l-class"]||e["link-id"]?2:7;b=$_(a,"cta_annotation_shown",e,c);a0(a,e,hoa(b,d))}},c0=function(a,b,c,d,e,f){if(b){var k=Z_(a,b);
k["iv-event"]=3;k["i-time"]=a.i[b]||"";d&&g.dc(k,d);b=$_(a,"cta_annotation_clicked",k,e);a0(a,k,b,c,f)}},d0=function(a,b){if(b){var c=Z_(a,b);
c["iv-event"]=4;c["i-time"]=a.i[b]||"";var d=$_(a,"cta_annotation_closed",c);a0(a,c,d)}},hoa=function(a,b){return b?(0,g.G)(a,g.Qa(function(c,d){return g.dn(d,c)},b)):a},$_=function(a,b,c,d){d=d?g.fb(d):[];
var e=c["a-type"];if(30==e||31==e&&g.R(g.W(a.g).experiments,"enable_async_click_tracking")){a:{c=c["a-id"];a=a.g.getVideoData();if(a.ju){if((b=a.ju[b])&&g.Su(b)){a=g.jc("[ANNOTATION_ID]");0<=b.indexOf("[ANNOTATION_ID]")?b=b.replace("[ANNOTATION_ID]",c):0<=b.indexOf(a)&&(b=b.replace(a,c));break a}}else if(a.kn){b=g.eq(a.kn,{label:b,value:"a_id="+c});break a}b=""}b&&d.push(b)}return d},a0=function(a,b,c,d,e){var f=1,k=-1;
if(d){var l=!1;var m=function(){f--;f||l||(clearTimeout(k),l=!0,d())};
k=setTimeout(function(){l=!0;d()},1E3)}(0,g.B)(c||[],function(n){f++;
g.Rq(n,m)});
e&&(f++,0!=e&&a.g.sendVideoStatsEngageEvent(e,m));g.vJ(a.g,"iv",b,m)},Z_=function(a,b){var c={};
if(b){var d=new g.Tm(b);(0,g.B)(d.Dd(),function(e){c[e]=escape(d.get(e,""))})}c["p-time"]=a.g.getCurrentTime().toFixed(2);
c.ps=g.W(a.g).playerStyle;return c},e0=function(a,b,c,d,e){e=Z_(a,e);
e["iv-event"]=c;b&&(e.ei=b);e["a-id"]||(e["a-id"]="card:drawer");e["a-type"]=51;a0(a,e,d)},f0=function(a,b,c,d){c&&(c=Z_(a,c),c["iv-event"]=b,a0(a,c,d))},ioa=function(a,b,c,d,e,f,k){this.g=a;
this.l=b;this.rb=c;this.videoData=d;this.logger=e;this.Z=f;this.i=k},g0=function(a,b,c){this.g=a;
this.o=b;this.u=c;this.i=new g.On},joa=function(a,b){var c=[];
(0,g.B)(b.choices,function(k){c.push({C:"li",G:b.B+"-"+k.index.toString(),J:[{C:"label",J:[{C:"input",G:"iv-card-poll-choice-input",L:{type:"checkbox",role:"radio",name:b.B+k.index.toString(),value:k.index.toString(),"data-poll-choice-index":k.index.toString()}},{C:"span",G:"iv-card-poll-choice-text",J:[{C:"span",G:"iv-card-poll-choice-percent"},h0(this,"span",void 0,k.desc)]}]},{C:"div",G:"iv-card-poll-result",J:[{C:"div",G:"iv-card-poll-result-bar"}]}]})},a);
var d={C:"ul",L:{role:"radiogroup"},J:c},e={};b.o&&(e["aria-label"]=g.FM("$POLL_TITLE - Sign in to vote.",{POLL_TITLE:b.title}));var f=["iv-card","iv-card-poll"];d=[{C:"div",G:"iv-card-content",J:[h0(a,"h2",e,b.title),{C:"form",J:[{C:"fieldset",J:[d]}]}]}];b.o&&(f.push("iv-card-unavailable"),d.push({C:"div",W:["iv-card-sign-in"],J:[{C:"h2",U:"Want to vote?"},{C:"a",W:["iv-card-sign-in-button","iv-button"],L:{href:WZ(b.o)},J:[{C:"span",W:["iv-button-content"],U:"Sign in"}]}]}));f=new g.U({C:"div",
W:f,J:d});d=f.element;i0(b,d);gna(a.g.g,d,g.Qa(a.B,b),a);(0,g.B)(g.Fd("iv-card-poll-choice-input",d),function(k){this.g.g.da(k,"focus",g.Qa(this.l,!0));this.g.g.da(k,"blur",g.Qa(this.l,!1))},a);
b.o&&(d=g.Gd("iv-card-sign-in-button",d),a.o(d,b.o,b.id,b.Wc,b.l,b.i.click,5));return f},m0=function(a,b,c,d){var e=b.displayDomain?{C:"div",
G:"iv-card-image-text",U:b.displayDomain}:"",f=j0(a,b),k=["iv-card"];b.g&&k.push("iv-card-unavailable");e=[{C:"a",G:"iv-click-target",L:{href:WZ(b.url)},J:[k0(b.imageUrl,e),{C:"div",G:"iv-card-content",J:[h0(a,"h2",void 0,b.title),f]}]}];b.g&&e.push({C:"div",W:["iv-card-sign-in"],J:[h0(a,"h2",void 0,b.I||""),{C:"p",U:b.H},{C:"a",W:["iv-card-sign-in-button","iv-button"],L:{href:WZ(b.g)},J:[h0(a,"span","iv-button-content","Sign in")]}]});k=new g.U({C:"div",W:k,J:e});l0(a,k,b,c,d);return k},o0=function(a,
b,c){var d=["yt-badge",
"standalone-ypc-badge-renderer-icon",b.H?"standalone-ypc-badge-renderer-icon-purchased":"standalone-ypc-badge-renderer-icon-available"],e={};d=b.B&&b.o?{C:"span",W:d,L:e,U:b.o}:"";c={C:"div",W:["iv-card",c],J:[{C:"a",G:"iv-click-target",L:{href:WZ(b.url)},J:[k0(b.F,d?{C:"div",G:"iv-card-image-text",J:[d,b.priceText]}:""),{C:"div",G:"iv-card-content",J:[{C:"h2",G:"iv-card-primary-link",U:b.title},n0(a,b)]}]}]};c=new g.U(c);l0(a,c,b);return c},p0=function(a,b){return b.customMessage?h0(a,"div","iv-card-message",
b.customMessage):""},k0=function(a,b){var c="background-image: url("+a+");",d=[];
b&&d.push(b);return{C:"div",G:"iv-card-image",L:{style:c},J:d}},n0=function(a,b){if(!b.metaInfo||0==b.metaInfo.length)return"";
var c=[];(0,g.B)(b.metaInfo,function(d){c.push(h0(this,"li","",d))},a);
return{C:"ul",G:"iv-card-meta-info",J:c}},h0=function(a,b,c,d){c?g.v(c)?c={"class":c}:g.Ja(c)&&(c={"class":c.join(" ")}):c={};
c.dir=g.Pn(a.i,d);return{C:b,L:c,U:d}},j0=function(a,b){if(!b.customMessage)return"";
var c=["iv-card-action","iv-card-primary-link"],d={};b.o&&(c.push("iv-card-action-icon"),d.style="background-image: url("+b.o+");");d.dir=g.Pn(a.i,b.customMessage);var e=[{C:"span",U:b.customMessage}];b.showLinkIcon&&(e.push("\u00a0"),e.push({C:"span",G:"iv-card-link-icon"}));return{C:"div",W:c,L:d,J:e}},i0=function(a,b){var c=0;
(0,g.B)(a.choices,function(m){c+=m.count});
c=c||1;for(var d=0;d<a.choices.length;d++){var e=a.choices[d],f=g.Gd(a.B+"-"+e.index.toString(),b);e=e.count/c;null==a.g&&(e=0);g.M(f.getElementsByTagName("label")[0],"iv-card-poll-choice-checked",a.g==d);f.getElementsByTagName("input")[0].checked=a.g==d;var k=Math.floor(100*e).toFixed(0),l=g.Gd("iv-card-poll-choice-percent",f);g.ae(l,g.FM("$PERCENT%",{PERCENT:k}));f=g.Gd("iv-card-poll-result-bar",f);g.uh(f,"transform","scaleX("+e.toFixed(2)+")")}g.M(b,"iv-card-poll-voted",null!=a.g);g.M(b,"iv-card-poll-expanded",
null!=a.g&&1<a.choices.length)},q0=function(a,b,c,d){d?(c&&a.g.videoData.sa||a.g.Z.pauseVideo(),a.g.Z.isFullscreen()&&a.g.Z.toggleFullscreen(),c0(a.g.logger,b.l,d,void 0,b.i.click,5),(a=g.Us())&&g.Hs(a,b.A)):b.url&&a.u(b.url,b.id,b.Wc,b.l,b.i.click||[],5)},l0=function(a,b,c,d,e){c.g&&r0(a,g.Fd("iv-card-sign-in-button",b.element),c,c.g,e);
c.url&&r0(a,g.Fd("iv-click-target",b.element),c,c.url,d)},r0=function(a,b,c,d,e){(0,g.B)(b,function(f){if(e){var k=(0,g.z)(function(l){l.stopPropagation();
l.preventDefault();e();return!1},this);
this.g.g.da(f,"click",k)}else d&&this.o(f,d,c.id,c.Wc,c.l,c.i.click,5)},a)},s0=function(a){var b=0;
-1!=a.indexOf("h")&&(a=a.split("h"),b=3600*a[0],a=a[1]);-1!=a.indexOf("m")&&(a=a.split("m"),b=60*a[0]+b,a=a[1]);-1!=a.indexOf("s")?(a=a.split("s"),b=1*a[0]+b):b=1*a+b;return b},u0=function(a){var b;
(b=a)&&!(b=1<a.length?"/"==a.charAt(0)&&"/"!=a.charAt(1):"/"==a)&&(b=t0(a),b="com"==b[0]&&"youtube"==b[1]||"be"==b[0]&&"youtu"==b[1]);return b?-1==a.indexOf("/redirect?"):!1},t0=function(a){a=a.replace(/^(https?:)?\/\//,"");
a=a.split("/",1);return!a||1>a.length||!a[0]?[]:a[0].toLowerCase().split(".").reverse()},koa=function(a){a=WZ(a);
if(!a)return null;a=a.replace(/https?:\/\//g,"");var b;(b=!u0(a))||(b=g.Ng(g.Mg(a)[5]||null)||"",b=b.split("/"),b="/"+(1<b.length?b[1]:""),b="/watch"!=b);if(b)return null;b=g.cq(a);if(!b||!b.v)return null;if(b=b.t)return s0(b);a=a.split("#",2);return!a||2>a.length?null:(a=g.aq(a[1]))&&a.t?s0(a.t):-1},v0=function(a){a=WZ(a);
a=a.replace(/https?:\/\//g,"");return u0(a)?(a=g.cq(a))&&a.v?a.v:null:null},loa=function(a,b,c){c=c.replace(/\/(u|b)\/[0-9]+/g,"");
var d=/^[0-9]+$/;a&&d.test(a)&&(c="/b/"+a+c);b&&d.test(b)&&(c="/u/"+b+c);return c},w0=function(a,b){return b?b:u0(a)?"current":"new"},x0=function(a,b){g.H.call(this);
this.Ca=a;this.context=b;this.Us=!1;this.X=0},moa=function(a){return(0,g.C)()-a.X},noa=function(a,b,c,d,e,f){var k=WZ(b);
if(k){var l=w0(k,b.target),m=(0,g.z)(function(){b.g&&this.context.Z.pauseVideo();var p=this.context.videoData.ac||!1,r=g.cq(k||"");p&&r&&(r.v||r.list)?g.sX(this.context.Z.app,r.v,c,r.list,!1,void 0,void 0):g.LK(k||"","current"==l?"_top":void 0,c)},a);
"new"==l&&(m(),m=null);var n={};n.interval=moa(a);c0(a.context.logger,d,m,n,e,f);u0(k)||(a=g.Us(),d=c.itct,a&&d&&g.Hs(a,g.Ds(d)))}},A0=function(a,b,c){x0.call(this,b,c);
var d=this;this.i=a;this.R=null;this.V=this.xa=this.u=this.ua=!1;this.aa=null;this.M=new g.N(g.Ga,c.rb.bd?4E3:3E3);g.I(this,this.M);this.la=new g.N(g.Ga);g.I(this,this.la);this.A=new g0(c,(0,g.z)(this.yi,this),(0,g.z)(this.qm,this));this.F=new g.U({C:"div",G:"iv-drawer",L:{id:"iv-drawer"},J:[{C:"div",G:"iv-drawer-header",L:{"aria-role":"heading"},J:[{C:"span",G:"iv-drawer-header-text"},{C:"button",W:["iv-drawer-close-button","ytp-button"],L:{"aria-label":"Hide cards",tabindex:"0"}}]},{C:"div",G:"iv-drawer-content"}]});
g.I(this,this.F);this.B=this.F.element;this.wa=new g.qP(this.F,330);g.I(this,this.wa);this.ya=g.Gd("iv-drawer-header-text",this.B);this.o=g.Gd("iv-drawer-content",this.B);this.l=[];this.na=this.O=this.D=this.Y=this.g=null;this.I=[];this.addCueRange(0,1E3*c.videoData.lengthSeconds,"",function(){d.xa&&y0(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.xa=d.u)&&z0(d)});
this.P=this.H=this.ba=null},roa=function(a,b){var c=b&&b.data&&b.data.card_type;
if(c&&B0[c]){c=new B0[c](b.id,b.data,b.g);if(!a.ua){g.Un(a.ka(),["html5-stop-propagation","iv-drawer-manager"]);g.FJ(a.i,a.B,5);ooa(a);a.O=g.Gd("ytp-cards-button",a.i.getRootNode());var d=g.Gd("iv-drawer-close-button",a.B);a.na=d;a.ua=!0}C0(a,c.id);var e=poa(a,c);if(e){d={Hb:c,Uo:e.element,Dw:!1};var f=qoa(a,d);g.jb(a.l,f,0,d);e.g(a.o,f);a.sl();c.autoOpen?a.addCueRange(c.startMs,0x8000000000000,c.id,g.Qa(a.IL,d)):(e=1E3*a.context.Z.getCurrentTime(),5E3>e&&e>c.startMs&&a.Pz(d),a.addCueRange(c.startMs,
c.startMs+1,c.id,g.Qa(a.Pz,d)),D0(a))}}},soa=function(a,b){b.data.autoOpenMs&&a.addCueRange(b.data.autoOpenMs,0x8000000000000,"",function(){y0(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
b.data.autoCloseMs&&a.addCueRange(b.data.autoCloseMs,0x8000000000000,"",function(){z0(a)});
var c=b.data.headerText;g.ae(a.ya,c);a.O&&a.O.setAttribute("title",c);b.data.eventId&&(a.R=b.data.eventId);a.ba=g.Ds(b.data.trackingParams);a.P=g.Ds(b.data.closeTrackingParams);a.H=g.Ds(b.data.iconTrackingParams)},C0=function(a,b){var c=toa(a,b);
c&&(c==a.g&&(a.g=null),a.i.removeCueRange(c.Hb.id),g.Wd(c.Uo),g.bb(a.l,c),a.sl(),D0(a))},y0=function(a,b,c,d){if(!a.u){a.wa.show();
a.Y=new g.N(function(){g.K(a.context.Z.getRootNode(),"ytp-iv-drawer-open")},0);
a.Y.start();a.aa=g.vr(a.o,"mousewheel",(0,g.z)(a.IE,a));a.u=!0;a.X=(0,g.C)();e0(a.context.logger,a.R,7,void 0,d&&d.Hb?d.Hb.l:void 0);var e=g.Us();e&&a.ba&&a.P&&hZ(e,[a.ba,a.P]);var f={TRIGGER_TYPE:b};(0,g.B)(a.l,function(k){k.Dw||(k.Dw=!0,b0(a.context.logger,k.Hb.l,k.Hb.i.yD,f));e&&hZ(e,[k.Hb.A])});
SY(a.i);c&&(a.D=new g.N(function(){a.ha=a.O;a.na.focus()},330),a.D.start())}},z0=function(a){a.u&&(a.wa.hide(),g.wr(a.aa),a.aa=null,g.Vn(a.context.Z.getRootNode(),"ytp-iv-drawer-open"),a.u=!1,SY(a.i),a.D&&a.D.stop(),a.D=new g.N(function(){a.ha&&(a.ha.focus(),a.ha=null)},330),a.D.start())},ooa=function(a){var b=g.Gd("iv-drawer-close-button",a.B);
a.context.g.da(b,"click",a.aC,a);a.context.g.da(a.o,"touchend",function(){a.M.start()});
a.context.g.da(a.o,"scroll",a.jC,a);a.context.i.subscribe("onHideControls",function(){a.V=!0});
a.context.i.subscribe("onShowControls",function(){a.V=!1});
a.context.i.subscribe("onVideoAreaChange",function(){a.V=g.Tn(a.i.getRootNode(),"ytp-autohide")});
a.I.push(g.Np("iv-button-shown",a.QD,a));a.I.push(g.Np("iv-button-hidden",a.PD,a));a.I.push(g.Np("iv-teaser-shown",a.TD,a));a.I.push(g.Np("iv-teaser-hidden",a.SD,a));a.I.push(g.Np("iv-teaser-clicked",a.RD,a))},poa=function(a,b){switch(b.type){case "simple":return m0(a.A,b);
case "collaborator":var c=a.A,d={C:"div",W:["iv-card","iv-card-channel"],J:[{C:"a",W:["iv-click-target"],L:{href:WZ(b.url),"data-ytid":b.channelId},J:[k0(b.profileImageUrl),{C:"div",G:"iv-card-content",J:[p0(c,b),{C:"h2",G:"iv-card-primary-link",U:b.title},n0(c,b)]}]}]};d=new g.U(d);l0(c,d,b);return d;case "donation":return c=a.A,d=(0,g.z)(c.A,c,b),m0(c,b,d,d);case "episode":return o0(a.A,b,"iv-card-episode");case "movie":return o0(a.A,b,"iv-card-movie");case "playlist":return c=a.A,d={C:"div",W:["iv-card",
"iv-card-playlist"],J:[{C:"a",G:"iv-click-target",L:{href:WZ(b.url)},J:[k0(b.o,{C:"div",G:"iv-card-image-overlay",J:[{C:"span",G:"iv-card-playlist-video-count",U:b.playlistVideoCount.toString()}]}),{C:"div",G:"iv-card-content",J:[p0(c,b),h0(c,"h2","iv-card-primary-link",b.title),n0(c,b)]}]}]},d=new g.U(d),l0(c,d,b),d;case "poll":return joa(a.A,b);case "productListing":c=a.A;var e=0!=b.offers.length;d=["iv-card"];var f="",k=j0(c,b);e&&(d.push("iv-card-product-listing"),f="iv-card-primary-link",e=b.offers[0],
k=[],e.price&&k.push({C:"div",G:"iv-card-offer-price",U:e.price}),e.merchant&&k.push({C:"div",G:"iv-card-offer-merchant",U:e.merchant}),k={C:"div",J:k});d={C:"div",W:d,L:{tabindex:"0"},J:[{C:"a",W:["iv-card-image","iv-click-target"],L:{style:"background-image: url("+b.imageUrl+");",href:WZ(b.url),"aria-hidden":"true",tabindex:"-1"}},{C:"div",G:"iv-card-content",J:[b.sponsored?{C:"div",G:"iv-card-sponsored",J:["Sponsored",{C:"div",G:"iv-ad-info-container",J:[{C:"div",G:"iv-ad-info",U:"{{adInfo}}"},
{C:"div",G:"iv-ad-info-icon-container",J:[{C:"div",G:"iv-ad-info-icon"},{C:"div",G:"iv-ad-info-callout"}]}]}]}:"",{C:"a",G:"iv-click-target",L:{href:WZ(b.url)},J:[h0(c,"h2",f,b.title),k]}]}]};d=new g.U(d);f=g.Rd("span");g.ae(f,"You are seeing this product because we think it is relevant to the video. Google may be compensated by the merchant.");d.kb(f,"adInfo");l0(c,d,b);return d;case "tip":return c=a.A,d=(0,g.z)(c.D,c,b),m0(c,b,d,d);case "video":return c=a.A,d=b.isLiveNow?{C:"span",W:["yt-badge",
"yt-badge-live"],U:"LIVE NOW"}:"",d={C:"div",W:["iv-card","iv-card-video"],J:[{C:"a",G:"iv-click-target",L:{href:WZ(b.url)},J:[k0(b.o,b.videoDuration?{C:"span",G:"iv-card-video-duration",U:b.videoDuration}:""),{C:"div",G:"iv-card-content",J:[p0(c,b),h0(c,"h2","iv-card-primary-link",b.title),n0(c,b),d]}]}]},d=new g.U(d),l0(c,d,b),d}return null},qoa=function(a,b){if(0==a.l.length)return 0;
var c=g.Xa(a.l,function(d){return b.Hb.startMs>d.Hb.startMs||b.Hb.startMs==d.Hb.startMs&&b.Hb.timestamp>=d.Hb.timestamp?!0:!1});
return-1==c?0:c+1},uoa=function(a){return a.g?"productListing"==a.g.Hb.type:(0,g.Zi)(a.l,function(b){return"productListing"==b.Hb.type})},D0=function(a){g.M(a.i.getRootNode(),"ytp-cards-shopping-active",uoa(a))},E0=function(a,b){if(a.F.Ea()){var c=new cZ([0,
a.o.scrollTop],[0,b.Uo.offsetTop],600,fna);a.context.l.da(c,"animate",function(d){a.o.scrollTop=d.y});
a.context.l.da(c,"finish",function(d){a.o.scrollTop=d.y});
c.play()}else g.IB(a.F,!0),a.o.scrollTop=b.Uo.offsetTop,g.IB(a.F,!1)},F0=function(a){return a.g&&a.g.Hb?a.g.Hb:a.l[0]&&a.l[0].Hb?a.l[0].Hb:null},toa=function(a,b){return g.Wa(a.l,function(c){return c.Hb.id==b})},G0=function(a,b,c){x0.call(this,a,b);
this.annotation=c;this.isActive=!1},voa=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&a.addCueRange(a.annotation.data.start_ms,a.annotation.data.end_ms,a.annotation.id,function(){a.show()},function(){a.hide()})},H0=function(a,b,c){G0.call(this,a,b,c);
this.i=null;this.D=!1;this.l=null;this.o=!1;this.u=0;this.g=this.B=this.A=null},I0=function(a,b,c){G0.call(this,a,b,c);
this.F=this.u=this.H=!1;this.B=5E3;this.o=null;this.D=g.Qd("DIV","iv-promo-contents");this.i=this.l=this.g=null;this.A=new g.N(function(){this.g.setAttribute("aria-hidden",!0);g.Oh(this.l,!1);g.Oh(this.i,!0)},700,this);
g.I(this,this.A)},woa=function(a){var b=a.annotation.data;
if("cta"==a.annotation.style)var c=6;else if("video"==a.annotation.style||"playlist"==a.annotation.style)c=7;a.B=b.collapse_delay_ms||a.B;var d=["iv-promo","iv-promo-inactive"];a.ka().setAttribute("aria-hidden",!0);a.ka().setAttribute("aria-label","Promotion");a.ka().tabIndex=0;var e=a.annotation.Ib(),f=b.image_url;if(f){var k=g.Qd("DIV",["iv-promo-img","iv-click-target"]);f=g.Qd("IMG",{src:f,"aria-hidden":"true"});k.appendChild(f);b.video_duration&&!b.is_live?(f=g.Qd("SPAN","iv-promo-video-duration",
b.video_duration),k.appendChild(f)):b.playlist_length&&(f=g.Qd("SPAN","iv-promo-playlist-length",b.playlist_length.toString()),k.appendChild(f));e&&a.yi(k,e,a.annotation.id,b.session_data,a.annotation.g,void 0,c)}e?(f=g.Qd("A","iv-promo-txt"),g.md(f,WZ(e)),a.g=f):a.g=g.Qd("DIV","iv-promo-txt");switch(a.annotation.style){case "cta":case "website":var l=g.Qd("P",null,g.Qd("STRONG",null,b.text_line_1));var m=g.Qd("P",null,g.Qd("SPAN","iv-promo-link",b.text_line_2));if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");
g.R(a.context.rb.experiments,"web_action_cta_larger_ui")&&d.push("iv-promo-website-card-cta-larger-ui");var n=g.Qd("BUTTON",["iv-promo-round-expand-icon","ytp-button"]);f=g.Qd("BUTTON",["iv-button","iv-promo-button"],g.Qd("SPAN","iv-button-content",f));var p=g.Qd("DIV","iv-promo-button-container");p.appendChild(f);e&&a.yi(a.ka(),e,a.annotation.id,b.session_data,a.annotation.g,void 0,c)}g.K(a.g,"iv-click-target");e&&a.yi(a.g,e,a.annotation.id,b.session_data,a.annotation.g,void 0,c);break;case "playlist":case "video":l=
g.Qd("P",null,g.Qd("SPAN",null,b.text_line_1)),m=g.Qd("P",null,g.Qd("STRONG",null,b.text_line_2)),b.is_live&&(l=m,m=g.Qd("SPAN",["yt-badge","iv-promo-badge-live"],"LIVE NOW")),g.K(a.g,"iv-click-target"),e&&a.yi(a.g,e,a.annotation.id,b.session_data,a.annotation.g,void 0,c),d.push("iv-promo-video")}l&&a.g.appendChild(l);m&&a.g.appendChild(m);a.D.appendChild(a.g);p&&a.D.appendChild(p);c=g.Qd("DIV","iv-promo-actions");a.i=g.Qd("BUTTON",["iv-promo-expand","ytp-button"]);a.i.title="Expand";a.context.g.da(a.i,
"click",g.Qa(a.Qp,5E3),a);c.appendChild(a.i);g.Oh(a.i,!1);a.context.g.da(a.ka(),"mouseover",a.YC,a);a.context.g.da(a.ka(),"mouseout",a.XC,a);a.context.g.da(a.ka(),"touchend",g.Qa(a.Qp,5E3),a);a.l=g.Qd("BUTTON",["iv-promo-close","ytp-button"]);a.l.title="Close";a.context.g.da(a.l,"click","cta"==a.annotation.style&&b.text_line_3?a.QC:a.PC,a);c.appendChild(a.l);g.Un(a.ka(),d);k&&(a.ka().appendChild(k),n&&k.appendChild(n));a.ka().appendChild(a.D);a.ka().appendChild(c)},J0=function(a){a.u||a.F||a.o||(g.K(a.ka(),
"iv-promo-collapsed"),a.u=!0,a.A.start())},K0=function(a){a.A.stop();
a.u&&(g.Wn(a.ka(),["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.u=!1,a.g&&a.g.removeAttribute("aria-hidden"),g.Oh(a.i,!1),g.Oh(a.l,!0))},M0=function(a,b){a.o||(a.o=g.Cg(function(){L0(this);
J0(this)},b,a))},L0=function(a){a.o&&(g.w.clearTimeout(a.o),a.o=null)},N0=function(a){g.TJ.call(this,a);
this.I=!1;this.H=0;this.i={};this.P={};this.D=new foa(a);this.A=new g.Ir(this);g.I(this,this.A);this.B=this.l=null;this.A.K(this.player,"onVideoAreaChange",(0,g.z)(this.N,this,"onVideoAreaChange"));this.A.K(this.player,"onHideControls",(0,g.z)(this.N,this,"onHideControls"));this.A.K(this.player,"onShowControls",(0,g.z)(this.N,this,"onShowControls"));this.A.K(this.player,"resize",(0,g.z)(this.N,this,"resize"));this.A.K(this.player,"presentingplayerstatechange",(0,g.z)(this.N,this,"presentingplayerstatechange"));
this.subscribe("onHideControls",this.qI,this);this.subscribe("onShowControls",this.qK,this);this.subscribe("presentingplayerstatechange",this.zJ,this);this.subscribe("resize",this.Ir,this);this.subscribe("G",this.qE,this);this.subscribe("F",this.qg,this);this.subscribe("D",this.pH,this);this.subscribe("E",this.SH,this);g.W(this.player).I.subscribe("vast_info_card_add",this.Sy,this);this.R=new g.Ir(this);g.I(this,this.R);this.R.K(this.player,g.pD("annotations_module"),this.oE);this.R.K(this.player,
"crx_annotations_module",this.pE);this.O=g.Qd("DIV",["video-legacy-annotations","html5-stop-propagation"]);this.V=g.Qd("DIV","video-custom-annotations");this.u=new g.U({C:"div",W:["ytp-player-content","ytp-iv-player-content"]});g.I(this,this.u);g.FJ(this.player,this.u.element,4);this.u.hide();this.o=new g.U({C:"div",W:["ytp-iv-video-content"]});g.I(this,this.o);g.Td(this.o.element,g.Qd("DIV","video-annotations",this.O,this.V));this.F=this.g=null;this.M=[];xoa(this)&&this.load();var b=g.Rd("STYLE");
(document.getElementsByTagName("HEAD")[0]||document.body).appendChild(b);g.of(this,function(){g.Wd(b)});
if(a=b.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},O0=function(a){switch(a){case "annotation-editor":case "live-dashboard":return!0}return!1},xoa=function(a){var b=g.W(a.player);
a=a.player.getVideoData();return 1==(b.Lf||a.Lf)&&!a.OA||null!==b.I.get(a.videoId)},P0=function(a,b,c){a.I=!0;
a.B=g.vq(b,c)},Q0=function(a,b){for(var c={},d=0;d<b.attributes.length;d++){var e=b.attributes[d];
c[e.name]=e.nodeValue}for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],e.tagName){if(c[e.tagName])var f=c[e.tagName];else if("data"==e.tagName){0<e.childNodes.length&&(f=e.childNodes[0].nodeValue,c[e.tagName]="string"==typeof f?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&"TEXT"==e.tagName?1==e.childNodes.length&&3==e.childNodes[0].nodeType?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push(Q0(a,e))}return c},R0=function(a,b,c){return!(a.loaded&&a.H==b&&a.player.getVideoData().videoId==
c)},zoa=function(a,b){var c=yoa(a,b);
if(!c&&"marker"!=b.type)return null;n_(b,function(e){e=(0,g.z)(this.OK,this,b.id,e);this.subscribe("ivTrigger:"+b.id,e)},a);
var d=new N_(a.wa,b,c);g.I(d,c);return d},Aoa=function(a,b){var c=g.Qd("DIV",["annotation",
"annotation-type-custom"]);g.Oh(c,!1);var d=null;switch(b.type){case "branding":if(g.W(a.player).Ni)break;a.u.element.appendChild(c);d=new H0(c,S0(a),b);break;case "promotion":g.FJ(a.player,c,4),d=new I0(c,S0(a),b)}d&&d.Hn();return d},Boa=function(a){var b=a.player.getVideoData();
if(b.Bd){var c=g.W(a.player),d=c.I.get(b.videoId);if(d){var e={format:"XML",Dc:{},method:"POST",withCredentials:!0};"gaming"==c.playerStyle&&(e.Dc.gaming="1");e.Vc=(0,g.z)(function(f,k,l){R0(this,f,k)||(f=g.pq(l)&&l.responseXML?l.responseXML:null)&&T0(this,f)},a,a.H,b.videoId);
g.ms()&&(e.Vc=U0(a,e.Vc));e.qb={ic_only:"1"};V0(e,d);a.I=!0;g.vq(b.Bd,e)}}},V0=function(a,b){a.method="POST";
a.qb=a.qb||{};b.xl&&(a.qb.ic_coll=b.xl);b.yl&&(a.qb.ic_xml=b.yl);b.Js&&(a.qb.ic_track=b.Js)},Coa=function(a){var b=new g.U({C:"div"});
g.Oh(b.element,!1);var c=new A0(a.player,b.element,S0(a));g.I(c,b);b.g(a.u.element);c.Hn();return c},S0=function(a){if(!a.F){var b=new gZ(a);
g.I(a,b);var c=new g.an(a);g.I(a,c);a.F=new ioa(b,c,g.W(a.player),a.player.getVideoData(),a.D,a.player,a.wa)}return a.F},T0=function(a,b){var c=!1;
Doa(b);for(var d=b.getElementsByTagName("annotation"),e=0;e<d.length;e++){var f=Q0(a,d[e]),k=null;try{k=Rna(f)}catch(l){}if(k){a:{switch(k.type){case "branding":case "promotion":f=!0;break a}f=!1}if(f){if(f=Aoa(a,k))g.I(a,f),a.P[k.id]=f}else if("card"==k.type||"drawer"==k.type)a.g||(a.g=Coa(a),g.I(a,a.g)),"card"==k.type?roa(a.g,k):soa(a.g,k),c=!0;else if(f=zoa(a,k))g.I(a,f),a.i[k.id]=f}}c&&(SY(a.player),a.Ir());g.Jb(a.i,function(l){if(l.view){var m=l.annotation;(l=l.view)&&m.segment&&m.segment.i&&
(m=this.i[m.segment.i])&&(l.O=m.annotation)}},a)},Doa=function(a){if((a=a.getElementsByTagName("annotations"))&&!(1>a.length)&&(a=a[0].getAttribute("itct"))){var b=g.Us();
if(b){var c=g.Ts();c&&g.Fs(b,c,[g.Ds(a)])}}},Eoa=function(a,b,c,d){d?W0(a,b,c):X0(a,b,c)},X0=function(a,b,c){if(b=a.i[b])P_(b),c&&c.i?(a=(0,g.z)(a.ew,a,b),b.g=new g.N(a,2E3),b.g.start()):a.ew(b)},W0=function(a,b,c){if(b=a.i[b])P_(b),c&&c.o?(a=(0,g.z)(a.bA,a,b),b.g=new g.N(a,2E3),b.g.start()):a.bA(b)},Y0=function(a,b){var c=a.player.getVideoData();
if(!c.nl)return!1;var d=WZ(b);if(!d)return!1;d=d.replace(/https?:\/\//g,"");if(!u0(d))return!1;d=g.cq(d);return d.list||d.p?!1:(d=v0(b))?c.videoId==d?!0:"new"!=b.target&&g.W(a.player).i?!0:!1:!1},yoa=function(a,b){if(Foa(b)){var c=b.u||l_(b,function(d){return"click"==d||"rollOut"==d||"rollOut"==d});
return new G_(b,(0,g.z)(a.O.appendChild,a.O),a.player,a.wa,c)}return null},Foa=function(a){if("highlight"==a.type||"widget"==a.type)return!0;
if("text"==a.type)for(var b in k_)if(a.style==k_[b])return!0;return!1},Z0=function(a,b,c,d){a.N(r_(b,d),c,d)},U0=function(a,b){return(0,g.z)(function(){if(!this.ea()){var c=Array.prototype.slice.call(arguments,0);
c.unshift(b);b=g.Qa.apply(window,c);this.M.push(g.ks(b))}},a)};
g.jJ.prototype.wi=g.ca(14,function(a,b){var c=g.kJ(this).l;c&&c.wi(a,b)});
g.jo.prototype.Op=g.ca(0,function(){this.i=this.M.createElement("DIV")});
var Zma=/[^\d]+$/,$ma={cm:1,"in":1,mm:1,pc:1,pt:1},ana={em:1,ex:1},XY={},YY=null;g.A(bZ,g.rf);g.A(cZ,g.Yn);g.h=cZ.prototype;g.h.getDuration=function(){return this.duration};
g.h.play=function(a){if(a||0==this.g)this.progress=0,this.coords=this.i;else if(1==this.g)return!1;ZY(this);this.startTime=a=(0,g.C)();-1==this.g&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.A=this.startTime;this.progress||this.o();this.Pd("play");-1==this.g&&this.Pd("resume");this.g=1;var b=g.Pa(this);b in XY||(XY[b]=this);$Y();aZ(this,a);return!0};
g.h.stop=function(a){ZY(this);this.g=0;a&&(this.progress=1);dZ(this,this.progress);this.Pd("stop");this.l()};
g.h.pause=function(){1==this.g&&(ZY(this),this.g=-1,this.Pd("pause"))};
g.h.T=function(){0==this.g||this.stop(!1);this.Pd("destroy");cZ.Ga.T.call(this)};
g.h.destroy=function(){this.dispose()};
g.h.Ar=function(){this.Pd("animate")};
g.h.Pd=function(a){this.dispatchEvent(new bZ(a,this))};
g.A(eZ,cZ);eZ.prototype.u=g.Ga;eZ.prototype.Ar=function(){this.u();eZ.Ga.Ar.call(this)};
eZ.prototype.l=function(){this.u();eZ.Ga.l.call(this)};
eZ.prototype.o=function(){this.u();eZ.Ga.o.call(this)};
g.A(fZ,eZ);fZ.prototype.u=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};
g.t(gZ,g.H);gZ.prototype.da=function(a,b,c,d){c=(0,g.z)(c,d||this.i);a=g.vr(a,b,c);this.g.push(a);return a};
gZ.prototype.rm=function(a,b,c,d){c=(0,g.z)(c,d||this.i);a=g.Fr(a,b,c);this.g.push(a);return a};
gZ.prototype.Na=function(a){g.wr(a);g.bb(this.g,a)};
gZ.prototype.T=function(){g.wr(this.g);this.g.length=0;g.H.prototype.T.call(this)};g.A(kZ,g.Pf);g.h=kZ.prototype;g.h.Jp=null;g.h.Aj=null;g.h.ka=function(){return this.Aj};
g.h.addEventListener=function(a,b,c,d){g.Bf(this.Aj,a,b,c,d)};
g.h.removeEventListener=function(a,b,c,d){g.Jf(this.Aj,a,b,c,d)};
g.h.T=function(){kZ.Ga.T.call(this);var a=this.Aj;if(a)if(g.uf(a))a.ge&&g.yf(a.ge);else if(a=g.Ef(a)){var b=0,c;for(c in a.listeners)for(var d=a.listeners[c].concat(),e=0;e<d.length;++e)g.Kf(d[e])&&++b}};g.A(pZ,kZ);pZ.prototype.fill=null;g.A(rZ,kZ);sZ.prototype.ze=null;sZ.prototype.ud=null;sZ.prototype.Fk=!0;var ina=[2,2,6,6,0];g.h=sZ.prototype;g.h.clear=function(){this.Ta.length=0;this.Ba.length=0;this.Md.length=0;delete this.ze;delete this.ud;delete this.Fk;return this};
g.h.moveTo=function(a,b){0==g.Ua(this.Ta)?this.Md.length-=2:(this.Ta.push(0),this.Ba.push(1));this.Md.push(a,b);this.ud=this.ze=[a,b];return this};
g.h.Zb=function(a){var b=g.Ua(this.Ta);if(null==b)throw Error("Path cannot start with lineTo");1!=b&&(this.Ta.push(1),this.Ba.push(0));for(b=0;b<arguments.length;b+=2){var c=arguments[b],d=arguments[b+1];this.Md.push(c,d)}this.Ba[this.Ba.length-1]+=b/2;this.ud=[c,d]};
g.h.close=function(){var a=g.Ua(this.Ta);if(null==a)throw Error("Path cannot start with close");4!=a&&(this.Ta.push(4),this.Ba.push(1),this.ud=this.ze);return this};
g.h.clone=function(){var a=new this.constructor;a.Ta=this.Ta.concat();a.Ba=this.Ba.concat();a.Md=this.Md.concat();a.ze=this.ze&&this.ze.concat();a.ud=this.ud&&this.ud.concat();a.Fk=this.Fk;return a};
g.h.transform=function(a){if(!this.Fk)throw Error("Non-simple path");a.transform(this.Md,0,this.Md,0,this.Md.length/2);this.ze&&a.transform(this.ze,0,this.ze,0,1);this.ud&&this.ze!=this.ud&&a.transform(this.ud,0,this.ud,0,1);return this};
g.h.isEmpty=function(){return 0==this.Ta.length};g.A(uZ,pZ);g.A(wZ,g.jo);wZ.prototype.o=null;wZ.prototype.qj=function(){return this.Sg?g.Nh(this.ka()):g.Ea(this.width)&&g.Ea(this.height)?new g.vd(this.width,this.height):null};
wZ.prototype.resume=function(){};g.A(mZ,qZ);g.A(lZ,qZ);g.A(xZ,rZ);xZ.prototype.clear=function(){g.Ud(this.ka())};
xZ.prototype.setSize=function(a,b){var c=this.ka(),d={width:a,height:b},e;for(e in d)c.setAttribute(e,d[e])};
g.A(yZ,uZ);var BZ;g.A(zZ,wZ);var lna=0;g.h=zZ.prototype;g.h.Op=function(){var a=nZ(this,"svg",{width:this.width,height:this.height,overflow:"hidden"}),b=nZ(this,"g");this.B=nZ(this,"defs");this.o=new xZ(b,this);a.appendChild(this.B);a.appendChild(b);this.i=a;this.l&&(this.ka().setAttribute("preserveAspectRatio","none"),this.O?this.DA():this.ka().setAttribute("viewBox","0 0 "+(this.l?this.l+" "+this.I:"")))};
g.h.DA=function(){if(this.Sg){var a=this.qj();0==a.width?this.ka().style.visibility="hidden":(this.ka().style.visibility="",this.o.ka().setAttribute("transform","scale("+a.width/this.l+" "+a.height/this.I+") translate(0 0)"))}};
g.h.setSize=function(a,b){g.Mh(this.ka(),a,b)};
g.h.qj=function(){if(!g.wh)return this.Sg?g.Nh(this.ka()):zZ.Ga.qj.call(this);var a=this.width,b=this.height,c=g.v(a)&&-1!=a.indexOf("%"),d=g.v(b)&&-1!=b.indexOf("%");if(!this.Sg&&(c||d))return null;if(c){var e=this.ka().parentNode;var f=g.Nh(e);a=parseFloat(a)*f.width/100}d&&(e=e||this.ka().parentNode,f=f||g.Nh(e),b=parseFloat(b)*f.height/100);return new g.vd(a,b)};
g.h.clear=function(){this.o.clear();g.Ud(this.B);this.g={}};
g.h.gj=function(){zZ.Ga.gj.call(this);this.O&&this.P.Na(mna(),"tick",this.DA)};
g.h.T=function(){delete this.g;delete this.B;delete this.o;this.P.dispose();delete this.P;zZ.Ga.T.call(this)};g.t(DZ,g.TJ);g.h=DZ.prototype;
g.h.load=function(){g.TJ.prototype.load.call(this);if(!FZ(g.W(this.player).playerStyle)){var a=g.qB(this.player.getVideoData());if(a)a=CZ(a,EZ(this)),GZ(this,a);else{var b=this.player.getVideoData();a=b.videoId;this.o&&this.o.abort();a={method:"POST",Vc:(0,g.z)(this.hI,this,a),Dc:{v:a},withCredentials:!0};"gaming"==g.W(this.player).playerStyle&&(a.Dc.gaming="1");this.P&&(a.Dc.ptype="embedded");var c=this.player.getVideoData().bv;c&&(a.qb={ad_tracking:c});if(b=g.pB(b))if(b=g.Vc(b),b=g.Sc(b))this.o=
g.vq(b,a)}}};
g.h.unload=function(){GZ(this,null);this.o&&(this.o.abort(),this.o=null);g.TJ.prototype.unload.call(this)};
g.h.Yb=function(a,b){if(!FZ(g.W(this.player).playerStyle))return null;if("loadCustomEndscreenRenderer"==a){var c=CZ(b,"new");GZ(this,c);return!0}return null};
g.h.getOptions=function(){return FZ(g.W(this.player).playerStyle)?["loadCustomEndscreenRenderer"]:[]};
g.h.hI=function(a,b){var c=this.o=null;if(200==b.status){var d=b.responseText;")]}"==d.substring(0,3)&&(d=d.substring(3),c=JSON.parse(d),c=CZ(c,EZ(this)))}GZ(this,c)};
g.h.ib=function(){if(this.i&&this.i.elements){var a=this.player.getVideoContentRect();if(a&&0!=a.width&&0!=a.height){var b=this.player.getPlayerSize();if(b&&0!=b.width&&0!=b.height){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<$0.length;f++){var k=Math.abs(b.width-$0[f]);if(-1==e||d>=k)e=f,d=k}d=a1[e];this.l&&g.uh(this.l.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.i.elements.length;++b)if(f=this.i.elements[b].id,e=this.g[f],k=this.B[f],e&&k){var l=k.width*c/k.aspectRatio;
f=Math.round(l*a.height);var m=a.left+Math.round(k.left*a.width),n=a.top+Math.round(k.top*a.height);g.Mh(e.element,Math.round(k.width*a.width),f);g.Ch(e.element,m,n);g.Wn(e.element,Goa);m=k.left+k.width/2;k=k.top+l/2;g.K(e.element,.5>=m&&.5>=k?"ytp-ce-top-left-quad":.5<m&&.5>=k?"ytp-ce-top-right-quad":.5>=m&&.5<k?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.Wn(e.element,a1);g.K(e.element,d);(e=g.Ed(document,"div","ytp-ce-expanding-overlay-body",e.element)[0])&&g.uh(e,"height",f+"px")}}}}};
g.h.sE=function(a){if(this.i)if("ytp-ce-in-endscreen"==a.getId())this.H=!1,this.i.skip&&1==this.player.getPlayerState()?(g.sJ(this.player,!0),this.player.seekTo(Infinity),this.H=!0):(KZ(this,this.i.impressionUrls),(a=g.Us())&&this.i.visualElement&&g.Gs(a,this.i.visualElement));else if(!this.H){a=a.getId().substring(15);var b=this.g[a],c=this.B[a];g.K(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");b=this.player.getRootNode();g.K(b,"ytp-ce-shown");KZ(this,c.impressionUrls);
(b=g.Us())&&g.Gs(b,c.visualElement);g.W(this.player).tb&&this.player.ma("endscreenelementshown",a)}};
g.h.tE=function(a){if("ytp-ce-in-endscreen"!=a.getId()&&!this.H){a=a.getId().substring(15);var b=this.g[a];g.Vn(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden",!0);b=this.player.getRootNode();g.Vn(b,"ytp-ce-shown");g.W(this.player).tb&&this.player.ma("endscreenelementhidden",a)}};
g.h.dL=function(a){var b=this;a.target===window&&(new g.N(function(){for(var c in b.g)g.Wn(b.g[c].element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
g.h.ty=function(a,b){if(a.targetUrl&&(!b||"keypress"!=b.type||13==b.keyCode)){for(var c=b.target;c&&!g.Tn(c,"ytp-ce-element");){g.Tn(c,"subscribe-label")&&LZ(this,a);if(g.Tn(c,"ytp-ce-channel-subscribe"))return;c=g.Zd(c)}if(!c||g.Tn(c,"ytp-ce-element-hover")){b.preventDefault();b.stopPropagation();if(c=this.g[a.id])this.Hr(c,a),c.element.blur();b.ctrlKey||b.metaKey||"new"==a.Nn?(LZ(this,a),this.Jz(),this.player.pauseVideo(),c=g.Vc(a.targetUrl),c=g.Sc(c),g.LK(c,void 0,a.Wc)):(c=this.player.getVideoData().ac,
c=(0,g.z)(this.OL,this,c,a.targetUrl,a.Wc),c=(0,g.z)(this.Jz,this,c),LZ(this,a,c))}}};
g.h.OL=function(a,b,c){var d=g.cq(b);a&&d&&(d.v||d.list)?g.sX(this.player.app,d.v,c,d.list,!1,void 0,void 0):g.KK(b,c)};
g.h.Nq=function(a,b){g.Tn(a.element,"ytp-ce-element-hover")||("VIDEO"==b.type||"PLAYLIST"==b.type?g.K(a.element,"ytp-ce-element-hover"):g.W(this.player).g?(new g.N(function(){g.K(a.element,"ytp-ce-element-hover")},200)).start():g.K(a.element,"ytp-ce-element-hover"),KZ(this,b.wD),JZ(this,b.id,!0))};
g.h.Hr=function(a,b){g.Vn(a.element,"ytp-ce-element-hover");g.Vn(a.element,"ytp-ce-force-expand");JZ(this,b.id,!1)};
g.h.Jz=function(a){this.player.sendVideoStatsEngageEvent(17,a)};
var $0=[346,426,470,506,570,640,853,1280,1920],a1="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),Goa=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"];var xna={qN:"current",xO:"new"};var zna={CLOSE:"close",BO:"openUrl",EB:"subscribe"},Ana={lN:"click",CLOSE:"close",TN:"hidden",bP:"rollOut",AB:"rollOver",BB:"shown"};var Cna={FP:"xx",GP:"xy",HP:"yx",IP:"yy"};g.t(f_,ZZ);var Hna={bB:"anchored",XO:"rect",eP:"shapeless"};var Lna={CLOSED:"closed",KO:"playerControlShow",AB:"rollOver",BB:"shown"};j_.prototype.Ib=function(){var a=Tna(this,function(b){return"openUrl"==b.type&&null!=b.url});
return a?a.url:null};
j_.prototype.showLinkIcon=function(){return l_(this,function(a){return null!=a.url&&a.url.showLinkIcon})};
var k_={bB:"anchored",eB:"branding",CHANNEL:"channel",pN:"cta",VN:"highlightText",jO:"label",PLAYLIST:"playlist",NO:"popup",iP:"speech",EB:"subscribe",rP:"title",VIDEO:"video",BP:"website"},Pna={eB:"branding",cN:"card",wN:"drawer",UN:"highlight",rO:"marker",SO:"promotion",TEXT:"text",DP:"widget"},Qna={zP:"video_relative",LO:"player_relative"};s_.prototype.o=function(a,b,c,d){this.g[a]=b?!c:c;a=g.Nb(this.g,function(e){return e});
this.l!=a&&(this.l=a,this.i.N(this.u,a,d))};t_.prototype.ka=function(){return this.u};
t_.prototype.l=function(){};var x_={bevel:1,dropshadow:2};g.t(C_,t_);
C_.prototype.l=function(a,b){var c=p_(a);if(c){var d=c_(c,b);if(!(0>=d.width||0>=d.height)){var e;if(e=(c=(c=o_(a))&&c.g?c.g:null)&&c.length?c[0]:null){var f=g.lh(a_(b,b_(e,new g.ih(e.D,e.F,e.Hi,e.l),b.g))),k=d.clone();c=new g.ih(f.x,f.y,1,1);var l=Math.max(k.left+k.width,c.left+c.width),m=Math.max(k.top+k.height,c.top+c.height);k.left=Math.min(k.left,c.left);k.top=Math.min(k.top,c.top);k.width=l-k.left;k.height=m-k.top;c=a.i;k=A_(k,c.effects);l=u_(this,k.width,k.height);m=z_(c,k.width,k.height,this.g);
d=new g.ih(d.left-k.left,d.top-k.top,d.width,d.height);var n=new g.td(f.x-k.left,f.y-k.top);this.o=17*YZ(b.g,e.i,e.g?e.g:"xy");e=c.cornerRadius;f=a.i;var p=this.g&&m_(a),r=p?f.borderWidth+1:f.borderWidth;p=(f=r?new vZ(r,p?f.i:f.borderColor):null)?f.g/2:0;r=aoa(d,n);var u=this.A(d,e,n,r),y=n.x;n=n.y;var D=d.width,F=d.height,E=d.left;d=d.top;var L=new sZ;L.moveTo(E+e+p,d+p);"t"==r&&(L.Zb(u.start,d+p),L.Zb(y,n),L.Zb(u.end,d+p));L.Zb(E+D-e-p,d+p);tZ(L,e,e,-90);"r"==r&&(L.Zb(E+D-p,u.start),L.Zb(y,n),L.Zb(E+
D-p,u.end));L.Zb(E+D-p,d+F-e-p);tZ(L,e,e,0);"b"==r&&(L.Zb(u.end,d+F-p),L.Zb(y,n),L.Zb(u.start,d+F-p));L.Zb(E+e+p,d+F-p);tZ(L,e,e,90);"l"==r&&(L.Zb(E+p,u.end),L.Zb(y,n),L.Zb(E+p,u.start));L.Zb(E+p,d+e+p);tZ(L,e,e,180);L.close();AZ(l,L,f,m);if(m=this.ka())g.K(m,"annotation-shape"),g.K(m,"annotation-speech-shape"),g.Ch(m,k.left,k.top),g.Mh(m,k.width,k.height),B_(l,m,c.effects)}}}};
C_.prototype.A=function(a,b,c,d){function e(f,k,l,m){f=Math.min(Math.max(m-2*b,0),f);k=g.pd(k-f/2,l+b,l+m-f-b);return new g.qi(k,k+f)}
return"t"==d||"b"==d?e(this.o,c.x,a.left,a.width):"l"==d||"r"==d?e(this.o,c.y,a.top,a.height):new g.qi(0,0)};g.t(D_,t_);D_.prototype.l=function(a,b){var c=p_(a);if(c){var d=c_(c,b);if(!(0>=d.width||0>=d.height)){var e=a.i;c=A_(d,e.effects);var f=u_(this,c.width,c.height),k=new vZ(!e.l&&this.g?1:e.l,e.bgColor),l=new lZ("#000",0);d=y_(new g.ih(0,0,d.width,d.height),e.cornerRadius,k?k.g/2+1:0);AZ(f,d,k,l);f=this.ka();g.K(f,"annotation-shape");e=e.g;UY(f,this.g?Math.max(e,.9):e);g.Ch(f,c.left,c.top);g.Mh(f,c.width,c.height)}}};g.t(E_,t_);
E_.prototype.l=function(a,b){var c=p_(a);if(c){var d=c_(c,b);if(!(0>=d.width||0>=d.height)){c=a.i;var e=A_(d,c.effects),f=u_(this,e.width,e.height),k=new g.ih(0,0,d.width,d.height);d=z_(c,d.width,d.height,this.g);var l=c.cornerRadius;var m=a.i;var n=this.g&&m_(a),p=n?m.borderWidth+1:m.borderWidth;m=p?new vZ(p,n?m.i:m.borderColor):null;k=y_(k,l,m?m.g/2+1:0);AZ(f,k,m,d);if(k=this.ka())g.K(k,"annotation-shape"),g.K(k,"annotation-popup-shape"),g.Ch(k,e.left,e.top),g.Mh(k,e.width,e.height),B_(f,k,c.effects)}}};g.t(F_,C_);F_.prototype.A=function(a,b,c,d){function e(f,k,l,m){f=Math.min(Math.max(m-2*b,0),f);k=k<=l+m/2?Math.max(l+m/4-f/2,l+b):Math.min(l+3*m/4-f/2,l+m-f-b);return new g.qi(k,k+f)}
return"t"==d||"b"==d?e(this.o,c.x,a.left,a.width):"l"==d||"r"==d?e(this.o,c.y,a.top,a.height):new g.qi(0,0)};g.t(G_,g.H);g.h=G_.prototype;g.h.gx=function(){this.F||(this.o&&g.Oh(this.o,!0),this.u&&g.Oh(this.u,!0),this.l&&(this.l.g=!0,UY(this.i,L_(this)?1:0),this.l.l(this.g,I_(this))),this.D.isActive()&&this.D.stop(),this.F=!0,this.H=this.ca.rm(g.pJ(this.A),"mouseleave",function(a){this.Tm.stop();this.qg(a)}))};
g.h.qg=function(){this.F&&(this.M?this.D.start():this.gw(),this.l&&(this.l.g=!1,UY(this.i,L_(this)?1:0),this.l.l(this.g,I_(this))),this.F=!1,this.H&&(this.ca.Na(this.H),this.H=null))};
g.h.gw=function(){this.o&&g.Oh(this.o,!1);this.u&&g.Oh(this.u,!1)};
g.h.gF=function(a){this.aa=a;this.Tm.yj()};
g.h.WC=function(){var a=this.aa,b=new g.td(a.clientX,a.clientY),c=g.Gh(this.A.getRootNode()),d=M_(c,this.P);c=(this.u&&VY(this.u)||this.o&&VY(this.o))&&M_(c,this.M);d&&d.contains(b)||c&&c.contains(b)?this.gx(a):this.qg(a)};
g.h.show=function(){var a=this.g.i;a=(a&&0==a.g||"title"==this.g.style||"highlightText"==this.g.style?!1:!0)&&!this.l;var b=!this.i;if(a){var c=I_(this),d=null;"highlight"==this.g.type||"label"==this.g.style?d=new D_:"popup"==this.g.style?d=new E_:"anchored"==this.g.style?d=new C_:"speech"==this.g.style&&(d=new F_);d&&(d.l(this.g,c),this.l=d,c=d.ka())&&(g.Oh(c,!1),g.K(c,"annotation-type-"+this.g.type.toLowerCase()),this.R(c))}if(b){c=["annotation"];"highlightText"!=this.g.style||c.push("annotation-no-mouse");
c.push("annotation-type-"+this.g.type.toLowerCase());this.i=g.Qd("DIV",c);g.Oh(this.i,!1);this.g.o&&(this.B=g.Qd("DIV","inner-text"),"label"==this.g.style&&(g.K(this.B,"player-label-text"),this.B.style.backgroundColor=this.g.i.bgColor),g.ae(this.B,this.g.o),this.i.appendChild(this.B));g.Dp(this.i,"annotation_id",this.g.id);this.R(this.i);boa(this,this.i);if(m_(this.g)&&this.g.showLinkIcon()){if(d=this.g.Ib())c=this.i,d=new g.Nm(WZ(d)),c.title=d.g+d.i;this.u=g.Qd("SPAN","annotation-link-icon");g.Oh(this.u,
!1);this.i.appendChild(this.u)}coa(this);m_(this.g)||(this.i.style.cursor="default")}if(a||b){a:{a=this.g.segment.g;if(a.length&&(a=h_(a[0]))){a=a.u;break a}a=0}this.i&&(this.i.style.zIndex=a);this.l&&this.l.ka()&&(this.l.ka().style.zIndex=a)}g.Oh(this.i,!0);UY(this.i,L_(this)?1:0);K_(this);this.l&&this.l.ka()&&g.Oh(this.l.ka(),!0)};
g.h.hide=function(){this.i&&g.Oh(this.i,!1);this.l&&this.l.ka()&&g.Oh(this.l.ka(),!1);this.I&&(this.ca.Na(this.I),this.I=null)};g.t(N_,g.H);g.h=N_.prototype;g.h.hide=function(){this.isVisible=!1;this.view&&(O_(this),this.view.hide())};
g.h.show=function(){this.isVisible=!0;this.view&&(this.view.show(),this.i.subscribe("resize",this.fx,this),this.i.subscribe("onVideoAreaChange",this.Ty,this))};
g.h.destroy=function(){if(this.view){O_(this);var a=this.view,b=a.ca;g.wr(b.g);b.g.length=0;a.Tm.dispose();a.D.dispose();a.i&&g.Wd(a.i);a.l&&a.l.ka()&&g.Wd(a.l.ka())}P_(this)};
g.h.Ty=function(){K_(this.view)};
g.h.fx=function(){K_(this.view)};g.t(Q_,jZ);g.t(R_,jZ);g.t(S_,R_);g.t(T_,jZ);g.t(U_,jZ);g.t(V_,R_);g.t(W_,R_);g.t(X_,jZ);g.t(Y_,jZ);g0.prototype.l=function(a,b){var c=g.ge(b.target,"label");c&&g.M(c,"iv-card-poll-choice-focused",a)};
g0.prototype.B=function(a,b){var c=g.ge(b.target,null,"iv-card-poll",void 0);if(c)if(a.o)g.Gd("iv-card-sign-in-button",c).click();else{var d=parseInt(cna(b.target),10);if(null==a.g)a.choices[d].count++,a.g=d;else if(a.g!=d){var e=a.choices[a.g];e.count=Math.max(e.count-1,0);a.choices[d].count++;a.g=d}else e=a.choices[a.g],e.count=Math.max(e.count-1,0),a.g=null;i0(a,c);g.zq(this.g.videoData.Bd,{Dc:{action_poll_vote:1},qb:{poll_id:a.id,index:d,session_token:a.F}});c0(this.g.logger,a.l,void 0,{"link-id":d},
a.i.click,5);(c=g.Us())&&g.Hs(c,a.A)}};
g0.prototype.A=function(a){var b=g.x("yt.ypc.bootstrap.api.loadOffersForInnertubeRequestParams"),c;b&&(c=function(){b(a.F,a.B)});
q0(this,a,!0,c)};
g0.prototype.D=function(a){var b=g.x("yt.ypc.bootstrap.api.loadOffers");b&&(b=g.Qa(b,a.P,a.F,a.B));q0(this,a,!1,b)};g.t(x0,g.H);g.h=x0.prototype;g.h.addCueRange=function(a,b,c,d,e){a=new g.mD(a,b,{id:c});g.I(this,a);a.namespace="annotations_module";d&&RY(a).subscribe("onEnter",d,this);e&&RY(a).subscribe("onExit",e,this);g.yJ(this.context.Z,[a])};
g.h.Hn=function(){this.context.i.subscribe("resize",this.sl,this)};
g.h.ka=function(){return this.Ca};
g.h.yi=function(a,b,c,d,e,f,k){this.context.g.da(a,"click",g.Qa(this.qm,b,c,d,e,f||[],k||0),this);this.context.g.da(a,"touchstart",g.Qa(function(){this.Us=!1}),this);
this.context.g.da(a,"touchmove",g.Qa(function(){this.Us=!0}),this)};
g.h.qm=function(a,b,c,d,e,f,k){if(this.Us)return!1;k&&(k.stopPropagation(),k.preventDefault());noa(this,a,c,d,e,f);return!1};
g.h.show=function(){this.X=(0,g.C)()};
g.h.hide=function(){};
g.h.destroy=function(){g.Wd(this.ka())};
g.h.sl=function(){};g.t(A0,x0);g.h=A0.prototype;g.h.isAvailable=function(){var a;if(a=!!this.l.length)(a=this.i.getRootNode())?(a=g.Nh(a),a=173<a.width&&173<a.height):a=!1;return a};
g.h.sl=function(){var a=this.isAvailable();g.Oh(this.ka(),a);g.M(this.context.Z.getRootNode(),"ytp-iv-drawer-enabled",a);SY(this.i)};
g.h.destroy=function(){this.i.wi(!1);this.i.getRootNode().removeChild(this.B);g.Op(this.I);g.wr(this.aa);this.Y&&this.Y.dispose();this.D&&this.D.dispose();x0.prototype.destroy.call(this)};
g.h.IE=function(a){this.M.start();a.preventDefault();a=a||window.event;var b=0;"MozMousePixelScroll"==a.type?b=0==(a.axis==a.HORIZONTAL_AXIS)?a.detail:0:window.opera?b=a.detail:b=0==a.wheelDelta%120?"WebkitTransform"in document.documentElement.style?window.chrome&&0==navigator.platform.indexOf("Mac")?a.wheelDeltaY/-30:a.wheelDeltaY/-1.2:a.wheelDelta/-1.6:a.wheelDeltaY/-3;if(a=b)this.o.scrollTop+=a};
g.h.Pz=function(a){if(!g.Tn(this.i.getRootNode(),"ytp-cards-teaser-shown")){if(this.g!=a){var b=g.Us(),c=this.g?this.g.Hb.u:this.H;b&&c&&iZ(b,[c]);this.g=a;D0(this)}VY(this.ka())&&(2==this.context.Z.getPresentingPlayerType()?b=1==(isNaN(void 0)?this.context.Z.getAdState():void 0):(b=isNaN(void 0)?this.context.Z.getPlayerState():void 0,b=1==b||0==b&&0===this.context.Z.getCurrentTime()),b&&a.Hb.teaserDurationMs&&this.i.wi(!0,{teaserText:a.Hb.teaserText,durationMs:a.Hb.teaserDurationMs}));this.la.isActive()||
((!this.u||!this.M.isActive()&&this.V)&&E0(this,a),this.la.start(910+a.Hb.teaserDurationMs))}};
g.h.IL=function(a){this.u||(this.g=a,D0(this),E0(this,a),y0(this,"YOUTUBE_DRAWER_AUTO_OPEN",!1,a))};
g.h.aC=function(){if(this.u){e0(this.context.logger,this.R,4,F0(this).i.close);var a=g.Us();a&&this.P&&g.Hs(a,this.P);z0(this)}};
g.h.jC=function(){g.M(this.B,"iv-drawer-scrolled",0<this.o.scrollTop)};
g.h.QD=function(){var a=g.Us(),b=F0(this);b=b?b.u:this.H;a&&b&&hZ(a,[b])};
g.h.PD=function(){var a=g.Us(),b=F0(this);b=b?b.u:this.H;a&&b&&iZ(a,[b])};
g.h.TD=function(){var a=F0(this);f0(this.context.logger,8,a.l,a.i.VL);var b=g.Us();b&&a&&hZ(b,[a.D,a.u])};
g.h.SD=function(){var a=g.Us(),b=F0(this);a&&b&&iZ(a,[b.D])};
g.h.RD=function(a){var b=F0(this),c=g.Us();this.g?a?(a=this.context.logger,f0(a,9,b.l,b.i.Cs),a.g.sendVideoStatsEngageEvent(4,void 0),c&&g.Hs(c,b.D)):(a=this.context.logger,f0(a,12,b.l,b.i.Cs),a.g.sendVideoStatsEngageEvent(4,void 0),c&&g.Hs(c,b.u)):(a=this.context.logger,e0(a,this.R,12,b.i.Cs),a.g.sendVideoStatsEngageEvent(4,void 0),c&&this.H&&g.Hs(c,this.H))};
var B0={collaborator:Q_,donation:S_,episode:Y_,movie:Y_,playlist:T_,poll:U_,productListing:V_,simple:R_,tip:W_,video:X_};g.t(G0,x0);G0.prototype.Hn=function(){x0.prototype.Hn.call(this);voa(this)};
G0.prototype.show=function(){x0.prototype.show.call(this);var a=g.Us(),b=this.annotation.data;a&&b&&(b=b.session_data)&&hZ(a,[g.Ds(b.itct)])};
G0.prototype.hide=function(){x0.prototype.hide.call(this);var a=g.Us(),b=this.annotation.data;a&&b&&(b=b.session_data)&&iZ(a,[g.Ds(b.itct)])};g.t(H0,G0);g.h=H0.prototype;g.h.PL=function(a,b,c,d){this.l.stop();if(!this.o){var e=g.Nh(a);this.g||(g.Lh(a,e.width),g.Lh(b,e.width));g.uh(c,"top",e.height-Math.max(Math.min(e.height,d)/2+10,20)+"px");g.uh(c,"right","1px");this.o=!0;g.Oh(a,!0);this.A=new g.N(function(){g.K(this.ka(),"iv-branding-active")},0,this);
this.A.start()}};
g.h.uD=function(a,b){g.Vn(this.ka(),"iv-branding-active");this.B=new g.N((0,g.z)(function(){g.Oh(a,!1);this.g||g.Lh(b,0)},this),250);
this.B.start();this.o=!1};
g.h.show=function(){if(!this.isActive){G0.prototype.show.call(this);if(!this.D){g.K(this.ka(),"iv-branding");var a=this.annotation.data;this.u=a.image_width;this.i=g.Qd("IMG",{src:a.image_url,"class":"branding-img iv-click-target",width:a.image_width,height:a.image_height});g.Oh(this.i,!1);var b=g.Qd("DIV","branding-img-container",this.i);this.ka().appendChild(b);var c=g.Qd("DIV","iv-branding-context-name");g.ae(c,a.channel_name);var d=g.Qd("DIV","iv-branding-context-subscribe");if(b=a.standalone_subscribe_button_data)this.g=
new g.iV(b.subscribeText,b.subscribeCount,b.unsubscribeText,b.unsubscribeCount,!!b.enabled,!!b.classic,a.channel_id,!!b.subscribed,b.feature,a.session_data.itct,b.signinUrl,this.context.Z),this.g.g(d);b=g.Qd("DIV","iv-branding-context-subscribe-caret");c=g.Qd("DIV","branding-context-container-inner",b,c,d);g.Oh(c,!1);d=g.Qd("DIV","branding-context-container-outer",c);g.uh(d,"right",this.u+"px");this.ka().appendChild(d);var e=this.annotation.Ib();e&&this.yi(this.i,e,this.annotation.id,a.session_data,
this.annotation.g);this.l=new g.N(g.Qa(this.uD,c,d),500,this);g.I(this,this.l);this.context.g.da(this.ka(),"mouseover",(0,g.z)(this.PL,this,c,d,b,a.image_height));this.context.g.da(this.ka(),"mouseout",(0,g.z)(this.l.start,this.l,void 0));this.D=!0}b0(this.context.logger,this.annotation.g);g.Oh(this.ka(),!0);this.isActive=!0;if(this.i){a=this.i;var f=void 0===f?0:f;b=TY(a).width;c=g.Ea(void 0)?void 0:b;g.Ch(a,c);f=new fZ(a,[c,a.offsetTop],[c-b-f,a.offsetTop],200,ena);g.I(this,f);this.context.l.da(f,
"begin",g.Qa(g.Oh,a,!0));f.play()}}};
g.h.hide=function(){this.isActive&&(G0.prototype.hide.call(this),g.Oh(this.ka(),!1),this.isActive=!1)};
g.h.destroy=function(){this.g&&(this.g.dispose(),this.g=null);G0.prototype.destroy.call(this)};g.t(I0,G0);g.h=I0.prototype;g.h.show=function(){this.isActive||(G0.prototype.show.call(this),this.H||(woa(this),this.H=!0),g.Oh(this.ka(),!0),this.annotation&&this.annotation.g&&b0(this.context.logger,this.annotation.g),g.Cg(function(){g.Vn(this.ka(),"iv-promo-inactive")},100,this),this.ka().removeAttribute("aria-hidden"),this.isActive=!0,L0(this),K0(this),M0(this,this.B))};
g.h.hide=function(){this.isActive&&(g.K(this.ka(),"iv-promo-inactive"),this.isActive=!1,this.ka().setAttribute("aria-hidden",!0))};
g.h.qm=function(a,b,c,d,e,f,k){return this.u?!1:G0.prototype.qm.call(this,a,b,c,d,e,f,k)};
g.h.Qp=function(a,b){b.stopPropagation();K0(this);M0(this,a);this.g.focus()};
g.h.YC=function(a){this.F=!0;this.Qp(500,a)};
g.h.XC=function(){this.F=!1;J0(this)};
g.h.PC=function(a){a.stopPropagation();this.hide();d0(this.context.logger,this.annotation.g)};
g.h.QC=function(a){a.stopPropagation();L0(this);this.u=!0;g.K(this.ka(),"iv-promo-collapsed-no-delay");this.A.start();d0(this.context.logger,this.annotation.g)};
g.h.destroy=function(){this.A.dispose();G0.prototype.destroy.call(this)};g.t(N0,g.TJ);g.h=N0.prototype;g.h.Yb=function(a,b){if(!O0(g.W(this.player).playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":var c=g.Xn(b);c&&T0(this,c);return!0;case "removeCustomAnnotationById":return b&&this.g&&(C0(this.g,b),SY(this.player)),!0}return null};
g.h.getOptions=function(){return O0(g.W(this.player).playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.h.Ir=function(){if(this.o){var a=g.pJ(this.player).getVideoContentRect(!0);g.Mh(this.o.element,a.width,a.height);g.Ch(this.o.element,a.left,a.top)}if(this.g){var b=g.wJ(this.player);a=this.g;b=b.width;g.M(a.B,"iv-drawer-small",426>=b);g.M(a.B,"iv-drawer-big",1280<=b)}};
g.h.zJ=function(a){this.jc(a.state);g.V(a.state,2)&&(this.sd()&&this.xe()&&2!=this.player.getPresentingPlayerType()&&this.setCardsVisible(!1),this.wi(!1))};
g.h.load=function(){g.TJ.prototype.load.call(this);this.jc(g.oJ(this.player));this.H++;var a=this.player.getVideoData(),b=a.videoId,c=(0,g.z)(this.iI,this,b,this.H),d=(0,g.z)(function(){this.B=null},this);
g.ms()&&(c=U0(this,c));c={format:"XML",Vc:c,onError:d,Dc:{}};a.isPharma&&(c.Dc.pharma="1");c.method="POST";c.withCredentials=!0;d=g.W(this.player);"gaming"==d.playerStyle&&(c.Dc.gaming="1");(b=d.I.get(b))&&V0(c,b);b=b&&(b.yl||b.xl);if(!a.ll||b)a.Bd?P0(this,a.Bd,c):(this.l=(0,g.z)(this.rE,this,c),this.player.addEventListener("videodatachange",this.l));g.FJ(this.player,this.o.element,4);this.Ir()};
g.h.jc=function(a){a=!a.isCued()&&!g.V(a,1024);g.IB(this.u,a);g.IB(this.o,a)};
g.h.rE=function(a){var b=this.player.getVideoData();b.Bd&&(this.l&&(this.player.removeEventListener("videodatachange",this.l),this.l=null),P0(this,b.Bd,a))};
g.h.unload=function(){goa(this.D);g.BJ(this.player,"annotations_module");g.Jb(this.i,function(a){a.destroy()});
g.Jb(this.P,function(a){a.destroy()});
this.F=null;this.g&&(this.g.destroy(),this.g=null,SY(this.player));this.I=!1;this.B&&(this.B.abort(),this.B=null);this.i={};this.P={};this.u.hide();g.TJ.prototype.unload.call(this);g.HB(this.o);this.l&&(this.player.removeEventListener("videodatachange",this.l),this.l=null)};
g.h.iI=function(a,b,c){this.B=null;if(!R0(this,b,a)&&(a=g.pq(c)&&c.responseXML?c.responseXML:null)){T0(this,a);g.K(this.player.getRootNode(),"iv-module-loaded");a=[];for(var d in this.i){b=this.i[d].annotation;if(b.segment)if(c=b.segment,c.g.length)if(c=c.g[0].i||c.g[0].g||c.g[0].l,!c||2>c.length)c=null;else{var e=c.length-1;c=0>=c[0].t&&0>=c[e].t?null:{start:c[0].t,end:c[e].t}}else c=null;else c=null;if(e=c)if(c=1E3*e.start,e=1E3*e.end,0==c&&(c++,e++),!(e<c)){var f={id:d,namespace:"annotations_module"};
"marker"==b.type&&(f.style="ytp-chapter-marker",f.tooltip=b.o,f.visible=!0);b=new g.mD(c,e,f);a.push(b)}}g.yJ(this.player,a)}};
g.h.Sy=function(a){a==this.player.getVideoData().videoId&&(this.loaded?Boa(this):this.load())};
g.h.oE=function(a){a=a.getId();var b=this.i[a];b&&!b.l&&(b=b.annotation,W0(this,a),b0(this.D,b.g))};
g.h.pE=function(a){X0(this,a.getId())};
g.h.ew=function(a){a&&(a.hide(),Z0(this,"shown",!1,a.annotation.id),this.Hl(a.annotation,"hidden"))};
g.h.bA=function(a){a&&(a.show(),Z0(this,"shown",!0,a.annotation.id),this.Hl(a.annotation,"shown"))};
g.h.OK=function(a,b,c){var d=this.i[a];if(d&&b.value!=c){b.value=c;var e=!1;n_(d.annotation,function(f){e=e||f.value});
Eoa(this,a,b,e)}};
g.h.pH=function(a){if(a&&a.id){var b=a.Ib();if(b){var c=WZ(b);if(c){var d=(0,g.z)(this.Hl,this,a,"click");if("new"==w0(c,b.target)||Y0(this,b))d(),d=null;c0(this.D,a.g,d)}}}};
g.h.Hl=function(a,b){Sna(a,function(c){if(c.trigger==b&&"openUrl"==c.type&&c.url){var d=this.player.getVideoData(),e;if(!(e=!Y0(this,c.url))){e=v0(c.url);var f=koa(c.url);e?(d.videoId==e?this.player.seekTo(f||0):(d=S0(this).Z,g.sX(d.app,e,void 0,void 0,void 0,void 0,void 0),f&&S0(this).Z.dc()&&S0(this).Z.seekTo(f)),d=!0):d=!1;e=!d}e&&(e=g.W(this.player),(d=WZ(c.url))?(f=t0(d),e&&"com"==f[0]&&"google"==f[1]&&"plus"==f[2]&&(e=g.Qa(loa,e.pageId,e.kc),d=new g.Nm(d),e=e(d.i),d.i=e,d=d.toString())):d=null,
d&&(this.player.pauseVideo(),c=w0(d,c.url.target),e=a.itct,"ei"in g.cq(d)&&(d=g.ch(d,"ei")),g.LK(d,"current"==c?"_top":void 0,{itct:e})))}},this)};
g.h.qI=function(){Z0(this,"playerControlShow",!1)};
g.h.qK=function(){Z0(this,"playerControlShow",!0)};
g.h.qE=function(a){Z0(this,"rollOver",!0,a.id)};
g.h.qg=function(a){Z0(this,"rollOver",!1,a.id)};
g.h.SH=function(a){a&&a.id&&(this.i[a.id].l=!0,X0(this,a.id),d0(this.D,a.g),this.Hl(a,"close"),Z0(this,"closed",!0,a.id))};
g.h.sd=function(){return!!this.g&&this.g.isAvailable()};
g.h.xe=function(){this.sd();return!!this.g&&this.g.u};
g.h.setCardsVisible=function(a,b,c){b=void 0===b?!1:b;this.sd();this.g&&(a?c?y0(this.g,c,b):y0(this.g,"YOUTUBE_DRAWER_AUTO_OPEN",b):z0(this.g))};
g.h.wi=function(a,b){this.player.N(a?"cardsteasershow":"cardsteaserhide",b)};
g.h.T=function(){g.W(this.player).I.unsubscribe("vast_info_card_add",this.Sy,this);g.Vn(this.player.getRootNode(),"ytp-iv-drawer-open");for(var a=this.M,b=0,c=a.length;b<c;b++)g.ns(a[b]);this.M.length=0;g.TJ.prototype.T.call(this)};g.qU.annotations_module=N0;g.qU.creatorendscreen=DZ;})(_yt_player);
