(function(g){var window=this;var b1=function(a){var b={languageCode:a.i,languageName:a.l,displayName:g.ez(a),kind:a.o,name:a.u,id:a.Da,is_servable:a.B,is_default:a.isDefault,is_translateable:a.D,vss_id:a.A};a.g&&(b.translationLanguage=a.g);return b},c1=function(a){return a.g?a.g.languageCode:a.i},Hoa=function(a,b){var c=new g.dz;
c.i=a.i;c.l=a.l;c.u=a.u;c.o=a.o;c.isDefault=!1;c.B=a.B;c.D=a.D;c.A=a.A;c.F=a.F;c.g=b;return c},d1=function(a){if(!Ioa.test(a))throw Error("'"+a+"' is not a valid hex color");
4==a.length&&(a=a.replace(Joa,"#$1$1$2$2$3$3"));a=a.toLowerCase();a=parseInt(a.substr(1),16);return[a>>16,a>>8&255,a&255]},Koa=function(){this.i=[];
this.g=[]},e1=function(a,b){return b?a.g.concat(a.i):a.g},f1=function(a,b){switch(b.o){case "asr":var c=a.i;
g.Wa(c,(0,g.z)(b.Oq,b))||c.push(b);break;default:c=a.g,g.Wa(c,(0,g.z)(b.Oq,b))||c.push(b)}},g1=function(){g.H.call(this);
this.i=new Koa;this.u=[]},h1=function(a,b,c){g1.call(this,a);
this.g=null;this.u=b.qu;this.l=c},i1=function(){this.Ta=[]},j1=function(a,b,c,d,e,f){g.H.call(this);
this.I=a;this.o=b;this.A=new i1;this.g=null;this.F=d;this.P=f;this.i=this.l=null;this.D=c;this.B=e||!1;this.H=new g.N(this.Cw,1E3,this);g.I(this,this.H);this.u=new g.Ir(this);g.I(this,this.u);g.R(g.W(b).experiments,"html5_disable_captions_seek_complete")?this.u.K(b,"seekto",this.mx):this.u.K(b,"seekcomplete",this.rF);this.mx(b.getCurrentTime());this.Cw()},k1=function(a,b){b-=a.o.oc();
var c=a.g;a.g=g.Ua(a.D.nf(b).g);c!=a.g&&a.P&&a.P()},l1=function(a,b){var c=g.rv(b,a.I,{}).Ib(),d={format:"RAW",
withCredentials:!0};a.B&&(d.responseType="arraybuffer");a.i=g.Wq(c,d,3,100).then((0,g.z)(a.WJ,a));a.l=b;c=a.A;d=a.l.g[0].i;var e=g.nb(c.Ta,d);0<=e||0>e&&1==(-e-1)%2||(e=-e-1,0<e&&1==d-c.Ta[e-1]&&e<c.Ta.length&&1==c.Ta[e]-d?(g.ab(c.Ta,e),g.ab(c.Ta,e-1)):0<e&&1==d-c.Ta[e-1]?c.Ta[e-1]=d:e<c.Ta.length&&1==c.Ta[e]-d?c.Ta[e]=d:(g.jb(c.Ta,e,0,d),g.jb(c.Ta,e+1,0,d)))},m1=function(a,b){g1.call(this,g.W(b));
this.g=a;this.B=b;this.l=null;this.o=!1;this.A=g.Py(g.W(this.B))&&!this.g.i},n1=function(a,b){var c=[],d;
for(d in a.g.g){var e=a.g.g[d];if(g.jU(e,b||null)){var f="en",k="English",l=".en",m="";if(e=e.info.captionTrack)f=e.languageCode,k=e.displayName,l=e.vssId,m=e.kind;c.push(new g.dz({id:d,languageCode:f,languageName:k,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:l,kind:m}))}}return c},Loa=function(a,b){return null!=b&&b in a.g.g?a.g.g[b]:null},o1=function(a,b,c){var d=[],e;
for(e in a.g.g){var f=a.g.g[e];if(g.jU(f,c||null)){var k=f.info.captionTrack;k&&k.languageCode==b&&d.push(f)}}return d.length?d[0]:null},p1=function(a,b,c,d,e){g1.call(this,e||null);
c=c||g.cq(a).hl||"";c=c.split("_").join("-");this.o=g.eq(a,{hl:c});this.l=b;this.A=!!d;this.B={};this.g=null},q1=function(a,b,c,d,e,f,k){f=void 0===f?!1:f;
k=void 0===k?null:k;g.mD.call(this,a,a+b,{priority:c,namespace:"captions"});this.windowId=d;this.text=e;this.l=f;this.i=k},r1=function(a,b,c,d,e){g.mD.call(this,a,a+b,{priority:c,
namespace:"captions"});this.id=d;this.params=e;this.i=[]},t1=function(a){a=void 0===a?{}:a;
var b="_"+s1++;return new r1(0,0x8000000000000,0,b,a)},v1=function(a,b,c,d,e,f){var k={};
g.Ra(k,b);g.Ra(k,a.params);g.Ra(k,c);var l={};g.Ra(l,b.xb);a.params.xb&&g.Ra(l,a.params.xb);g.Ra(l,c.xb);k.xb=l;g.U.call(this,{C:"div",G:"caption-window",L:{id:"caption-window-"+a.id,dir:1==k.te?"rtl":"ltr",tabindex:"0","aria-live":"assertive",lang:k.lang},J:[{C:"span",G:"captions-text",L:{style:"word-wrap: normal; display: block;"}}]});this.B=[];this.O=!1;this.o=a;this.V=this.R=null;this.Ra=e;this.Oa=f;this.D=null;this.X=.96*e;this.xa=.96*f;this.l=k;this.Ma=c;this.A=this.i["captions-text"];this.Ca=
null!=this.A.style["box-decoration-break"]||null!=this.A.style["-webkit-box-decoration-break"];this.Y=d/360*16;this.type=0;this.la=this.Y*u1(l);a=new g.Or(this.element,!0);g.I(this,a);a.subscribe("dragstart",this.qF,this);a.subscribe("dragmove",this.pF,this);a.subscribe("dragend",this.oF,this);this.ua=this.na=0;b="";this.l.windowOpacity&&(a=d1(this.l.windowColor),b="rgba("+a[0]+","+a[1]+","+a[2]+","+this.l.windowOpacity+")");a={"background-color":b,display:!1===this.l.isVisible?"none":"","text-align":Moa[this.l.textAlign]};
this.Ca&&(a["border-radius"]=b?this.la/8+"px":"");if(this.u=2==this.o.params.te||3==this.o.params.te)b=this.element,c="vertical-rl",1==this.l.lA&&(c="vertical-lr"),g.Ld&&(c="vertical-lr"==c?"tb-lr":"tb-rl"),g.uh(b,"-o-writing-mode",c),g.uh(b,"-webkit-writing-mode",c),g.uh(b,"writing-mode",c),g.uh(b,"text-orientation","upright"),g.K(b,"ytp-vertical-caption"),3==this.o.params.te&&(g.uh(b,"text-orientation",""),g.uh(b,"transform","rotate(180deg)"));g.uh(this.element,a);switch(this.l.Kf){case 0:case 1:case 2:g.K(this.element,
"ytp-caption-window-top");break;case 6:case 7:case 8:g.K(this.element,"ytp-caption-window-bottom")}},u1=function(a){var b=1+.25*(a.fontSizeIncrement||0);
if(0==a.offset||2==a.offset)b*=.8;return b},w1=function(a,b){var c={},d=b.background?b.background:a.l.xb.background;
if(null!=b.backgroundOpacity||b.background){var e=null!=b.backgroundOpacity?b.backgroundOpacity:a.l.xb.backgroundOpacity;d=d1(d);c.background="rgba("+d[0]+","+d[1]+","+d[2]+","+e+")";a.Ca&&(c["box-decoration-break"]="clone",c["border-radius"]=a.la/8+"px")}if(null!=b.fontSizeIncrement||null!=b.offset)c["font-size"]=a.Y*u1(b)+"px";d=1;e=b.color||a.l.xb.color;if(b.color||null!=b.textOpacity)e=d1(e),d=null==b.textOpacity?a.l.xb.textOpacity:b.textOpacity,e="rgba("+e[0]+","+e[1]+","+e[2]+","+d+")",c.color=
e,c.fill=e;var f=b.charEdgeStyle;0==f&&(f=null);if(f){e="rgba(34, 34, 34, "+d+")";var k="rgba(204, 204, 204, "+d+")";b.zu&&(k=e=b.zu);var l=a.Y/16/2,m=Math.max(l,1),n=Math.max(2*l,1),p=Math.max(3*l,1),r=Math.max(5*l,1);d=[];switch(f){case 4:for(;p<=r;p+=l)d.push(n+"px "+n+"px "+p+"px "+e);break;case 1:n=2<=window.devicePixelRatio?.5:1;for(f=m;f<=p;f+=n)d.push(f+"px "+f+"px "+e);break;case 2:d.push(m+"px "+m+"px "+k);d.push("-"+m+"px -"+m+"px "+e);break;case 3:for(p=0;5>p;p++)d.push("0 0 "+n+"px "+
e)}c["text-shadow"]=d.join(", ")}e="";switch(b.fontFamily){case 1:e='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:e='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:e='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:e='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:e='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:e=g.Dq()?'"Carrois Gothic SC", sans-serif-smallcaps':
'"Arial Unicode Ms", Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:e='"YouTube Noto", Roboto, "Arial Unicode Ms", Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}e&&(c["font-family"]=e);e=b.offset;null==e&&(e=a.l.xb.offset);switch(e){case 0:c["vertical-align"]="sub";break;case 2:c["vertical-align"]="super"}7==b.fontFamily&&(c["font-variant"]="small-caps");b.bold&&(c["font-weight"]="bold");b.Je&&(c["font-style"]="italic");b.underline&&(c["text-decoration"]="underline");
b.tD&&(c.visibility="hidden");1==b.vD&&a.u&&(c["text-combine-upright"]="all",c["text-orientation"]="mixed",e=g.Ry||g.Sy,3==a.o.params.te?c.transform=e?"rotate(90deg)":"rotate(180deg)":e&&(c.transform="rotate(-90deg)"));return c},x1=function(a){a.D=g.Rd("SPAN");
g.uh(a.D,{display:"block"});g.K(a.D,"caption-visual-line");a.A.appendChild(a.D)},y1=function(a,b){var c=g.Rd("SPAN");
g.uh(c,{display:"inline-block","white-space":"pre-wrap"});g.uh(c,w1(a,b));c.classList.add("ytp-caption-segment");a.D.appendChild(c);c.previousElementSibling&&(g.uh(c.previousElementSibling,{"border-top-right-radius":"0","border-bottom-right-radius":"0"}),g.uh(c,{"border-top-left-radius":"0","border-bottom-left-radius":"0"}));return c},z1=function(a,b,c){a.O=a.O||!!c;
var d={};g.Ra(d,a.l.xb);g.Ra(d,c||b.i);g.Ra(d,a.Ma.xb);var e=!a.D;e&&x1(a);c=a.R&&a.V&&g.$b(d,a.V)?a.R:y1(a,d);for(var f=g.v(b.text),k=f?b.text.split("\n"):[b.text],l=0;l<k.length;l++){var m=0<l||!b.l,n=k[l];m&&!e?(x1(a),c=y1(a,d)):m&&e&&(e=!1);n&&c.appendChild(f?g.Sd(n):n)}if(!f)for(e=b.text.querySelectorAll("RT".toString()),f=0;f<e.length;f++)g.uh(e[f],w1(a,d)),g.uh(e[f],"font-size","50%");a.V=d;a.R=c;a.B.push(b)},A1=function(){},C1=function(){this.o=this.i=this.mode=this.l=0;
this.u=new B1(this);this.A=new B1(this);this.g=[];this.clear()},Noa=function(a,b,c){if(255==a&&255==b||!a&&!b)return{pl:a,
ql:b,result:0};a=D1[a];b=D1[b];if(a&128){if(!(b&128)&&0!=c.g&&c.i==b)return{pl:a,ql:b,result:1}}else if(b&128&&1<=a&&31>=a)return{pl:a,ql:b,result:2};return{pl:a,ql:b,result:3}},Ooa=function(a,b,c,d){255==b&&255==c||!b&&!c?(45==++a.o&&a.reset(),a.u.g.clear(),a.A.g.clear()):(a.o=0,E1(a.u,b,c,d))},Poa=function(a,b){a.g.sort(function(e,f){var k=e.time-f.time;
return 0==k?e.order-f.order:k});
for(var c=0;c<a.g.length;c++){var d=a.g[c];a.i=d.time;0==d.type?Ooa(a,d.tu,d.uu,b):1==d.type&&a.l&496&&E1(a.A,d.tu,d.uu,b)}a.g.length=0},F1=function(){this.g=0},G1=function(){this.i=this.l=this.g=0},H1=function(){this.timestamp=this.Ld=0},I1=function(a){this.l=[];
for(var b=0;15>=b;b++){this.l[b]=[];for(var c=0;32>=c;c++)this.l[b][c]=new H1}this.g=this.i=this.row=0;this.style=new F1;this.u=a;this.o=0},J1=function(a,b){if(3==a.style.g){for(var c=0,d=0,e=a.u.i+0,f="",k="",l=e,m=1;15>=m;++m){for(var n=!1,p=d?d:1;32>=p;++p){var r=a.l[m][p];
if(0!=r.Ld){0==c&&(c=m,d=p);n=String.fromCharCode(r.Ld);var u=r.timestamp;u<e&&(e=u);r.timestamp=l;k&&(f+=k,k="");f+=n;n=!0}if((0==r.Ld||32==p)&&n){k="\n";break}else if(d&&!n)break}if(c&&!n)break}f&&b.u(c,d,e,l,f)}else for(d=c=0,f=e=a.u.i+0,k=1;15>=k;++k)for(l="",m=1;32>=m;++m)if(p=a.l[k][m],r=p.Ld,0!=r&&(0==c&&(c=k,d=m),n=String.fromCharCode(r),u=p.timestamp,u<=e&&(e=u),l+=n,p.reset()),32==m||0==r)l&&b.u(c,d,e,f,l),e=f,l="",d=c=0},Uoa=function(a,b){switch(a){case 0:return Qoa[(b&127)-32];
case 1:return Roa[b&15];case 2:return Soa[b&31];case 3:return Toa[b&31]}return 0},K1=function(a){return a.l[a.row][a.i]},L1=function(a,b,c){2<=b&&1<a.i&&(--a.i,K1(a).Ld=0);
var d=K1(a);d.timestamp=a.u.i+0;d.Ld=Uoa(b,c);32>a.i&&a.i++},M1=function(a,b,c,d){for(var e=0;e<d;e++)for(var f=0;32>=f;f++)a.l[b+e][f].Sf(a.l[c+e][f])},N1=function(a,b,c){for(var d=0;d<c;d++)for(var e=0;32>=e;e++)a.l[b+d][e].reset()},O1=function(a){a.row=0<a.g?a.g:1;
a.i=1;N1(a,0,15)},P1=function(a){this.o=a;
this.u=0;this.style=new F1;this.A=new I1(a);this.B=new I1(a);this.D=new I1(a);this.i=this.A;this.l=this.B;this.g=this.i},Q1=function(a,b,c){var d=a.i,e=!1;
switch(a.style.get()){case 4:if(0<d.g)break;case 1:case 2:J1(d,c),O1(a.i),O1(a.l),d.row=15,d.g=b,e=!0}a.style.set(3);a.g=d;a.g.style=a.style;a.o.mode=1<<d.o;e?d.i=1:d.g!=b&&(d.g>b?(J1(d,c),N1(d,d.row-d.g,b)):d.row<b&&(b=d.g),d.g=b)},R1=function(a){a.style.set(1);
a.g=a.l;a.g.g=0;a.g.style=a.style;a.o.mode=1<<a.g.o},S1=function(a){a.style.set(4);
a.g=a.D;a.g.style=a.style;a.o.mode=1<<a.g.o},B1=function(a){this.i=a;
this.g=new G1;this.u=0;this.l=new P1(a);this.A=new P1(a);this.o=this.l},E1=function(a,b,c,d){a.g.update();
b=Noa(b,c,a.g);switch(b.result){case 0:return;case 1:case 2:return}var e=b.pl;c=b.ql;if(32<=e||!e)a.i.mode&a.i.l&&(b=e,b&128&&(b=127),c&128&&(c=127),a=a.o.g,b&96&&L1(a,0,b),c&96&&L1(a,0,c),0!=b&&0!=c&&3==a.style.g&&J1(a,d));else if(e&16)a:if(!a.g.matches(e,c)&&(b=a.g,b.l=e,b.i=c,b.g=2,b=e&8?a.A:a.l,a.o=b,a.i.mode=1<<(a.u<<2)+(b.u<<1)+(4==b.style.g?1:0),(a.i.mode|1<<(a.u<<2)+(b.u<<1)+(4!=b.style.g?1:0))&a.i.l))if(c&64){d=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(e&7)<<1|c>>5&1];a=c&16?4*((c&14)>>1):
0;c=b.g;switch(b.style.get()){case 4:d=c.row;break;case 3:if(d!=c.row){if(d<c.g&&(d=c.g,d==c.row))break;var f=1+c.row-c.g,k=1+d-c.g;M1(c,k,f,c.g);b=f;e=c.g;k<f?(f=k+e-f,0<f&&(b+=f,e-=f)):(f=f+e-k,0<f&&(e-=f));N1(c,b,e)}}c.row=d;c.i=a+1}else switch(e&7){case 1:switch(c&112){case 32:L1(b.g,0,32);break a;case 48:57==c?(d=b.g,K1(d).Ld=0,32>d.i&&d.i++):L1(b.g,1,c&15)}break;case 2:c&32&&L1(b.g,2,c&31);break;case 3:c&32&&L1(b.g,3,c&31);break;case 4:case 5:if(32<=c&&47>=c)switch(c){case 32:R1(b);break;case 33:d=
b.g;1<d.i&&(--d.i,K1(d).Ld=0);break;case 36:d=b.g;b=K1(d);for(a=0;15>=a;a++)for(c=0;32>=c;c++)if(d.l[a][c]==b){for(;32>=c;c++)d.l[a][c].reset();break}break;case 37:Q1(b,2,d);break;case 38:Q1(b,3,d);break;case 39:Q1(b,4,d);break;case 40:L1(b.g,0,32);break;case 41:b.style.set(2);b.g=b.i;b.g.g=0;b.g.style=b.style;b.o.mode=1<<b.g.o;break;case 42:d=b.D;d.g=15;d.style.set(4);O1(d);S1(b);break;case 43:S1(b);break;case 44:a=b.i;switch(b.style.get()){case 1:case 2:case 3:J1(a,d)}N1(a,0,15);break;case 45:b:{a=
b.g;switch(b.style.get()){default:case 2:case 1:break b;case 4:if(15>a.row){++a.row;a.i=1;break b}case 3:}2>a.g&&(a.g=2,a.row<a.g&&(a.row=a.g));b=a.row-a.g+1;J1(a,d);M1(a,b,b+1,a.g-1);N1(a,a.row,1)}break;case 46:N1(b.l,0,15);break;case 47:J1(b.i,d),b.l.updateTime(b.o.i+0),d=b.l,b.l=b.i,b.i=d,R1(b)}break;case 7:switch(c){case 33:case 34:case 35:d=b.g,32<(d.i+=c&3)&&(d.i=32)}}},T1=function(a){g.H.apply(this,arguments)},U1=function(a){T1.call(this);
this.l={};this.F={};this.H={};this.u="_"+s1++;this.A=a;this.D={};this.i=this.g=null;this.B=!0},V1=function(a,b){var c=a.getAttribute(b);
if(null!=c)return parseFloat(c)},W1=function(a,b){var c=a.getAttribute(b);
if(null!=c)return"1"==c},X1=function(a,b){var c=V1(a,b);
return void 0!=c?c:null},Z1=function(a,b){var c=a.getAttribute(b);
if(null!=c)return Y1.test(c),c},$1=function(a,b){var c={},d=b.getAttribute("ws");
g.Ra(c,d?a.H[d]:a.A);d=X1(b,"mh");null!=d&&(c.Jq=d);d=X1(b,"ju");null!=d&&(c.textAlign=d);d=X1(b,"pd");null!=d&&(c.te=d);d=X1(b,"sd");null!=d&&(c.lA=d);d=Z1(b,"wfc");null!=d&&(c.windowColor=d);d=V1(b,"wfo");void 0!=d&&(c.windowOpacity=d/255);return c},a2=function(a,b){var c={},d=b.getAttribute("wp");
d&&g.Ra(c,a.F[d]);d=X1(b,"ap");null!=d&&(c.Kf=d);d=V1(b,"cc");null!=d&&(c.Bl=d);d=V1(b,"ah");null!=d&&(c.Ke=d);d=V1(b,"rc");null!=d&&(c.vk=d);d=V1(b,"av");null!=d&&(c.vg=d);return c},b2=function(a,b,c,d){var e={};
g.Ra(e,a2(a,b));g.Ra(e,$1(a,b));d?g.$b(e,a.A)?(d=a.u,e=a.A):d="_"+s1++:d=b.getAttribute("id")||"_"+s1++;a=V1(b,"t")+c;b=V1(b,"d")||0x8000000000000;if(2==e.te||3==e.te)c=e.vk,e.vk=e.Bl,e.Bl=c;return new r1(a,b,0,d,e)},c2=function(a,b,c,d,e,f,k){v1.call(this,a,b,c,d,e,f,k);
this.type=1},d2=function(a,b,c){this.B=c;
this.version=this.A=this.o=this.g=0;this.i=new DataView(a);this.l=[]},e2=function(a){var b=a.g;
a.g+=1;return a.i.getUint8(b)},f2=function(a){var b=a.g;
a.g+=4;return a.i.getUint32(b)},g2=function(a,b){T1.call(this);
this.i=a;this.track="CC3"==b.l?4:0;this.g=new C1;this.g.l=1<<this.track},i2=function(a){if(g.v(a))return!1;
a=new d2(a,8,0);return h2(a)},h2=function(a){if(!(a.g<a.i.byteLength)||1380139777!=f2(a))return!1;
a.version=e2(a);if(1<a.version)return!1;e2(a);e2(a);e2(a);return!0},j2=function(a,b,c,d,e,f,k){v1.call(this,a,b,c,d,e,f,k);
g.K(this.element,"ytp-caption-window-rollup");this.type=2;this.F=[];this.I=this.H=this.ba=0;this.M=NaN;this.ya=0;this.Fa=null;this.ha=new g.N(this.bK,433,this);g.I(this,this.ha)},Voa=function(a,b){return(a.u?b.offsetHeight:b.offsetWidth)+1},Woa=function(a){if(isNaN(a.M)){var b=a.l.Bl;
if(b){var c=g.Rd("SPAN");g.ae(c,"\u2013".repeat(b));g.uh(c,w1(a,a.l.xb));a.A.appendChild(c);a.M=c.offsetWidth;a.A.removeChild(c)}else a.M=0}return a.M},Xoa=function(a,b){if(!b)return"";
a.u&&1!=a.o.params.lA&&(b*=-1);return"translate"+(a.u?"X":"Y")+"("+b+"px)"},k2=function(a){a.F=[].concat(g.ea(document.getElementsByClassName("caption-visual-line")));
for(var b=a.o.params.vk,c=0,d=0,e=a.F.length-1;c<b&&-1<e;){var f=a.F[e];d+=a.u?f.offsetWidth:f.offsetHeight;c++;e--}a.F.length<b&&(d*=b/a.F.length);a.H=d;a.I=Math.max(Woa(a),a.ya,Voa(a,a.A))},Yoa=function(a,b){k2(a);
var c=a.F.reduce(function(e,f){return(a.u?f.offsetWidth:f.offsetHeight)+e},0);
c=a.H-c;if(c!=a.ba){var d=0<c&&0==a.ba;b||isNaN(c)||d||(g.K(a.element,"ytp-rollup-mode"),g.eo(a.ha));g.uh(a.A,"transform",Xoa(a,c));a.ba=c}k2(a)},l2=function(){T1.call(this)},m2=function(a,b,c,d,e,f,k,l,m){switch(k.tagName){case "b":l.bold=!0;
break;case "i":l.Je=!0;break;case "u":l.underline=!0}for(var n=0;n<k.childNodes.length;n++){var p=k.childNodes[n];if(3==p.nodeType){p=new q1(b,c,d,e.id,p.nodeValue,f||0<n,g.Wb(l)?void 0:l);m.push(p);var r=e;g.I(r,p);r.i.push(p)}else r={},g.Ra(r,l),m2(a,b,c,d,e,!0,p,r,m)}},n2=function(a){var b=0;
a=g.q(a.split(":"));for(var c=a.next();!c.done;c=a.next())b=60*b+parseFloat(c.value);return 1E3*b},o2=function(a,b,c,d){d=Object.assign({Jq:0},d);
return new r1(a,b,c,"_"+s1++,d)},p2=function(a){g.H.call(this);
this.i=a;this.g=null},s2=function(a){g.TJ.call(this,a);
this.u=g.W(a);this.l=a.getVideoData();this.xa=g.pJ(a);this.I=a;var b=null,c=g.Qo("yt-html5-player-modules::subtitlesModuleData");c&&(b=new g.Ao(c));this.aa=b;this.o={xb:{}};this.A={xb:{}};this.H=[];this.M={};this.V={};this.P=!1;this.na=g.kU(this.l,this.I);this.ya=!!this.l.captionTracks.length;this.Ca=!!this.l.Xi;this.la="3"==this.u.l;b=a.app.o;c=!(!b||!b.Ik());this.ua=!(!b||!b.th());this.B=this.la&&c&&!this.na;this.R=!this.B&&this.la&&this.ua&&this.na;this.i=this.D=this.F=this.O=this.ha=null;this.Y=
new p2(this.u);g.I(this,this.Y);c=b=this.g=null;this.B||(b=new g.ao(this.BA,void 0,this),g.I(this,b),c=new g.N(this.xL,2E3,this),g.I(this,c));this.X=b;this.ba=c;this.ca=new g.Ir(this);g.I(this,this.ca);this.B||this.ca.K(a,"resize",this.Os);this.ca.K(a,"onPlaybackAudioChange",this.yH);this.ca.K(a,g.pD("captions"),this.AE,this);this.ca.K(a,"crx_captions",this.BE,this);q2(this,r2(this,"display-settings")||{})},t2=function(a){if(1==a.u.Of||1==a.l.Of||"alwayson"==g.eB(a.l,"yt:cc"))return!0;
if(2==a.u.Of){var b=r2(a,"module-enabled");if(null!=b)return!!b}if(a.l.captionTracks.length)var c=a.player.getAudioTrack().To;return"ON"==c||"on"==g.eB(a.l,"yt:cc")},u2=function(a,b){if(a.g&&(void 0===b||!b)||!a.l.captionTracks.length)return!1;
var c=a.player.getAudioTrack();return!!c.Kl||"FORCED_ON"==c.To},w2=function(a,b){if(a.i){if(a.D&&a.D.g)return a.D.g;
var c=b;c||(c=a.Ca?!1:a.ya?!1:!0);c=e1(a.i.i,c);for(var d=[a.l.Nf,a.u.Nf,g.eB(a.l,"yt:cc_default_lang")],e=0;e<d.length;e++)for(var f=0;f<c.length;f++)if(c1(c[f])==d[e])return c[f];return a.D&&a.D.kp?a.D.kp:(d=c.find(function(k){return k.isDefault}))?d:c[0]||v2(a)}return null},v2=function(a){return a.D&&a.D.Kl},x2=function(a){var b=v2(a);
return!!b&&a.g==b},y2=function(a,b){for(var c=a.I.app.o.ka().textTracks,d=a.g.toString(),e=0;e<c.length;e++){var f=c[e];
f.id==d&&(b?"showing"!=f.mode&&(f.mode="showing"):"showing"==f.mode&&(f.mode="disabled"))}},A2=function(a,b,c){a.loaded&&a.unload();
null!=c&&(a.P=c,a.P&&z2(a,"module-enabled",!!b));a.g=b;u2(a)&&(a.g=v2(a));a.load()},Zoa=function(a,b){var c=a.xa.getVideoContentRect(!0).height;
if(!c)return null;var d=a.xa.getPlayerSize();switch(null!=b.params.Jq?b.params.Jq:1<b.i.length?1:0){case 1:return new c2(b,a.o,a.A,c,d.width,d.height,a.u.experiments);case 2:return new j2(b,a.o,a.A,c,d.width,d.height,a.u.experiments);default:return new v1(b,a.o,a.A,c,d.width,d.height,a.u.experiments)}},q2=function(a,b,c){var d=B2.xb;
a.o={};g.Ra(a.o,B2);a.o.xb={};g.Ra(a.o.xb,d);a.A={xb:{}};var e=b.backgroundOverride?a.A:a.o,f=b.background||d.background;Y1.test(f);e.xb.background=f;e=b.colorOverride?a.A:a.o;f=b.color||d.color;Y1.test(f);e.xb.color=f;e=b.windowColorOverride?a.A:a.o;f=b.windowColor||B2.windowColor;Y1.test(f);e.windowColor=f;e=b.backgroundOpacityOverride?a.A:a.o;f=b.backgroundOpacity;null==f&&(f=d.backgroundOpacity);e.xb.backgroundOpacity=f;e=b.fontSizeIncrementOverride?a.A:a.o;f=b.fontSizeIncrement;null==f&&(f=d.fontSizeIncrement);
e.xb.fontSizeIncrement=f;f=b.fontStyleOverride?a.A:a.o;e=b.fontStyle;null==e&&(e=d.bold&&d.Je?3:d.bold?1:d.Je?2:0);f=f.xb;switch(e){case 1:f.bold=!0;delete f.Je;break;case 2:delete f.bold;f.Je=!0;break;case 3:f.bold=!0;f.Je=!0;break;default:delete f.bold,delete f.Je}e=b.textOpacityOverride?a.A:a.o;f=b.textOpacity;null==f&&(f=d.textOpacity);e.xb.textOpacity=f;e=b.windowOpacityOverride?a.A:a.o;f=b.windowOpacity;null==f&&(f=B2.windowOpacity);e.windowOpacity=f;e=b.charEdgeStyleOverride?a.A:a.o;f=b.charEdgeStyle;
null==f&&(f=d.charEdgeStyle);e.xb.charEdgeStyle=f;e=b.fontFamilyOverride?a.A:a.o;f=b.fontFamily;null==f&&(f=d.fontFamily);e.xb.fontFamily=f;a.loaded&&a.Os();c&&z2(a,"display-settings",b)},D2=function(a,b){if(b&&!a.F){var c=t1({te:0,
lang:"en-GB"});a.F=[c,new q1(c.start,c.end-c.start,0,c.id,"Captions look like this")];g.yJ(a.player,a.F)}else!b&&a.F&&(C2(a,a.F),a.F=null)},C2=function(a,b){g.AJ(a.player,b);
(0,g.B)(b,function(c){g.bb(this.H,c)},a);
a.X.xj()},r2=function(a,b){if(!a.aa)return null;
try{var c=a.aa.get(b)}catch(d){a.aa.remove(b)}return c},z2=function(a,b,c){if(a.aa)try{a.aa.set(b,c)}catch(d){}};
g.yD.prototype.Zi=g.ca(13,function(){for(var a=g.Ed(document,"track",void 0,this.g),b=0;b<a.length;b++)g.Wd(a[b])});
g.cW.prototype.Zi=g.ca(12,function(){this.g.Zi()});
g.yD.prototype.Ik=g.ca(11,function(){return!!this.g.textTracks});
g.cW.prototype.Ik=g.ca(10,function(){return this.g.Ik()});
g.yD.prototype.Si=g.ca(9,function(a){for(var b=0;b<a.length;b++)this.g.appendChild(a[b])});
g.cW.prototype.Si=g.ca(8,function(a){this.g.Si(a)});
g.oC.prototype.th=g.ca(7,function(){});
g.yD.prototype.th=g.ca(6,function(){return!(!this.g.textTracks||!this.g.textTracks.addEventListener)});
g.cW.prototype.th=g.ca(5,function(){return this.g.th()});
g.dz.prototype.Oq=g.ca(3,function(a){return a?this.toString()==a.toString():!1});
g.gt.prototype.Tl=g.ca(2,function(a){return(a=this.Vf(a))?a.i:0});
g.cw.prototype.Tl=g.ca(1,function(){return 0});
var $oa=/^(ar|ckb|dv|he|iw|fa|nqo|ps|sd|ug|ur|yi|.*[-_](Adlm|Arab|Hebr|Nkoo|Rohg|Thaa))(?!.*[-_](Latn|Cyrl)($|-|_))($|-|_)/i,Joa=/#(.)(.)(.)/,Ioa=/^#(?:[0-9a-f]{3}){1,2}$/i,Y1=/^#(?:[0-9a-f]{3}){1,2}$/i;g.t(g1,g.H);g1.prototype.hz=function(){return!1};
g1.prototype.T=function(){this.wg();g.H.prototype.T.call(this)};
g.t(h1,g1);h1.prototype.Fq=function(a,b,c){b=this.tj(a,b);var d=(0,g.z)(function(e){this.g=null;c(e.responseText,a)},this);
this.wg();this.g=g.vq(b,{format:"RAW",onSuccess:d,withCredentials:!0})};
h1.prototype.Gq=function(a){if(this.l)for(var b=g.q(this.l.captionTracks),c=b.next();!c.done;c=b.next())f1(this.i,c.value);a()};
h1.prototype.tj=function(a,b){var c=a.Ib(),d={fmt:b};a.g&&(d.tlang=c1(a));return g.eq(c,d)};
h1.prototype.wg=function(){this.g&&this.g.abort()};
i1.prototype.contains=function(a){a=g.nb(this.Ta,a);return 0<=a||0>a&&1==(-a-1)%2};
i1.prototype.length=function(){return this.Ta.length/2};
g.t(j1,g.H);g.h=j1.prototype;g.h.T=function(){g.H.prototype.T.call(this);this.i&&this.i.cancel()};
g.h.mx=function(a){var b=this;if(this.D.Vg())var c=this.u.K(this.o,"progresssync",function(){b.D.index.Fb()&&(b.reset(),b.g=null,k1(b,b.o.getCurrentTime()),b.u.Na(c))});
else k1(this,a)};
g.h.rF=function(){k1(this,this.o.getCurrentTime())};
g.h.reset=function(){this.A=new i1;this.i&&(this.i.cancel(),this.i=null)};
g.h.Cw=function(){var a;if(a=null!==this.g)a=this.g,a=a.g.yf(a);!a||this.i||this.g&&30<this.g.startTime-this.o.getCurrentTime()||(a=this.g,a=a.g.di(a),a.g[0].duration&&(this.A.contains(a.g[0].i)||l1(this,a),this.g=g.Ua(a.g)));this.H.start()};
g.h.WJ=function(a){var b=!(this.B?a.response:a.responseText)||400<=a.status,c=g.jw(a);c?(a=g.rv(this.l,this.I,{}),b=this.l,g.mv(b.i,a,c),b.requestId=a.get("req_id"),l1(this,this.l)):(b||null===this.F||(this.B?this.F(a.response,1E3*(this.l.g[0].startTime+this.o.oc())):this.F(a.responseText,1E3*(this.l.g[0].startTime+this.o.oc()))),this.i=this.l=null)};
g.t(m1,g1);g.h=m1.prototype;g.h.Fq=function(a,b,c){this.wg();b=Loa(this,a.getId());b||(b=a.i,b=this.g.i?o1(this,b,"386"):o1(this,b));if(b){var d=1E3*(b.index.Tl(b.index.ie())-b.index.Jc(b.index.ie()));this.l=new j1(new g.Ju,this.B,b,function(e,f){c(e,a,f,d)},this.A||g.Bu(b.info),(0,g.z)(function(){this.l&&this.l.reset();
this.o=!0},this))}};
g.h.hz=function(){var a=this.o;this.o=!1;return a};
g.h.Gq=function(a){var b;this.A?b=[new g.dz({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.dz({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]:b=this.g.i?n1(this,"386"):n1(this);b=g.q(b);for(var c=b.next();!c.done;c=b.next())f1(this.i,c.value);a()};
g.h.wg=function(){this.l&&(this.l.dispose(),this.l=null)};
g.h.tj=function(){return""};
g.t(p1,g1);p1.prototype.Fq=function(a,b,c){b=this.tj(a,b);var d=(0,g.z)(function(e){this.g=null;c(e.responseText,a)},this);
this.wg();this.g=g.vq(b,{format:"RAW",onSuccess:d,withCredentials:!0})};
p1.prototype.Gq=function(a){var b=this.o,c={type:"list",tlangs:1,v:this.l,vssids:1};this.A&&(c.asrs=1);b=g.eq(b,c);c=(0,g.z)(function(d){this.g=null;if((d=d.responseXML)&&d.firstChild){for(var e=g.q(d.getElementsByTagName("track")),f=e.next();!f.done;f=e.next()){var k=f.value;f=k.getAttribute("lang_code");var l=k.getAttribute("lang_translated"),m=k.getAttribute("name"),n=k.getAttribute("kind"),p=k.getAttribute("id"),r="true"==k.getAttribute("lang_default"),u="true"==k.getAttribute("cantran");k=k.getAttribute("vss_id");
f1(this.i,new g.dz({languageCode:f,languageName:l,name:m,kind:n,id:p,is_servable:!0,is_translateable:u,vss_id:k,is_default:r}))}d=d.getElementsByTagName("target");e=d.length;for(f=0;f<e;f++)l=d[f].getAttribute("lang_code"),m=d[f].getAttribute("lang_translated"),n=d[f].getAttribute("lang_original"),p=d[f].getAttribute("id"),r="true"==d[f].getAttribute("lang_default"),l={languageCode:l,languageName:m,languageOriginal:n,id:p,isDefault:r},this.B[l.languageCode]=l.languageName,this.u.push(l)}a()},this);
this.wg();this.g=g.vq(b,{format:"RAW",onSuccess:c,withCredentials:!0})};
p1.prototype.tj=function(a,b){var c=this.o,d={v:this.l,type:"track",lang:a.i,name:a.getName(),kind:a.o,fmt:b};a.g&&(d.tlang=c1(a));return c=g.eq(c,d)};
p1.prototype.wg=function(){this.g&&this.g.abort()};var Moa=["left","right","center","justify"];var B2={windowColor:"#080808",windowOpacity:0,textAlign:2,Kf:7,Ke:50,vg:100,xb:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.t(q1,g.mD);q1.prototype.toString=function(){return g.mD.prototype.toString.call(this)};g.t(r1,g.mD);r1.prototype.toString=function(){return g.mD.prototype.toString.call(this)};
var s1=0;g.t(v1,g.U);g.h=v1.prototype;g.h.qF=function(a,b){var c=g.Kh(this.element,this.element.parentElement);this.na=a-c.x;this.ua=b-c.y;g.K(this.element,"ytp-dragging")};
g.h.pF=function(a,b){var c=g.Nh(this.element),d=a-this.na-.02*this.Ra,e=b-this.ua-.02*this.Oa,f=(d+c.width/2)/this.X*3;f=Math.floor(g.pd(f,0,2));var k=(e+c.height/2)/this.xa*3;k=Math.floor(g.pd(k,0,2));var l=f+3*k;d=(d+f/2*c.width)/this.X;d=100*g.pd(d,0,1);c=(e+k/2*c.height)/this.xa;c=100*g.pd(c,0,1);this.o.params.Kf=l;this.o.params.vg=c;this.o.params.Ke=d;this.l.Kf=l;this.l.vg=c;this.l.Ke=d;this.Dz()};
g.h.oF=function(){g.Vn(this.element,"ytp-dragging")};
g.h.Dz=function(){this.qh(this.B)};
g.h.qh=function(a){var b=Math.min(this.Dv(),this.X),c=this.Cv(),d="";3==this.o.params.te&&(d="rotate(180deg)");g.uh(this.element,{top:0,left:0,right:"",bottom:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"96%","max-height":"96%",margin:"",transform:""});this.Ho(a);a={transform:d,top:"",left:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"","max-height":""};var e=.96*this.l.Ke+2;d=this.l.Kf;switch(d){case 0:case 3:case 6:a.left=e+"%";break;case 1:case 4:case 7:a.left=e+"%";e=this.A.offsetWidth;
b||e?(b=b||e+1,a.width=b+"px",a["margin-left"]=b/-2+"px"):a.transform+=" translateX(-50%)";break;case 2:case 5:case 8:a.right=100-e+"%"}b=.96*this.l.vg+2;switch(d){case 0:case 1:case 2:a.top=b+"%";break;case 3:case 4:case 5:a.top=b+"%";(c=c||this.element.clientHeight)?(a.height=c+"px",a["margin-top"]=c/-2+"px"):a.transform+=" translateY(-50%)";break;case 6:case 7:case 8:a.bottom=100-b+"%"}g.uh(this.element,a)};
g.h.Ho=function(a){var b;for(b=0;b<a.length&&a[b]==this.B[b];b++);if(this.O||this.B.length>b)b=0,this.O=!1,this.B=[],this.D=this.V=this.R=null,g.Ud(this.A);for(;b<a.length;b++)z1(this,a[b])};
g.h.Dv=function(){return 0};
g.h.Cv=function(){return 0};
g.h.toString=function(){return g.U.prototype.toString.call(this)};A1.prototype.u=function(){};C1.prototype.clear=function(){this.o=this.i=this.mode=0;this.g=[];this.reset()};
C1.prototype.reset=function(){this.mode=0;this.u.reset(0);this.A.reset(1)};
var D1=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];F1.prototype.set=function(a){this.g=a};
F1.prototype.get=function(){return this.g};
G1.prototype.clear=function(){this.g=0};
G1.prototype.update=function(){this.g=2==this.g?1:0};
G1.prototype.matches=function(a,b){return 0!=this.g&&a==this.l&&b==this.i};
H1.prototype.Sf=function(a){this.Ld=a.Ld;this.timestamp=a.timestamp};
H1.prototype.reset=function(){this.timestamp=this.Ld=0};
I1.prototype.updateTime=function(a){for(var b=1;15>=b;++b)for(var c=1;32>=c;++c)this.l[b][c].timestamp=a};
I1.prototype.debugString=function(){for(var a="\n",b=1;15>=b;++b){for(var c=1;32>=c;++c){var d=this.l[b][c];a=0==d.Ld?a+"_":a+String.fromCharCode(d.Ld)}a+="\n"}return a};
I1.prototype.reset=function(a){for(var b=0;15>=b;b++)for(var c=0;32>=c;c++)this.l[b][c].reset();this.o=a;this.g=0;this.i=this.row=1};
var Qoa=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],Roa=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],Soa=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],Toa=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];P1.prototype.reset=function(a,b){this.u=b;this.style.set(2);this.i=this.A;this.l=this.B;this.g=this.i;var c=(a<<2)+(b<<1);this.A.reset(c);this.B.reset(c);this.D.reset((a<<2)+(b<<1)+1)};
B1.prototype.reset=function(a){this.u=a;this.g.clear();this.o=this.l;this.l.reset(a,0);this.A.reset(a,1)};g.t(T1,g.H);T1.prototype.reset=function(){};g.t(U1,T1);U1.prototype.reset=function(){this.D={};this.i=this.g=null;this.B=!0};
U1.prototype.o=function(a,b){var c=a.firstChild;c.getAttribute("format");b=b||0;Number.isFinite(b);c=Array.from(c.childNodes);c=g.q(c);for(var d=c.next();!d.done;d=c.next())if(d=d.value,1==d.nodeType)switch(d.tagName){case "head":var e=d;break;case "body":var f=d}if(e)for(e=Array.from(e.childNodes),e=g.q(e),c=e.next();!c.done;c=e.next())if(c=c.value,1==c.nodeType)switch(c.tagName){case "pen":d=c.getAttribute("id");var k=this.l,l={},m=c.getAttribute("p");m&&g.Ra(l,this.l[m]);m=W1(c,"b");null!=m&&(l.bold=
m);m=W1(c,"i");null!=m&&(l.Je=m);m=W1(c,"u");null!=m&&(l.underline=m);m=X1(c,"et");null!=m&&(l.charEdgeStyle=m);m=X1(c,"of");null!=m&&(l.offset=m);m=Z1(c,"bc");null!=m&&(l.background=m);m=Z1(c,"ec");null!=m&&(l.zu=m);m=Z1(c,"fc");null!=m&&(l.color=m);m=X1(c,"fs");null!=m&&0!=m&&(l.fontFamily=m);m=V1(c,"sz");void 0!=m&&(l.fontSizeIncrement=m/100-1);m=V1(c,"bo");void 0!=m&&(l.backgroundOpacity=m/255);m=V1(c,"fo");void 0!=m&&(l.textOpacity=m/255);m=X1(c,"rb");null!=m&&(l.wk=m);c=X1(c,"hg");null!=c&&
(l.vD=c);k[d]=l;break;case "ws":d=c.getAttribute("id");this.H[d]=$1(this,c);break;case "wp":d=c.getAttribute("id"),this.F[d]=a2(this,c)}if(f){e=b;c=[];f=Array.from(f.childNodes);f=g.q(f);for(d=f.next();!d.done;d=f.next())if(d=d.value,1==d.nodeType)switch(d.tagName){case "w":this.g=b2(this,d,e,!1);g.I(this,this.g);(d=this.D[this.g.id])&&d.end>this.g.start&&(d.end=this.g.start);this.D[this.g.id]=this.g;c.push(this.g);break;case "p":var n=e;k=[];l=d.getAttribute("w")||this.u;m=!!W1(d,"a");n=(V1(d,"t")||
0)+n;var p=V1(d,"d")||5E3;m||(!this.B&&this.i&&this.i.windowId==l&&this.i.end>n&&(this.i.end=n),this.i&&"\n"==this.i.text&&(this.i.text=""));var r=m?6:5,u=this.l[d.getAttribute("p")],y=d.childNodes;y.length&&(this.B=null!=d.getAttribute("d"));for(var D=0;D<y.length;D++){var F=y[D];0<D&&(m=!0);var E=void 0;1==F.nodeType&&(E=F);if(E&&"s"==E.tagName)if((F=this.l[E.getAttribute("p")])&&1==F.wk){F=n;var L=p,O=l,pa=m,za=r;var Ka=E;var fd=y[D+1];var wd=y[D+2],kc=y[D+3];Ka.getAttribute("p");V1(Ka,"t");V1(fd,
"t");V1(wd,"t");V1(kc,"t");E=g.Rd("RUBY");Ka=Ka.textContent;var Rk=g.Rd("SPAN");Rk.innerText=Ka;E.appendChild(Rk);fd.getAttribute("p");Rk=g.Rd("RP");Ka=fd.textContent;Rk.innerText=Ka;E.appendChild(Rk);fd=this.l[wd.getAttribute("p")];Ka=wd.textContent;wd=g.Rd("RT");wd.innerText=Ka;E.appendChild(wd);if(4==fd.wk||6==fd.wk)g.uh(E,"ruby-position","over"),g.uh(E,"-webkit-ruby-position","before");else if(5==fd.wk||7==fd.wk)g.uh(E,"ruby-position","under"),g.uh(E,"-webkit-ruby-position","after");kc.getAttribute("p");
Ka=kc.textContent;kc=g.Rd("RP");kc.innerText=Ka;E.appendChild(kc);F=new q1(F,L,za,O,E,pa,null);D+=3}else kc=E,F=n,L=p,O=l,pa=m,za=r,E=kc.textContent?kc.textContent:"",Ka=this.l[kc.getAttribute("p")],kc=V1(kc,"t")||0,F=new q1(F+kc,L-kc,za,O,E,pa,Ka);else F=new q1(n,p,r,l,F.textContent||"",m,u);k.push(F);this.i=F}if(0<k.length)for(k[0].windowId==this.u&&(this.g=b2(this,d,e,!0),g.I(this,this.g),c.push(this.g)),d=g.q(k),k=d.next();!k.done;k=d.next())k=k.value,k.windowId=this.g.id,l=this.g,g.I(l,k),l.i.push(k),
c.push(k)}e=c}else e=[];return e};g.t(c2,v1);c2.prototype.Ho=function(a){var b=this.o.i;v1.prototype.Ho.call(this,a);for(a=a.length;a<b.length;a++){var c=b[a];if(f&&c.i==e)var d=f;else{d={};g.Ra(d,c.i);g.Ra(d,apa);var e=c.i;var f=d}z1(this,c,d)}};
var apa={tD:!0};g.t(d2,A1);d2.prototype.u=function(a,b,c,d,e){if(c<d){var f="_"+s1++;c=c/1E3-this.B;d=d/1E3-this.B;a=new r1(c,d-c,5,f,{textAlign:0,Kf:0,Ke:2.5*b,vg:5.33*a});e=new q1(c,d-c,5,f,e);this.l.push(a);this.l.push(e)}};
g.t(g2,T1);g2.prototype.o=function(a){a=new d2(a,a.byteLength,this.i);if(h2(a)){for(;a.g<a.i.byteLength;)for(0==a.version?a.o=f2(a)*(1E3/45):1==a.version&&(a.o=4294967296*f2(a)+f2(a)),a.A=e2(a);0<a.A;a.A--){var b=e2(a),c=e2(a),d=e2(a);b&4&&(b&3)==this.track&&(0==this.track||1==this.track)&&(b=this.g,b.g.push({time:a.o,type:this.track,tu:c,uu:d,order:b.g.length}))}Poa(this.g,a);return a.l}return[]};
g2.prototype.reset=function(){this.g.clear()};g.t(j2,v1);g.h=j2.prototype;g.h.Dz=function(){g.fo(this.ha)};
g.h.bK=function(){g.Vn(this.element,"ytp-rollup-mode");this.qh(this.Fa,!0)};
g.h.Cv=function(){return this.u?this.I:this.H};
g.h.Dv=function(){return this.u?this.H:this.I};
g.h.qh=function(a,b){this.Fa=a;if(this.o.params.vk){for(var c=0,d=0;d<this.B.length&&c<a.length;d++)this.B[d]==a[c]&&c++;0<c&&c<a.length&&(a=this.B.concat(a.slice(c)));this.ya=this.I;this.H=this.I=0;v1.prototype.qh.call(this,a);Yoa(this,b);v1.prototype.qh.call(this,a)}else v1.prototype.qh.call(this,a)};g.t(l2,T1);
l2.prototype.o=function(a,b){for(var c=[],d=a.split(bpa),e=1;e<d.length;e++){var f=d[e],k=b;if(""!=f&&!cpa.test(f)){var l=E2.exec(f);if(l&&4<=l.length){var m=n2(l[1]),n=n2(l[2])-m;m+=k;var p,r=p=void 0,u=void 0,y=void 0,D=l[3];l={textAlign:2};D=g.q(D?D.split(" "):[]);for(var F=D.next();!F.done;F=D.next())if(F=F.value.split(":"),2==F.length){var E=F[1];switch(F[0]){case "line":F=E.split(",");F[0].endsWith("%")&&(y=F[0],l.vg=Number.parseInt(y,10),2==F.length&&(u=F[1].trim()));break;case "position":F=E.split(",");
r=F[0];l.Ke=Number.parseInt(r,10);2==F.length&&(p=F[1].trim());break;case "align":switch(E){case "start":l.textAlign=0;break;case "middle":l.textAlign=2;break;case "end":l.textAlign=1}}}y||(l.vg=100,u||(u="end"));if(!r)switch(l.textAlign){case 0:l.Ke=0;break;case 1:l.Ke=100;break;default:l.Ke=50}r=0;switch(u){case "center":r+=3;break;case "end":r+=6;break;default:r+=0}switch(p){case "line-left":r+=0;break;case "center":r+=1;break;case "line-right":r+=2;break;default:switch(l.textAlign){case 0:r+=
0;break;case 2:r+=1;break;case 1:r+=2}}l.Kf=0>r||8<r?7:r;p=l;f=f.substring(E2.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");r=p;p=f;f={};if(0>p.indexOf("<")&&0>p.indexOf("&"))k=o2(m,n,5,r),n=new q1(m,n,5,k.id,p,!1,g.Wb(f)?void 0:f),c.push(k),c.push(n),g.I(k,n),k.i.push(n);else for(u=p.split(dpa),1==u.length?(p=5,r=o2(m,n,p,r)):(y=p=6,r=Object.assign({Bl:32},r),r=new r1(m,n,y,"_"+s1++,r)),c.push(r),y=m,l=0;l<u.length;l++)D=u[l],0==l%2?(F=g.Xn("<html>"+D+"</html>"),F.getElementsByTagName("parsererror").length?
(E=F.createElement("span"),E.appendChild(F.createTextNode(D))):E=F.firstChild,m2(this,y,n-(y-m),p,r,0<l,E,f,c)):y=n2(D)+k}E2.lastIndex=0}}return c};
var cpa=/^NOTE/,bpa=/(?:\r\n|\r|\n){2,}/,E2=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),dpa=/<((?:[\d]{2}:)?[\d]{2}:[\d]{2}\.[\d]{3})>/;g.t(p2,g.H);p2.prototype.clear=function(){this.g&&this.g.dispose();this.g=null};
p2.prototype.reset=function(){this.g&&this.g.reset()};
p2.prototype.T=function(){this.clear();g.H.prototype.T.call(this)};g.t(s2,g.TJ);g.h=s2.prototype;g.h.T=function(){if(this.B||this.R){var a=this.I.app.o;a&&a.Zi()}else D2(this,!1);g.TJ.prototype.T.call(this)};
g.h.Bk=function(){return this.la?this.B||this.R:u2(this)?!0:t2(this)};
g.h.load=function(){g.TJ.prototype.load.call(this);this.D=this.player.getAudioTrack();if(this.i)this.g&&(this.Y.clear(),this.B?y2(this,!0):3!=this.player.getPresentingPlayerType()&&this.i.Fq(this.g,"srv3",(0,g.z)(this.IK,this))),this.g&&!x2(this)?this.player.ma("captionschanged",b1(this.g)):this.player.ma("onCaptionsTrackListChanged");else{var a;this.na?a=new m1(this.l.ga,this.player):this.ya?a=new h1(this.u,this.l,this.player.getAudioTrack()):a=new p1(this.l.Xi,this.l.videoId,this.l.Nf||this.u.Nf||
g.eB(this.l,"yt:cc_default_lang")||this.u.Vb,this.l.Ro,this.u);this.i=a;g.I(this,this.i);a.Gq((0,g.z)(this.HK,this))}};
g.h.unload=function(){this.B&&this.g?y2(this,!1):(this.ba&&g.go(this.ba),g.BJ(this.player,"captions"),this.H=[],this.i&&this.i.wg(),this.Y.clear(),this.F&&g.yJ(this.player,this.F),this.Os());g.TJ.prototype.unload.call(this);var a=g.X(this.player.app);a&&a.o&&g.cC(a.o.l);this.player.ma("captionschanged",{})};
g.h.HK=function(){var a;this.P||t2(this)?a=w2(this,this.P):u2(this)&&(a=v2(this));if(this.B||this.R){for(var b=e1(this.i.i,!0),c=[],d=0;d<b.length;d++){var e=b[d],f={kind:"subtitles",label:g.ez(e),srclang:c1(e),id:e.toString()};this.R||(f.src=this.i.tj(e,"vtt"));e==a&&(f["default"]=1);c.push(g.Qd("TRACK",f))}this.I.app.o.Si(c);a=this.I.app.o.ka();this.ua&&this.ca.K(a.textTracks,"change",this.JK)}else!this.g&&a&&A2(this,a),this.player.ma("onCaptionsTrackListChanged"),this.player.ma("onApiChange")};
g.h.JK=function(){for(var a=this.I.app.o.ka().textTracks,b=null,c=0;c<a.length;c++)if("showing"==a[c].mode)a:{b=e1(this.i.i,!0);for(var d=0;d<b.length;d++)if(b[d].toString()==a[c].id){b=b[d];break a}b=null}(this.loaded?this.g:null)!=b&&A2(this,b,!0)};
g.h.dM=function(){!this.g&&this.B||this.unload()};
g.h.IK=function(a,b,c,d){if(a){this.i.hz()&&(this.H=[],g.BJ(this.I,"captions"),this.X.xj(),this.Y.reset());var e=this.Y;c=c||0;d=d||0;if(!g.v(a)){var f=new DataView(a);if(8<=f.byteLength&&1718909296==f.getUint32(4)&&(f=g.Ct(f,0,1835295092),a=a.slice(f.dataOffset,f.dataOffset+f.size),!i2(a))){a=new Uint8Array(a);f=[];for(var k=0,l=0;k<a.length;){var m=a[k++];if(128>m)f[l++]=String.fromCharCode(m);else if(191<m&&224>m){var n=a[k++];f[l++]=String.fromCharCode((m&31)<<6|n&63)}else if(239<m&&365>m){n=
a[k++];var p=a[k++],r=a[k++];m=((m&7)<<18|(n&63)<<12|(p&63)<<6|r&63)-65536;f[l++]=String.fromCharCode(55296+(m>>10));f[l++]=String.fromCharCode(56320+(m&1023))}else n=a[k++],p=a[k++],f[l++]=String.fromCharCode((m&15)<<12|(n&63)<<6|p&63)}a=f.join("")}}if(a)try{if(g.v(a)){if("WEBVTT"==a.substring(0,6)){b=a;var u=c;e.g||(e.g=new l2);var y=e.g.o(b,u);.01>Math.random()&&g.Bp(Error("Deprecated subtitles format in web player: WebVTT"));var D=y}else b:{y=a;u=g.Xn(y);if(!u||!u.firstChild){var F=Error("Invalid caption track data");
F.params=y;throw F;}if("timedtext"==u.firstChild.tagName){if(3==parseInt(u.firstChild.getAttribute("format"),10)){if(!e.g){y={};var E=c1(b);E&&(y.lang=E,$oa.test(E)&&(y.te=1));e.g=new U1(y,e.i)}D=e.g.o(u,c);break b}var L=Error("Unsupported subtitles format in web player (Format2)");L.params=y;throw L;}if("transcript"==u.firstChild.tagName){var O=Error("Unsupported subtitles format in web player (Format1)");O.params=y;throw O;}var pa=Error("Invalid caption track data");pa.params=y;throw pa;}var za=
D}else{D=a;u=c;E=d;if(!i2(D))throw Error("Invalid binary caption track data");e.g||(e.g=new g2(E,b));za=e.g.o(D,u)}var Ka=za}catch(fd){g.P(fd),e.clear(),Ka=[]}else Ka=[];g.yJ(this.player,Ka);!this.P||this.R||x2(this)||g.Fy(this.u)||g.Gy(this.u)||(g.go(this.ba),Ka=t1({Kf:0,Ke:5,vg:5,vk:2,textAlign:0,te:0,lang:"en-GB"}),this.O=[Ka],e=["Click "," for settings"],this.ha||(za=new g.EB(g.aP()),g.I(this,za),this.ha=za.element),za=Ka.end-Ka.start,(b=g.ez(this.g))&&this.O.push(new q1(Ka.start,za,0,Ka.id,b)),
this.O.push(new q1(Ka.start,za,0,Ka.id,e[0]),new q1(Ka.start,za,0,Ka.id,this.ha,!0),new q1(Ka.start,za,0,Ka.id,e[1],!0)),g.yJ(this.player,this.O),g.eo(this.ba));!this.P||this.R||x2(this)||(z2(this,"module-enabled",!0),this.D&&(this.D.g=this.g),(Ka=g.X(this.player.app))&&Ka.o&&g.cC(Ka.o.l));this.P=!1}};
g.h.AE=function(a){this.H.push(a);this.X.xj()};
g.h.BE=function(a){g.bb(this.H,a);this.i instanceof m1&&this.i.A&&g.AJ(this.player,[a]);this.X.xj()};
g.h.rL=function(a){if(a instanceof r1){var b=this.M[a.id];b&&b.o!=a&&(b.dispose(),delete this.M[a.id],b=null);b||(b=Zoa(this,a))&&(this.M[a.id]=b)}else b=a.windowId,this.V[b]||(this.V[b]=[]),this.V[b].push(a)};
g.h.xL=function(){C2(this,this.O);this.O=null};
g.h.BA=function(){this.X.stop();g.Xb(this.V);this.H.sort(g.oD);var a=this.H;if(this.F){var b=(0,g.Xd)(a,function(c){return-1==this.F.indexOf(c)},this);
b.length&&(a=b)}(0,g.B)(a,this.rL,this);g.Jb(this.M,function(c,d){this.V[d]?(c.element.parentNode||g.FJ(this.player,c.element,4),c.qh(this.V[d])):(c.dispose(),delete this.M[d])},this)};
g.h.BL=function(){q2(this,{},!0)};
g.h.IC=function(){var a=B2.xb;a={background:a.background,backgroundOpacity:a.backgroundOpacity,charEdgeStyle:a.charEdgeStyle,color:a.color,fontFamily:a.fontFamily,fontSizeIncrement:a.fontSizeIncrement,fontStyle:a.bold&&a.Je?3:a.bold?1:a.Je?2:0,textOpacity:a.textOpacity,windowColor:B2.windowColor,windowOpacity:B2.windowOpacity};var b=r2(this,"display-settings")||{};null!=b.background&&(a.background=b.background);null!=b.backgroundOverride&&(a.backgroundOverride=b.backgroundOverride);null!=b.backgroundOpacity&&
(a.backgroundOpacity=b.backgroundOpacity);null!=b.backgroundOpacityOverride&&(a.backgroundOpacityOverride=b.backgroundOpacityOverride);null!=b.charEdgeStyle&&(a.charEdgeStyle=b.charEdgeStyle);null!=b.charEdgeStyleOverride&&(a.charEdgeStyleOverride=b.charEdgeStyleOverride);null!=b.color&&(a.color=b.color);null!=b.colorOverride&&(a.colorOverride=b.colorOverride);null!=b.fontFamily&&(a.fontFamily=b.fontFamily);null!=b.fontFamilyOverride&&(a.fontFamilyOverride=b.fontFamilyOverride);null!=b.fontSizeIncrement&&
(a.fontSizeIncrement=b.fontSizeIncrement);null!=b.fontSizeIncrementOverride&&(a.fontSizeIncrementOverride=b.fontSizeIncrementOverride);null!=b.fontStyle&&(a.fontStyle=b.fontStyle);null!=b.fontStyleOverride&&(a.fontStyleOverride=b.fontStyleOverride);null!=b.textOpacity&&(a.textOpacity=b.textOpacity);null!=b.textOpacityOverride&&(a.textOpacityOverride=b.textOpacityOverride);null!=b.windowColor&&(a.windowColor=b.windowColor);null!=b.windowColorOverride&&(a.windowColorOverride=b.windowColorOverride);
null!=b.windowOpacity&&(a.windowOpacity=b.windowOpacity);null!=b.windowOpacityOverride&&(a.windowOpacityOverride=b.windowOpacityOverride);return a};
g.h.GA=function(a,b){var c={};g.Ra(c,r2(this,"display-settings"));g.Ra(c,a);q2(this,c,b);this.player.N("captionssettingschanged")};
g.h.Os=function(){!this.B&&this.loaded&&(g.Jb(this.M,function(a,b){a.dispose();delete this.M[b]},this),this.BA())};
g.h.Yb=function(a,b){switch(a){case "fontSize":if(isNaN(b))break;var c=g.pd(b,-2,4);this.GA({fontSizeIncrement:c});return c;case "reload":b&&!this.B&&A2(this,this.g,!0);break;case "stickyLoading":void 0!=b&&this.u.tb&&z2(this,"module-enabled",!!b);break;case "track":if(!this.i)return{};if(b){if(this.B)break;if(!g.Na(b))break;if(g.Wb(b)){A2(this,null,!0);break}for(var d=e1(this.i.i,!0),e=0;e<d.length;e++){var f=d[e];f.i!=b.languageCode||c&&f.l!=b.languageName||(c=b.translationLanguage?Hoa(f,b.translationLanguage):
f)}!c||c==this.g&&this.loaded||A2(this,c,!0)}else return this.loaded&&this.g&&!x2(this)?b1(this.g):{};return"";case "tracklist":return this.i?(0,g.G)(e1(this.i.i,!(!b||!b.includeAsr)),function(k){return b1(k)}):[];
case "translationLanguages":return this.i?this.i.u:[];case "sampleSubtitles":this.B||void 0==b||D2(this,!!b)}};
g.h.getOptions=function(){var a="reload fontSize track tracklist translationLanguages sampleSubtitle".split(" ");this.u.tb&&a.push("stickyLoading");return a};
g.h.vj=function(){var a=this.g;return a?{cc:a.A}:{}};
g.h.rA=function(){this.loaded&&this.g&&!x2(this)?(z2(this,"module-enabled",!1),this.unload(),u2(this,!0)&&A2(this,v2(this),!1)):A2(this,x2(this)||!this.g?w2(this,!0):this.g,!0)};
g.h.yH=function(){var a=x2(this);u2(this,a)?A2(this,this.player.getAudioTrack().Kl,!1):this.l.captionTracks.length&&(this.loaded&&this.unload(),this.Bk()&&(a?A2(this,w2(this),!1):this.load()))};g.qU.captions=s2;})(_yt_player);
